### ISSUE TITLE
Color Theme Should Apply to Files Section Too

### ISSUE THREAD

**Issue by my2iu** [mozilla/thimble.mozilla.org#1100]
When I change to a light colour theme, it only affects the editor and not the files section. The colour theme should also apply to the files section. 

I am taking screenshots of Thimble and pasting it into a handout that will be printed out. The dark theme results in heavy ink usage, and it might make it hard to see things when it is printed out.

I also think Thimble should default to a light theme like a normal application instead of defaulting to some artsy dark theme.

**Comment by flukeout** [comment]
That's a good idea about the theme switching. From our testing so far, most people prefer the dark theme - which also lines up with the current trends in code editing. There might be a bug still where Thimble doesn't remember your color theme when you reload it, but we'll have that fixed.

**Comment by humphd** [comment]
@flukeout we could add a media query for print specifically, and optimize Bramble for paper without trying to solve this directly in the light and dark themes.

**Comment by my2iu** [comment]
No, I screen capture the web page, paste it into my lesson handouts, and print those out. The result is that the handout is mostly black with hard to read text. Having a print media query won't help with my screencaps.

**Comment by flukeout** [comment]
I can work out the CSS for the theme if someone wants to take this issue.

**Comment by humphd** [comment]
Fixing this would require making changes to the files (probably the "light" theme) here:

https://github.com/mozilla/brackets/tree/master/src/extensions/default/bramble/stylesheets

In terms of what should actually change, that would need some discussion.

**Comment by bkim49** [comment]
I would like to work on this bug! Hopefully I can fix it :( 
Is that okay?

**Comment by flukeout** [comment]
Sounds good @bkim49 let me know if you're able to get the theme to switch, and I can provide you with a stylesheet or colors.

**Comment by humphd** [comment]
@bkim49 to fix this, you're going to have to make changes in the [Brackets repo](https://github.com/mozilla/brackets), not Thimble.  We often file bugs in Thimble that end up needing to be fixed in Brackets, because it's unclear where the actual code fix is needed.

In this case, we have code in Thimble that lets the user pick between two themes, Dark and Light.  In an email you sent to me earlier, you found the code in Thimble that does this, and then on the Brackets side we have code to do the actual theme switching.  You wrote:

> I am currently working on the issue #1100 for lab3, but I believe I got into a problem. My issue is to change the colour theme of bramble under "FILES". To do this, I need to figure out a way to access bramble on thimble's js. I found the js file that enables text editor to change theme. I attempted to use that code to understand how thimble is able to manipulate bramble's theme. But the code hides the specific part that allows bramble's text editor change. 
```js
    function setTheme(theme) {
      if(theme === "light-theme") {
        bramble.useLightTheme();
        lightThemeUI();
        analytics.event("LightTheme");
      } else if(theme === "dark-theme") {
        bramble.useDarkTheme();
        darkThemeUI();
        analytics.event("DarkTheme");
      }
    }
    function toggleTheme() {
      if(bramble.getTheme() === "dark-theme") {
        setTheme("light-theme");
      } else {
        setTheme("dark-theme");
      }
    }
    $("#theme-light").click(toggleTheme);
    $("#theme-dark").click(toggleTheme);
```
>Here, the function setTheme() calls the bramble.useLightTheme() and bramble.useDarkTheme() function to change the colour of bramble text editor. I tried to search this function on github, but unfortunately no result came up.

Let me try to answer your questions.

First, searching for things on GitHub is somewhat annoying, in that you can *only* search for code in the original repo, not in forks.  For Brackets that means you have to search in the [Adobe Brackets repo](https://github.com/adobe/brackets), the original one from which Mozilla forked its code. However, in this particular case, that won't help, since the code you need is *only* in Mozilla's version.  Therefore, I'll guide you through this code path myself.

As you rightly describe above, Thimble triggers the change to the theme by calling `bramble.useDarkTheme()` and `bramble.useLightTheme()`.  These functions are defined in the Bracket's API code, here:

https://github.com/mozilla/brackets/blob/master/src/bramble/client/main.js#L837-L843

From here, a message is sent into the editor iframe, which is where the Brackets code is running (recall that I described in class how the editor needs to run inside an iframe on a separate domain for security reasons).  In Brackets, those messages are received and acted upon here:

https://github.com/mozilla/brackets/blob/master/src/extensions/default/bramble/lib/RemoteCommandHandler.js#L107-L112

This code uses the `Theme.setTheme()` which is defined here:

https://github.com/mozilla/brackets/blob/master/src/extensions/default/bramble/lib/Theme.js

The `Theme` module basically switches between one of two CSS files, which are located here:

https://github.com/mozilla/brackets/tree/master/src/extensions/default/bramble/stylesheets

As I mentioned in an earlier comment, I think the right fix for this bug is to focus on making CSS changes to the light theme file:

https://github.com/mozilla/brackets/blob/master/src/extensions/default/bramble/stylesheets/lightTheme.css

See if this makes sense to you.  I've explained the theme switching code because you asked, but it's not really important for you to touch most of it in this bug.  Your fix will be focused on CSS changes only.

Let me know if you have more questions.

**Comment by bkim49** [comment]
@humphd I have found the css which sets the colour for the side panel. It seems that this is not inside either darkTheme.css or lightTheme.css, but instead it is in sidebarTheme.css. 

https://github.com/mozilla/brackets/blob/master/src/extensions/default/bramble/stylesheets/sidebarTheme.css#L13

#sidebar {
	background-color: black;
	text-shadow: none;
	color: #333333;
}

Since this is the case, even if user selects different theme, sidebar will never be changed.

I tried fixing this by adding the code from sidebarTheme.css into darkTheme.css and lightTheme.css, changing the sidebar background-color according to the theme. At the same time removing the original sidebarTheme.css. But this did not work. Sidebar appeared as broken up when I tried this method. 

Now I am little stuck on how I should go about solving this problem.

**Comment by humphd** [comment]
@bkim49 I think you're on the right track with moving the `#sidebar {...}` CSS into both of the light and dark theme files, and removing it from sidebarTheme.css.  What does "sidebar appeared as broken up when I tried this" mean?  Can you put in some screenshots in this bug (you can just drag-and-drop images into this comment box, and Github will upload them).

You might find that you need to specify more CSS than just this one element to make it look right.  Also, @flukeout might be a good person to get involved in discussing this.

**Comment by flukeout** [comment]
I'm happy to assist with the actual themes once you manage to get that working @bkim49. Based on what you've described, I'm guessing the neither of the theme css files is getting applied ever?

As a test, what if you just set one rule per theme

darkTheme.css -  ``* { background: orange; }``
lightTheme.css -  ``* { background: blue; }``

These set the background color of all the elements, so it should be really easy test to tell if the theme CSS files are actually ever being applied.

Once you have that working, we can focus on the actual styles.

**Comment by flukeout** [comment]
@bkim49 what if you just make some changes to the existing lightTheme/darkTheme files? Make the background of one pink and the other blue, just to see if any changes you make to those files are having an effect.

**Comment by bkim49** [comment]
That is what happens to sidebar when I remove sidebar.css file and add all its content into lightTheme and darkTheme.css

![image](https://cloud.githubusercontent.com/assets/17182037/22767638/d0bca31c-ee4a-11e6-8e2c-c053456a1a78.png)

@flukeout This is the screenshot of thimble when I set the background color of all element to same colour using :

darkTheme.css  * { background: orange; }   * { background-color: orange; }
lightTheme.css  * { background: blue; }       * { background-color: blue; }


![image](https://cloud.githubusercontent.com/assets/17182037/22767824/e9618a76-ee4b-11e6-9eb7-1c5ca6d9ef6a.png)

![image](https://cloud.githubusercontent.com/assets/17182037/22767861/38a273de-ee4c-11e6-8633-0b642fde930e.png)

**Comment by flukeout** [comment]
@bkim49 I'll try this out in my local environment tomorrow and see what I can come up with. Btw, are you changing files in the dist folder or the src folder in brackets?

@humphd I'm guessing src files end up being compiled into dist files at some point?

**Comment by bkim49** [comment]
@flukeout This is my folder path:
..\brackets\src\extensions\default\bramble\stylesheets

**Comment by humphd** [comment]
You need to work with different CSS selectors for the actual file tree panel.  The `#sidebar` element isn't enough.  Take a look at this:

![screen shot 2017-02-09 at 9 59 22 am](https://cloud.githubusercontent.com/assets/427398/22788649/7d8fa19e-eeae-11e6-8ae7-2854367d4592.png)

If you use your browser's Inspector, you should be able to find the right elements, IDs, classes to modify.

**Comment by flukeout** [comment]
Okay, so as far as I can tell, it looks like all the CSS is added to the light/darkTheme.css is scoped to under ``#editor-holder``, which is why it never affects the ``#sidebar`` element.

In ``darkTheme.css`` I added ``* { background: green }`` and here's how it shows up when I inspect the site...

<img width="361" alt="image" src="https://cloud.githubusercontent.com/assets/25212/22796643/f508e7a2-eeaf-11e6-9872-8a069fc4b716.png">

**Comment by flukeout** [comment]
I've found where this happens, it's in ``ThemeManager.js``, starting on line 170...

<img width="579" alt="image" src="https://cloud.githubusercontent.com/assets/25212/22796818/bd9cc56c-eeb0-11e6-84d3-c664f431857b.png">

**Comment by gideonthomas** [comment]
I'm confused!

Why can't we make the change in the `sidebarTheme.css` file? We toggle the `.dark` class on the `body` element based on what theme is set. Why can't we add style rules like:

```css
/* Dark theme sidebar */
.dark #sidebar {
   ...
}
```

and

```css
/* Light theme sidebar */
#sidebar {
   ...
}
```

**Comment by DorelBarbu** [comment]
Hello! I would like to work on this issue, please. Could you assign me?

**Comment by humphd** [comment]
@bkim49 are you still working on this?  If not, let's pass it over to @DorelBarbu.  Let us know, please.

**Comment by bkim49** [comment]
@DorelBarbu I am working on a different issue. Please work on this! Thank you

**Comment by DorelBarbu** [comment]
Great. @humphd , could you please assign me?

**Comment by humphd** [comment]
@DorelBarbu it's all yours, go for it.  Let us know if you have questions, or need help.

**Comment by DorelBarbu** [comment]
Thank you, @humphd !! I've started to explore a little and to work on it. I'll let you know if I need anything, and I'll also use the Thimble chat.

**Comment by DorelBarbu** [comment]
Hello. I've studied the code and I came to the conclusion that we can use gideon's approach. I have one question: how can we check which theme is set? @humphd, @gideonthomas, a little help please?

**Comment by flukeout** [comment]
Just to keep this updated, @DorelBarbu and I figured out where the class was being applied to change the styles in the side bar and he's good to go.

**Comment by humphd** [comment]
The way we do the theme is as follows:

* In Thimble, we call into `bramble.js` here: https://github.com/mozilla/brackets/blob/master/src/bramble/client/main.js#L847-L853.  You can use `bramble.getTheme()` to figure out what the current theme is in Thimble.

* In Brackets we manage those calls (eventually) here: https://github.com/mozilla/brackets/blob/master/src/extensions/default/bramble/lib/Theme.js

Does that help?

**Comment by DorelBarbu** [comment]
Yes, it helps very much. I'm starting to work on it now! I've been busy in the last 2 days. Thank you, @humphd  and @flukeout !!

**Comment by flukeout** [comment]
Closed via https://github.com/mozilla/brackets/pull/646 - thanks @DorelBarbu!
