### ISSUE TITLE
Preview header moves to strange position when window is made too narrow.

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.mozilla.org#1154]
**Steps to reproduce**
- Start a new project, or refresh the editor
- Make the browser window narrower
- Eventually this happens...

![image](https://cloud.githubusercontent.com/assets/25212/10146591/5fae1f5a-65ef-11e5-84e8-6c94a09119e7.png)

**BUT, now try this**
- Start a new project, or refresh the editor
- Change the width of the preview slightly (by clicking and dragging where the preview and editor join)
- Make the window narrower again like before
- This time, it works fine...

![image](https://cloud.githubusercontent.com/assets/25212/10146649/a107b3ee-65ef-11e5-9a46-23cfd28ce451.png)

**Comment by flukeout** [comment]
It seems like when the column-resizing code fires, things get set up appropriately and the columns scale correctly. We probably just need to fire that same code once when the editor loads.

**Comment by humphd** [comment]
In theory we already do this here:

https://github.com/mozilla/thimble.mozilla.org/blob/fa3dde088dc016a562520e62a9df1f5558ba8f70/public/editor/scripts/editor/js/fc/bramble-ui-bridge.js#L23-L25

Fixing this would require debugging the timing of this function call, and seeing if it's being done at all.

**Comment by dsych** [comment]
Can I try to do this one?

**Comment by flukeout** [comment]
Sounds good @dsych - this one might be tricky, let me know if you can reproduce it reliably.

**Comment by dsych** [comment]
I am having trouble reproducing the bug by the exact steps you've described above.
However I've managed to do it the other way, as follows:
Enlarge the browsing window by dragging it to the right. Eventually this will happen.
![bug](https://cloud.githubusercontent.com/assets/16144679/22402639/a3e3ea8e-e5cc-11e6-9001-99dc2ef1e720.png)

**Comment by dsych** [comment]
I am a little stuck right now. I've narrowed it down to brackets failing to initiate some value to update it later.
I found a piece of code that does the update of the layout(I believe it is being sent to thimble afterwards to adjust the headers). It is in brackets/src/utils/Resize.js
`
function doRedraw() 
`
on line 364. I've compared sequence of calls for the onload case when the bug appears and a working version after resize of the preview. It is identical. 

Please let me know if you have any ideas.

**Comment by dsych** [comment]
Update:
I think I've located the source if the problem. According to the de5842fa7 , sidebar had similar problem because its size was manually set. The same thing is happening to the first pane (editor). File src/extensions/default/bramble/Ui.js line 107-109.
```javascript
        var firstPaneWidth = BrambleStartupState.ui("firstPaneWidth");
        if(firstPaneWidth) {
            $("#first-pane").width(firstPaneWidth);
        }

```

Let me know what you think.

**Comment by flukeout** [comment]
Hey @dsych - will check into this shortly and get back to you.

**Comment by flukeout** [comment]
Im having a bit of trouble with my dev environment right now, so I'll be a bit longer to chime in. So for you, if you create a new project then immediately resize the browser window do the editor and preview panes adjust in size as you change the browser width?

I recorded what happens to me in FF and Chrome.. first browser resize doesn't change the columns, second one deoes...

![width](https://cloud.githubusercontent.com/assets/25212/22706270/7ad78ee4-ed23-11e6-9f8d-038beeac28ca.gif)

Not the same for you?

**Comment by dsych** [comment]
The problem is that onload brackets editor window is being static. After you change the editor size with the preview resize, editor starts to behave the way it is expected. I found the problem is that bramble manually sets the width for editor, which ,I assume, is causing the problem. There was a similar https://github.com/mozilla/brackets/pull/377 issue for the sidebar window, which was fixed(see comment above).

**Comment by humphd** [comment]
From email:

> After researching the problem and examining the source code, I have, supposedly, located the cause of the problem. Now, it turns out that there has been a similar issue before and it was fixed by you. Here us the issue https://github.com/mozilla/brackets/pull/377 and here is the commit https://github.com/mozilla/brackets/pull/377/commits/36fe37a432a3847acfa0e33ebc15c39acb68110f . It seems that I need to incorporate similar logic for the editor.

First of all, this is a hard bug to fix, which is why no one has fixed it!  So don't feel discouraged that it's taking so long to debug.  I'm not 100%, but I strongly suspect that we need to tell Bracket's internal layout code to adjust after we manually alter the DOM elements for each of the 3 panes in the editor.  I *think* that this involves calling https://github.com/mozilla/brackets/blob/master/src/view/WorkspaceManager.js#L230-L238.

I also note that we do seem to do it here: https://github.com/mozilla/brackets/blob/master/src/extensions/default/bramble/lib/UI.js#L106-L118.  This is likely where our bug is, namely, that we alter the `firstPane`'s width, but not the `secondPane`, and also, that we likely don't call the right.  I also notice in the Brackets' tests, they sometimes call `recomputeLayout(true)` and sometimes without forcing a redraw of the editor, see https://github.com/adobe/brackets/blob/f028b3ecdf2017498196f39ddbbe4a2364366c92/test/spec/EditorRedraw-test.js#L53.

There's a ton of "initialization" code and layout update code in https://github.com/adobe/brackets/blob/e78688aaa49af789726114721568637550bfaf86/src/view/MainViewManager.js.  I think we just need to call some of it before/after we mess with the pane DOM node widths.  Question: are we going through this code path currently? https://github.com/adobe/brackets/blob/e78688aaa49af789726114721568637550bfaf86/src/view/MainViewManager.js#L1617  It seems to call `_initialLayout();`, which we might want to call directly.  Maybe we have a timing issue, and need to do what we're doing before/after this?

I'd put a bunch of `console.log()` messages in the `MainViewManager.js` and try to understand what is and isn't happening.  I'm 95% sure we need to be dealing with something in here.

**Comment by flukeout** [comment]
Closed via https://github.com/mozilla/brackets/pull/581 - thanks again for your work @dsych
