### ISSUE TITLE
Improve UI contrast for projectors

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.mozilla.org#1251]
Imported from https://bugzilla.mozilla.org/show_bug.cgi?id=1206518

**Steps to reproduce**

We use Thimble for teaching at Kids/Girls Learning Code, often projected on an overhead projector

**Actual results**

The dark file index and header of the editor have very low contrast when projected on a white screen/wall. The names of the unselected files are barely visible in the sidebar

**Expected results**

higher contrast or dark text on a light background would make the text a lot easier to read when projected.

**Comment by tessalt** [comment]
it's the sidebar/header colours that have low contrast, and those don't change with the theme.

**Comment by humphd** [comment]
Indeed. This also reminds me of #1100, with a use case related to printing and contrast.

**Comment by sanariaz154** [comment]
hi @humphd  i'd like to work on this issue ,  can you guide me where to start ?

**Comment by humphd** [comment]
I think fixing this will require 2 different fixes.  One in Thimble (for header) and one in Brackets (for sidebar and editor).  #1100 addressed a similar issue with people wanting to print and not have the sidebar be solid black.  I'm going to get @flukeout to weigh in on everything I say below, since he'll have final say on how this ends up looking.

In Brackets, we have a dark and light theme.  I think we probably want to consider adding a 3rd state for high-contrast.  Most of the code that handles flipping between themes is in https://github.com/mozilla/brackets/blob/master/src/extensions/default/bramble/lib/Theme.js, and the stylesheets for this are in https://github.com/mozilla/brackets/tree/master/src/extensions/default/bramble/stylesheets.  We should probably start by creating the theme itself, and I'd recommend we focus on very light/white backgrounds and dark fonts/icons so printing also works well, but again, @flukeout can say more.

In Thimble, the changes will be two-fold.  First, the theme switching UI is here https://github.com/mozilla/thimble.mozilla.org/blob/948deb0b3231947aae366deaebb58e769222ffc2/public/editor/scripts/editor/js/fc/bramble-menus.js#L83.  I'm not sure how we'll do the 3rd option, but assume we need to add one somehow.

Next, we'll need to deal with how Thimble and Brackets talk to each other about theme info.  That happens in an API defined in Brackets here: https://github.com/mozilla/brackets/blob/master/src/bramble/client/main.js, search for `theme` in that file and you'll see the various methods and events.  Fixing that stuff can come later, and I can walk you through when you're ready.

For now, I'd focus on the look of the theme, and the CSS.  You could start by hacking the light theme we have, and get it to do what you want, then we can split it out into a third thing and change the code to allow for 3 of them.

Let me know what of this is unclear, and I'll try to expand.

**Comment by sanariaz154** [comment]
sorry I couldn't work  I was away for a week .
can you tell me do I have to install thimble for this or I can see changes through localhost/src as we could for brackets ?

**Comment by humphd** [comment]
Likely you'll have to make changes in both Brackets and Thimble, but you can start in Brackets, and just debug it the same way you did your other patch with http://localhost/src/hosted.html.  Eventually, you'll also need to work in Thimble, so you'll need to do the local setup for it, which uses Vagrant to run the various services it uses in a VM.  See the readme file for details, and let us know if you have questions.

**Comment by humphd** [comment]
This work has stalled, so I'm going to put it back in the general pool of bugs.  If someone wants to work on it, let us know.

**Comment by ayush9398** [comment]
Hi, everyone
I would like to work on this...
I am new at contributing to open source so can anyone guide me, please?

**Comment by gideonthomas** [comment]
Hi @ayush9398, I have assigned https://github.com/mozilla/thimble.mozilla.org/issues/2447 to you per your request. I would suggest starting with that and then once you're done with it, we can assign this to you if it's still available and if you're still interested.

**Comment by ayush9398** [comment]
Ok, thank you @gideonthomas.

**Comment by gideonthomas** [comment]
assigned to you @ayush9398

**Comment by gideonthomas** [comment]
@humphd has some comments above on how you might go about fixing this issue, let us know if you need some more info.

**Comment by ayush9398** [comment]
OK @gideonthomas , thank you.

**Comment by flukeout** [comment]
@ayush9398 - unfortunately this is not a good first bug because the brackets theme stylesheet is annoying to work with and we'll have to re-make a lot of the icons to work within a light theme. I'll close this issue for now and re-file separately.

**Comment by ayush9398** [comment]
No problem @flukeout , I understand....
It would be a huge help if you could assign me some other issue...

**Comment by flukeout** [comment]
I'll look for one now @ayush9398

**Comment by flukeout** [comment]
Want to do this one that you filed @ayush9398 - https://github.com/mozilla/thimble.mozilla.org/issues/2469
