### ISSUE TITLE
Add directory & file view when looking at a published folder without an index.html file.

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.mozilla.org#1260]
Something along the lines of...

![image](https://cloud.githubusercontent.com/assets/25212/11256233/98970024-8dff-11e5-8102-547d40a4459d.png)

@humphd said he's already got a solution.

In addition to this, we'll need to add a message at the top of this view that says something like...

`You're seeing this list of folders and files because the author of the project didn't include an index.html file, which would have been loaded automatically.`

Migrated from #1203

**Comment by hannahkane** [comment]
Messaging sounds slightly passive aggressive. :) Suggested edit: 

``You're seeing this list of folders and files because this project doesn't include an index.html file. Index files, when included in a project, are displayed automatically.``

**Comment by gideonthomas** [comment]
We have come up with a UX solution here: #1569, will be tracking the conversation there as well.

**Comment by humphd** [comment]
I'm ready to start on this bit, and have a question.  We have no good way to flag a file as generated vs. user created, especially across remixes.  At the point of publishing, I can look for `{root-dir}/index.html` and if it's missing, automatically generate something like you have above.  However, this file will be static, and if the user (or the remix user) doesn't touch it, but other aspects of the filesystem change, it will go out of sync.  I'm not sure that's a huge issue, but I want to flag it.  I don't think we should invent some complex set of flagging for this case.

There are a few ways to go here:

* We could choose to have the generated page not refer to anything in the filesystem as such, and just provide a generic "Hey, you don't have an index.html file, so that's why you're not seeing your stuff..." message.  This would be primarily aimed at the original author, who would hopefully correct the problem by editing the generated `index.html` file.
* On publish, we could scan the root dir for other HTML files, and suggest something that will work for the publish URL vs. something that will break.  This assumes that there is an HTML file of some kind (a fairly safe assumption, but not required I guess).  So instead of doing what we do now, which is to show "Here's a link you can share... https://thimbleprojects.org/humphd/128353", we'd do "Here's a link you can share...https://thimbleprojects.org/humphd/128353/other-file-we-found.html"
* I could do exactly what's suggested above and statically generate an `index.html` file that will show you all the various files (or maybe just the HTML files?) in the root dir.

Which way should I go?

**Comment by humphd** [comment]
Sorry, I didn't realize this was closed.  I'll move the comment over to the other bug.
