### ISSUE TITLE
Warn users when they publish a project without an index.html file

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.mozilla.org#1261]
When users publish a project without an index file, Thimble throws a 404 message (and eventually will show a directory listing) which might be different than what a user expects.

Let's add a little warning / help message to the Publish popup when a user is about to publish without an index.html file. Something like...

```
This project doesn't have an index.html file! Add one and it 
will be shown automatically when visitors come to
your web site / project.
```

Migrated from #1203

**Comment by gideonthomas** [comment]
This is coming up surprisingly more often than we thought. Users think it is an error because that is what we show them when they navigate to the published version of their project. Probably worth fixing this sometime (as a UX issue ideally as mentioned above)!

cc @hannahkane and @flukeout

**Comment by flukeout** [comment]
Where is it coming up more often? Are we getting some feedback? I'll dig into the DB to see how many published projects fall into this category.

Looks like the directory listing idea from #1203 is off the table, so that leaves us with a couple of options..
* Warning + allow publish
* Disallow publish until fixed

I'll check the stats and then we can figure out which to pursue.

**Comment by humphd** [comment]
What about if we just do a "You don't have an index.html page" learning/info style custom 404 on our s3 bucket?

* http://stackoverflow.com/questions/5500138/amazons3-custom-error-pages
* https://aws.amazon.com/blogs/aws/host-your-static-website-on-amazon-s3/

Then if people get the 404, they can take action and make one or use the proper URL based on the renamed page.

**Comment by gideonthomas** [comment]
In the past two months I have had about 4 users either file issues or comment on IRC that their published projects are showing 404s and all those times it has been because they were missing an index.html file.

I think Warning + allow publish should be fine though, users should probably just need to be aware of it.

@humphd but it's really tricky figuring out whether to show the regular 404 page or the "missing index.html" 404 page though. I'm not even sure if AWS supports adding that logic.

**Comment by Pomax** [comment]
Why not meet the user where they're at, and explain to users that somethings going to go wrong while offering them not just advice, but concrete options on how to deal with this situation?

"You are about to publish a project without a default 'index.html' landing page, which means your site will only be accessible if people visit specific pages. If you would like people to be able to visit your site without specifying the specific page, please pick one of the following:

"- [ ] create a new index.html for me
"- [ ] create a redirecting index.html that points to [dropdown menu with all .html files]

"If this is the first time you heard about needing default pages, then you might find [link to SUMO or something] worth reading, which explains some of the basics around how web servers typically serve content"

... or something along those lines. Offer them ways out instead of merely saying things are going to go wrong, and you have a learning/teaching moment right there.

**Comment by hannahkane** [comment]
It's too bad it's hard to differentiate whether it's a regular 404 or a missing index page, because that could really help with troubleshooting. The warning before publishing makes sense, and we should probably *also* include an explanation on the editor view even *after* publication, so that they can resolve the issue if they missed the first warning.

In terms of the warning itself, I think we could keep it simple, as in Luke's original comment. We can create a SUMO question that has more details and link to it for those who want more info.

**Comment by angielopez** [comment]
I am having an issue with publishing, although I already have an existing "index.html" page... HELP!?!?

**Comment by humphd** [comment]
@angielopez can you tell us about your issue?  What's happening, or not happening?

**Comment by angielopez** [comment]
I figured out the solution to my problem. I had previously named my "index.html" with another name when I published it, so when I renamed it back to index, it wasn't working. I had to unpublish and then republish in order for it to work again.
Thank you!

**Comment by gideonthomas** [comment]
@angielopez, when you renamed it back to `index.html` and clicked on the "Publish" button in the top-right corner, did it show you something like "Update Published Version" or did it just show you the link with the "Unpublish" button?

**Comment by gideonthomas** [comment]
We have come up with a UX solution here: #1569, will be tracking the conversation there as well.
