### ISSUE TITLE
Show Preview panel below the Editor panel

### ISSUE THREAD

**Issue by jjnilton** [mozilla/thimble.mozilla.org#1314]
Hello, here goes a suggestion: to make a option to show the Preview panel below the Editor, giving better experience to narrow resolutions on split view/multi windowed workspaces.

![image](https://cloud.githubusercontent.com/assets/228200/12071954/394e6642-b0a6-11e5-808a-30fdc6147e02.png)

**Comment by hannahkane** [comment]
Good suggestion, @jjnilton. I think we'd need to discuss this in the context of #1246, where we were thinking of separating out the Tutorial pane into a section below the Editor.

**Comment by humphd** [comment]
One data point is that Bramble supports this (we have an API for it, which we could expose to Thimble).  If we did this, we'd have to alter the logic for how the two halves of the user bar get sized, since they currently used layout events from Bramble to match the widths of the file tree, editor, and preview panes.

**Comment by humphd** [comment]
I think it's unlikely we're going to do this, because it will break a lot of what we do with the headers over the editor/preview.  I'm going to close, and if we decide to actually take it on, let's file a new bug.
