### ISSUE TITLE
Editor 'stuck loading' in Firefox

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.mozilla.org#1319]
When @kristinashu tries to remix https://d157rqmxrxj6ey.cloudfront.net/flukeout/22181/, firefox hangs on the loading overlay in the editor.

The last console error that is thrown is...
`SecurityError: The operation is insecure. main.js:16:0`

This seems like the same problem we've encountered in Chrome that is resolved by clearing all of the localstorage and indexed db entries for thimble, except I can't do that in the Firefox dev tools.

**Comment by gideonthomas** [comment]
@flukeout That's a pretty weird error and I suspect that it might not be the same as the Chrome issue.
@kristinashu are you able to remix it in chrome? Also, would you be able to tell me the version of firefox that this is failing on?

**Comment by kristinashu** [comment]
@gideonthomas Yup, works great in Chrome. I'm on Mac Firefox 44.0b4

**Comment by humphd** [comment]
@Pomax and I were trying to help a person on Twitter with the same problem, and could never get to a satisfactory level of understanding.  One thing I did discover in my research is that `localStorage` will honour the browser pref for disabling cookies, which means that trying to touch storage will throw this non-catchable error.  I'm not sure if that's at play here or not?

**Comment by gideonthomas** [comment]
Hmm so if I turn off cookies and try to remix that project, I see the `SecurityError: This operation is insecure.` but it shows it for `bramble.js:3:0` and not `main.js:16:0` that's in the error above. Also, It doesn't hang and instead I see the `There was an error loading your Project...` message (which is expected). So I doubt that it's having issues with accessing storage. 

I wonder if there is an easy way to debug this. But we need to be able to reproduce it locally so that we can take a look at the un-built un-minified code.

**Comment by humphd** [comment]
Yeah, I've never been able to reproduce this at all.  I suspect it's a corrupt db or something in the profile.

**Comment by gideonthomas** [comment]
Possibly related: https://github.com/mozilla/thimble.webmaker.org/issues/1136

**Comment by Calefornia** [comment]
If you change your custom history settings and allow cookies, it suddenly works, although I have no idea why. I'm assuming you were restricting third parties to some extent, but you can just add these exceptions:
https://mozillathimblelivepreview.net
https://thimble.mozilla.org

Hopefully this works for you.

**Comment by gideonthomas** [comment]
We have come up with a UX solution here: #1568, will be tracking the conversation there as well.
