### ISSUE TITLE
Preview does not show dynamically added links to files in the project

### ISSUE THREAD

**Issue by cathyatseneca** [mozilla/thimble.mozilla.org#1322]
Hi,

I was trying to figure out why an image wasn't loading for a p5.js sketch within thimble (my cousin claims it loads using FF but not chrome.  I couldn't get it to load in either). I can load it through an image tag but not through the sketch.  Console gives a 404 error when I looked at it.

I was going to publish and send the url but it seems that the sketch with the image does load in the published version.  However, the image won't load through the sketch in preview mode.

published version is here.

https://d157rqmxrxj6ey.cloudfront.net/umleung/22326/

When I tried to remix it, the image didn't load in preview

Let me know if you would like the zip archive

**Comment by gideonthomas** [comment]
@humphd not sure how we want to approach this (it won't be easy) but this involves re-writing paths in js files to blob urls because in @cathyatseneca's project, an image is loaded dynamically through js using a relative path so in the preview, the path that it resolves to is `https://mozillathimblelivepreview.net/..../mypath` which 404s.

@cathyatseneca I had a similar issue when loading content dynamically with js and the way I got around it was to host the content on dropbox or something similar and use the public url instead of `images/beaker.png`. That is a quick way to circumvent this problem for now.

**Comment by humphd** [comment]
The only way to solve this is to rewrite our server using Service Workers, and let arbitrary URLs from JS work without needing to pre-render.  I'm planning to try it this winter as part of my personal research, but it won't happen soon.

On Jan 6, 2016 10:31 AM, Gideon Thomas <notifications@github.com> wrote:

@humphd<https://github.com/humphd> not sure how we want to approach this (it won't be easy) but this involves re-writing paths in js files to blob urls because in @cathyatseneca<https://github.com/cathyatseneca>'s project, an image is loaded dynamically through js using a relative path so in the preview, the path that it resolves to is https://mozillathimblelivepreview.net/..../mypath which 404s.

@cathyatseneca<https://github.com/cathyatseneca> I had a similar issue when loading content dynamically with js and the way I got around it was to host the content on dropbox or something similar and use the public url instead of images/beaker.png. That is a quick way to circumvent this problem for now.

**Comment by flaki** [comment]
This came up with this [small space invaders game](https://thimbleprojects.org/flaki/51988/) I was doing for a workshop, which loads sprites from local assets. Thanks for this, I'm going to work around this by hosting the sprites externally (or linking from the published version) for now.

@humphd I've been working with service workers for some time now, I'd love to help you out with any of those bits -- but I'm not awfully familiar with the bramble-side and in general how Thimble handles things.

Maybe you could drop some info in #1459 or a separate issue and get us started there?
Would be lovely if we could pull this off.

**Comment by humphd** [comment]
Hey @flaki, if you're interested in hacking on this with me, I'd be happy to work with you.  What I'll do is file a bug in the Brackets code (where this has to get fixed), and outline what's needed.  It sounds like you have more experience with SW than I do--I'm still actively learning them; but I know the Brackets code intimately.

**Comment by humphd** [comment]
@flaki (and others): see https://github.com/mozilla/brackets/issues/549, where I've dumped some of my thoughts.  Let's discuss there if you want to hack on this.  I can answer questions or go into more detail.

**Comment by humphd** [comment]
Closing, since this needs to happen in Brackets, and is already well understood/discussed in bugs there.
