### ISSUE TITLE
Limit total project size

### ISSUE THREAD

**Issue by gideonthomas** [mozilla/thimble.mozilla.org#1326]
I can't find the issue for this that we filed before so re-filing. We probably want to limit the total size of a project for a couple of reasons:
1. It will be taxing on the server if it happens as a drag 'n drop. 
2. It will increase load time significantly
3. Remixing will take longer

cc @Pomax

**Comment by Pomax** [comment]
It'll also prevent an easy exploit, so one idea would be to have a soft cap and a hard cap, where taking up anywhere between zero and the soft cap, things work fine; once you go over the soft cap, you get an advisory that your project is getting really big and you should consider moving some files to a dedicated host instead, so you can link to them instead, but still allow the data to go through. Once you hit the hard cap, you get an advisory that your project is too large to save, and that you'll need to remove some assets from your projects and host them somewhere else, before you can save again.

Note that this will also need to be enforced at publish.wmo, because JavaScript is neat, and you can always bypass a site's UI to just send the GET/POST *you* want.

**Comment by Pomax** [comment]
cc @simonwex @cadecairos for opinions, too.

**Comment by simonwex** [comment]
I think this is more than a single metric, here are a few things to measure:

 * Max single file size
 * Max file size per content-type – This is a teachable moment
 * Max number of files
 * Max total project size

**Comment by Pomax** [comment]
we're already restricting single file size, although the idea of file size per content-type is an interesting one. I'd like to know @humphd's thoughts on this too. I don't think limiting the number of files is a metric that will be all that useful, given that different projects need different things. If I want to talk about ASCII for instance, with 255 .svg files in an "images/" dir, and each SVG file is <1kb, then that makes a lot of sense actually. Sure, if you're good at dev already you'd bundle them but that's not what Thimble is about (yet?). 

Total project size feels like the main metric here, with a soft cap that warns you you're pushing the limits, and a hard cap that tells you you've hit it and will need to delete some files before you can save more because you're going above and beyond what Thimble can do for you - which is also a teachable moment, where we can explain external hosting, CDNs, not putting things you can pull off the internet in your own project, etc.

**Comment by dsych** [comment]
Hi,
If nobody is working on it, I would like to implement it.

Please let me know if you have any suggestion on the metric. The "maximum project size" makes the most sense to me right now.
@gideonthomas @Pomax @simonwex

**Comment by Pomax** [comment]
@dsych I don't think this issue is strictly ready to get code written for it - we haven't settled on policy yet, so any implementation will be blocked until that happens.

**Comment by humphd** [comment]
Let's start by doing what's described above in https://github.com/mozilla/thimble.mozilla.org/issues/1326#issuecomment-172995306, specifically:

* Create a new object/module in Thimble (or maybe Bramble) that interacts closely with the filesystem, and allows you to query for info about the project (number of files, size of project, largest file(s), etc)
* Add some events to this object/module as well so that you can listen for things like "maximum-project-size-exceeded" or whatever, and prompt the user.
* Make this object/module configurable at runtime (e.g., via it's constructor or initialization method) so that later we can decide on our limits and pass them in.

For now, this code can be about info vs. enforcement, and in a later bug, we can add UI and enforcement.

**Comment by gideonthomas** [comment]
+1 to @humphd's suggestions. Just adding a few more thoughts:

- I think this module should be on Bramble(Brackets) and would ideally be on its API, i.e. `bramble.getProjectInfo()` or something like that
- You can probably add another api function `bramble.configureProject()` or something like that which will take in an object that might have properties like `maxSize`, `maxFileSize`, `maxNumberOfFiles`, etc. (probably based on @simonwex's comment above for now)
- Add the events on the `bramble` API similar to these: https://github.com/mozilla/brackets#bramble-instance-events

@dsych, I would probably start by making the changes in `src/bramble/client/main.js` to add the API functions there. Then it might be easy to flesh them out and use them to interact with Bramble core to actually get that data. Let us know if you need any guidance on where to find code.

**Comment by humphd** [comment]
Here's some thoughts on one way to approach this.

* +1 to putting this on the Bramble API vs. in Thimble, and have Thimble consume it.
* I'd suggest that we extend the `Bramble.mount()` function like so:
```
// Specify a set of limits to use.  If none are provided, we use defaults (no idea what those are)
var projectLimits = {
  fileSize: 1234, // max size of any file in bytes
  fileCount: 50, // total number of files you can have in a project
  projectSize: 10000 // total number of bytes for all files in this project
};
var bramble = Bramble.mount("/project", "index.html", projectLimits);
...
var info = bramble.getProjectInfo();
// info = { limits: {}, actual: {} } where limits is what was passed in originally,
// actual = { fileCount: 6, projectSize: 5213, largestFile: 1234, ... }
...
// Register events
bramble.on("projectFileSizeExceeded", function(data) {
  var path = data.path;
  var size = data.size;
  console.log("File too large!", path, size);
});
...
bramble.on("projectFileCountExceeded", function(data) {
  var count = data.count;
  console.log("Too many files!", count);
});
```
* Should the API call for getting project info be sync or async with callback?

Agree to making these changes in `src/bramble/client/main.js` in Brackets.  However, don't feel the need to make that file bigger, create a new module that it `require()`'s in.

**Comment by Pomax** [comment]
One important bit missing: bramble should have an API call that lets clients override project limits such as 
```
bramble.setProjectLimits({
  fileSize: ...,
  fileCount: ...,
  projectSize: ...
}, optionalSpecificProjectId);
```
Of importance is that second argument for specific project IDs, so that clients can decide that some projects are worth changing the defaults over without affecting every project in the full set of client-managed projects.

**Comment by gideonthomas** [comment]
bramble does not deal with project IDs (it isn't aware of what it is). Just calling `setLimits` should probably just set the limits for the currently mounted path because each bramble instance is tied to one mounted path (which we treat as a single project).
```js
bramble.setProjectLimits({
  fileSize: ...,
   ...
});
```
should be enough. I think to start, let's begin with setting the project limits once in the `mount` function as @humphd suggests and then slowly add these extra methods.

**Comment by Pomax** [comment]
wfm. Is this a good first bug?

**Comment by dsych** [comment]
Well, if you are asking me, I am up for the challange.

**Comment by Pomax** [comment]
awesome, @dsych, have at it!

**Comment by dsych** [comment]
Hi @Pomax  @gideonthomas ,
I am facing a slight problem. I've defined my code as a separate model in bramble/client folder as ProjectLimiter.js. When I try to require it in bramble/client/main.js to create a projectLimiter object, require fails. Code:
```javascript

var projectLimiter = require("bramble/client/ProjectLimiter");
``` 

And here is a snippet of the ProjectLimiter module. This is just for debug for now:

```javascript
define(function(require, exports, module) {
"use strict";
    exports.initLimits =  function (projectState){
        console.log(projectState);
    };
});
```

Here is the errors:

> GET http://localhost:8000/src/bramble.js 

and 

> Uncaught Error: Script error for: bramble
http://requirejs.org/docs/errors.html#scripterror
    at C (require.min.js:8)
    at HTMLScriptElement.onScriptError (require.min.js:30)

**Comment by humphd** [comment]
You should follow the pattern in `main`:

```js
define([
    // Change this to filer vs. filer.min if you need to debug Filer
    "thirdparty/filer/dist/filer.min",
    "bramble/ChannelUtils",
    "bramble/thirdparty/EventEmitter/EventEmitter.min",
    "bramble/client/StateManager",
    "bramble/client/ProjectLimiter",
    "bramble/thirdparty/MessageChannel/message_channel"
], function(Filer, ChannelUtils, EventEmitter, StateManager, ProjectLimiter) {
   ...
```

**Comment by dsych** [comment]
@humphd In this case I would need to create object manually as follows?:

```javascript
var projectLimiter = new ProjectLimiter();
```

**Comment by dsych** [comment]
Follow-up, if I don't explicitly instantiate the projectLimiter object and call function defined in the module, I get an undefined property error.:

```javascript
//main.js
ProjectLimiter.initLimits(projectLimits);


//ProjectLimiter.js
    exports.initLimits =  function (projectState){
       // maxProjectState = projectState;
        console.log(projectState);
    };
```
Error:
>Uncaught TypeError: Cannot read property 'initLimits' of undefined
    at EventEmitter.Bramble.mount (main.js:152)

**Comment by humphd** [comment]
It think it's how you're defining your module in `ProjectLimiter`.  Do this:

```js
define(function() {

  var ProjectLimiter = {};

  // define things on ProjectLimiter like you do on exports

  return ProjectLimiter;
});
```

**Comment by dsych** [comment]
still gives the same error. Here is how I define functions for ProjectLimiter:
```javascript

var proto = ProjectLimiter.prototype;
    proto.initLimits =  function (projectState){
        console.log(projectState);
    };

return ProjectLimiter;
 ```

**Comment by humphd** [comment]
You haven't defined `ProjectLimiter` in that code.  You won't need a prototype in this case, becuase you aren't using instances. Try this:

```js
var ProjectLimiter = {}
ProjectLimiter.initLimits = function(){ ...};

return ProjectLimiter;
```

You only need to put things on the `prototype` if you have instances.  It would then be:

```js
function ProjectLimiter() {}
var proto = ProjectLimiter.prototype;

proto.initLimits = function() {...};

return ProjectLimiter;
```

**Comment by dsych** [comment]
Tried both ways, same problem.

**Comment by humphd** [comment]
Do a PR and show us your actual code.

**Comment by dsych** [comment]
![debug_brackets](https://cloud.githubusercontent.com/assets/16144679/23571807/40261594-0039-11e7-8f95-acea7e296535.png)

**Comment by humphd** [comment]
I mean put all of it up, including how you're calling it in the other code.  Just push your branch and start a PR.  It's easier to discuss real code vs. snippets

**Comment by dsych** [comment]
Yeah, sorry. Here is PR https://github.com/mozilla/brackets/pull/620

**Comment by dsych** [comment]
Hi,
I've updated my pull request and was wondering if anyone might be able to take a look and tell me if I am on the right track.
Bare in mind that I've only tested this code with Brackets.

**Comment by dsych** [comment]
After a recent pull, I can no longer run standalone Brackets, I gives me this error:
>Uncaught TypeError: Cannot read property 'defineMode' of undefined
    at _patchCodeMirror (LanguageManager.js:209)
    at Object.<anonymous> (LanguageManager.js:1114)
    at Object.execCb (require.min.js:29)
    at Z.check (require.min.js:18)
    at Z.<anonymous> (require.min.js:23)
    at require.min.js:8
    at require.min.js:23
    at v (require.min.js:7)
    at Z.emit (require.min.js:23)
    at Z.check (require.min.js:19)

I believe, I heard @humphd talking about a patch that fixed this problem... Any ideas why it does not work for me?

**Comment by humphd** [comment]
https://github.com/mozilla/thimble.mozilla.org/issues/1598 seems related to this.

**Comment by humphd** [comment]
https://github.com/mozilla/thimble.mozilla.org/issues/1803 is also related.

**Comment by humphd** [comment]
We added code when publishing to indicate that a project is missing an `index.html` (also related to the work @dsych did here):

![screen shot 2017-06-07 at 1 31 59 pm](https://user-images.githubusercontent.com/427398/26892294-d784752e-4b85-11e7-86fa-0c2a6a3a11d1.png)

Could we do something similar with regard to total project size?  If it's over a certain size, we could either show a warning, or disallow it completely.  In Brackets we disallow files larger than 3 MB, and ZIP files larger than 5MB.  We should consider what we want to accept for total published project size.

I'm going to remove the Assigned label here, since this has been dormant for months.  If someone wants to work on it, let me know.

**Comment by flukeout** [comment]
Just wanted to add that we just got a support email from someone with a project that is failing to load. Sure enough, it's massive (10+ megs of images). I'm trying to see if just letting it load for longer will work, or where things might have broken.

**Thoughts**

* @gideonthomas something to think about with AWS, does that help us do bigger files etc?
* I think we should enforce some kind of size limit and indicate it in the file tree...
  * 1 of 3 MB used etc...
  * Upgrade for more storage?!
* For large images, we could try to help by automatically resizing images if they're beyond a certain size?
* For saving and loading, it would be nice to have indicators of what is happening.
  * 200kb of 1000kb uploaded... 
  * For long loads, things will just feel stuck, even if they are still happening

**Comment by Pomax** [comment]
To be fair, though, 10+ megs of images, based on the images my phone takes, is like... 6 images. There's an odd mismatch here between what is reasonable from a user perspective (surely I can add more than 5 images to my site) and from a dev perspective (10 megs for a few images? come on).

It feels like what we really need is a way to say "hey you added an image but it's *super big* for web purposes. [scale it down], or [cancel adding this file]?" so that users are confronted with the fact that there are things to consider when making web content, without preventing them from doing what they want: downscaling an image in JS is trivially easy, so we can convert that that 6000x4000 lossless image to a 2000x1333 JPG and if people care enough to go "omg jpeg! I need my pixels to be real" they probably already know how to downsize images on their own computer.

Other than images, what else would be candidates for downsizing? PDF files are kind of an all-or-nothing affair... can browsers convert audio and video into smaller files the same way they can trivially deal with images?

**Comment by flukeout** [comment]
Updated the list of options to reflect your suggestions, which I like. As far as file types & sizes, we've got all the info on our database. We should check the distribution of our file sizes, and see what types of large files people are trying to upload. So..

**To-Do**
* Get some numbers on...
  * How many large projects do we have? And what defines large 3MB+?
  * How many and what kinds of large files do we have in our DB
* Figure out some approaches to image resizing
  * Can we do it client size after upload?

**Comment by gideonthomas** [comment]
AWS can handle sizes without an issue. The Problem is it will always be reliant on the client's connection. I think the best thing we can do here is to just not block the editor on project load. We might need to figure out a way to basically allow users to play around with the index.html file and maybe block the file tree with a loading spinner or something. We def should enforce some limits though and we probably want different limits for different file types (since we're not a hosting service - we can add UI to indicate so and point them at hosting sties)

**Comment by dsych** [comment]
How about not loading all of the large files when a project loads? We can have some kind of mechanism that only ships file that are below a certain threshold, and other files could be shipped on demand. 
E.g. instead of showing images in a preview window, we can only show a proxy, placeholder. There will be some kind of a small window or icon on the image in the file tree or directly on top of the preview pane that will allow user to request the image. Moreover, for projects that actually need all images straight away, there will be an option for mass download in configurations.

About how to indicate if a file is too large, we can just highlight it in yellow (if it is big, but allowed) and red (if it is too big). When you click on the file, in the editor pane at the top, there would be one liner saying something like: "This file is too big. Consider resizing or re-hosting it."- with options to resize and link to suggested hosts respectively.

**Comment by flukeout** [comment]
That's a great evolution of @gideonthomas' thoughts @dsych. We can download files one by one in a project, but have the ones that are loaded already be editable. Let's get @gideonthomas' thoughts on some of these ideas from a technical perspective. If they are feasible, I can do some design work. OR, they can drive some of the technical decisions as we rewrite how we store files.

**Comment by humphd** [comment]
A few thoughts:

* We can resize images in a worker using something like Pica (see [demo](https://nodeca.github.io/pica/demo/), [code](https://github.com/nodeca/pica)).  When a user drops a file into the filetree, we can initially accept it, and in the background start reducing it.  When it's done, we can show a toast or something that says, "File x.png was too large for fast download, we've reduced it for you!" and just overwrite the file.  This way, they can keep using it without interruption.  Question for @flukeout: what size would we reduced too?
* For non-image, large, non-web file types (pdf, word doc, movies, etc) we can either offer to exclude them when importing, or have some kind of interaction via a modal that lets the user choose whether to include or exclude (sometimes you might really want it).
* We can do a similar step at the publish step: tell the user that files X, Y, and Z are really large, and will make the project slow to open/remix, and slow to load, and let them exclude from publish (e.g., they could still be in their local filesystem).  I think showing the user some info about how big their project is, and playing on the "This will be slow to load on the web, here's why..." angle might help.
* We could do something similar at remix, and exclude large non-necessary files (anything not HTML, CSS, JS, JSON, Image, ...) so what you open when remixing can be different than what you publish.
* If we switch to loading projects file-at-a-time vs. tarball (I have a [PR for this](https://github.com/mozilla/thimble.mozilla.org/pull/2262) already), we could open the project once the "text" files (html, css, js) are loaded, but before binary files (images): using the project metadata we'd write small placeholder versions to disk until the full ones arrive.  We'd have to "serve" the placeholders for the binary file types, which we can do via Blob URLs or Service Worker, and just refresh the preview when everything finishes loading fully.  Probably we could show a toast UI too, "Your project is still loading..." and "Your project is fully loaded, have fun!"

In short, there's a lot we can do here, and we should split this up into separate bugs and do a few things.

**Comment by flukeout** [comment]
To follow up on the file counts, here's what we are looking at in the working files db

```
[
  {
    "reverse" : "html",
    "count" : 1291098
  },
  {
    "reverse" : "css",
    "count" : 645465
  },
  {
    "reverse" : "jpg",
    "count" : 311853
  },
  {
    "reverse" : "png",
    "count" : 209245
  },
  {
    "reverse" : "svg",
    "count" : 125835
  },
  {
    "reverse" : "js",
    "count" : 123153
  },
  {
    "reverse" : "gif",
    "count" : 29421
  },
  {
    "reverse" : "JPG",
    "count" : 19306
  },
  {
    "reverse" : "jpeg",
    "count" : 15497
  },
  {
    "reverse" : "mp3",
    "count" : 8203
  },
  {
    "reverse" : "PNG",
    "count" : 5700
  },
  {
    "reverse" : "ttf",
    "count" : 4598
  },
  {
    "reverse" : "scss",
    "count" : 3890
  },
  {
    "reverse" : "",
    "count" : 3861
  },
  {
    "reverse" : "wav",
    "count" : 3455
  },
  {
    "reverse" : "woff",
    "count" : 3209
  },
  {
    "reverse" : "eot",
    "count" : 2830
  },
  {
    "reverse" : "txt",
    "count" : 2564
  },
  {
    "reverse" : "ogg",
    "count" : 2112
  },
  {
    "reverse" : "pdf",
    "count" : 1978
  },
  {
    "reverse" : "htm",
    "count" : 1867
  },
  {
    "reverse" : "mp4",
    "count" : 1547
  },
  {
    "reverse" : "otf",
    "count" : 1317
  },
  {
    "reverse" : "less",
    "count" : 1312
  },
  {
    "reverse" : "json",
    "count" : 1256
  },
  {
    "reverse" : "php",
    "count" : 1144
  },
  {
    "reverse" : "md",
    "count" : 1122
  }
]
```

**Comment by flukeout** [comment]
Here are some rough stats on file size distribution, broken down into 250KB groups...

![image](https://user-images.githubusercontent.com/25212/26987804-c04f41fe-4d01-11e7-9949-ca59e216b7db.png)

**Comment by humphd** [comment]
I have an experimental PR up in Brackets to auto-resize large images before we write them to the filesystem https://github.com/mozilla/brackets/pull/794.

**Comment by humphd** [comment]
@flukeout this is really neat to see, thanks for putting it in here.  I summarized and graphed it:

```
Category Number	Percent
--------------------------
HTML	1292965	45.89%
CSS	649355	23.05%
JS	124409	4.42%
Images	716857	25.44%
Audio	13770	0.49%
Video	1547	0.05%
Fonts	11954	0.42%
Text	3776	0.13%
Other	3,122	0.11%
```

![image](https://user-images.githubusercontent.com/427398/27007527-57c5989e-4e24-11e7-877c-e8a78ce4476a.png)

I'm excited by the Service Worker and Cache Storage PR in Brackets to increase our JS numbers.

**Comment by flukeout** [comment]
Closing—We've basically achieved this via blocking additional file uploads when a specifc project size is reached.
