### ISSUE TITLE
Figure out the best UI for the language picker

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.mozilla.org#1335]
Since we'll be localizing Thimble, we'll need to add a mechanism for letting users...
- know what language Thimble is currently using
- change, and save, their language preference
- know that they can contribute to the localization effort

In digging through my old design files, I found the following design for a top-level language preference, designed to sit alongside other items in the top green bar...

![image](https://cloud.githubusercontent.com/assets/25212/12367938/5ce02b68-bb9b-11e5-8b2d-d80e251f7ae1.png)

In our previous discussions, we thought of moving this to something like the profile page (on the login server), so we will need to revisit those assumptions to see if they're still relevant.

**Comment by flukeout** [comment]
**To do**
* Look into pontoon
* Observe someone's localization workflow
* Look into transifex
* Chat with Ali

**Comment by flukeout** [comment]
The "universal language icon" - neat - http://www.languageicon.org/

**Comment by flukeout** [comment]
**Some guidelines**
* If a user shows up, and we think we know what language they want - we automatically switch it
* The language options are in the native language of each language - ie. English is always "English"
* At any time, a user can switch their language preference from the available options, and we remember it
  * If they're signed in, we can store it in their account preferences
  * If not, as a cookie

**Comment by simonwex** [comment]
@alicoding could you fill in some details here from what we've done in the past and what we need to do now without having the pref in id.wm.o

**Comment by alicoding** [comment]
Mostly it's what @flukeout has written in this issue, but I'm just going to suggest the best option based on my research and what we've done in the past here.

If the user enter the site without locale in the URL we'll then check their browser preferences. Based on the return array of `navigator.languages` (['en', 'fr', 'th'] this will return in the order of what has been set in the browser preferences) we will try to match the language we support and if we do we will then inject the locale in the URL if not will default to the default language.

If the locale was entered in the URL and we support that then will just display that language, but if it was an unknown language then will redirect to the first language we support from their browser lang otherwise default language that we support.

For the language dropdown since we will not have account preferences in id.wb.org I believe the best option here is to use what I have suggested above here which we don't need to rely on storing the data anywhere.

**Comment by flukeout** [comment]
Here is how the language will be indicated and changed in the UI.

![image](https://cloud.githubusercontent.com/assets/25212/12800789/886d95d6-ca8c-11e5-8a45-276333bfec20.png)

**Comment by gideonthomas** [comment]
@flukeout question: How are the langs alphabetized? Are they based on their English names? Like Deutsch goes before English (US)? (Even though we would call it German)

**Comment by alicoding** [comment]
We can do two things here.

1. Based on the metric (most visited language)
2. Alphabetical order

**Comment by flukeout** [comment]
@gideonthomas @alicoding I vote for "Alphabetical sorted by their 'native' names" - that seems more reliable and constant as opposed to a potentially changing order over time as different languages get more / less popular among our userbase.

**Comment by flukeout** [comment]
**Questions**
* Figure out how to alphabetize names that don't use the roman alphabet

**Comment by flukeout** [comment]
**An option for alphabetizing**
Wikipedia sorts by the latinized name of the language while displaying it in the 'native language'. So Japanese is displayed with Kanji, but sorted as "nihon go".

![image](https://cloud.githubusercontent.com/assets/25212/12826766/7e582b74-cb31-11e5-814a-2b2ecd228e82.png)

**Comment by simonwex** [comment]
It might make sense to have the list separated where the locales in the user's `Accept-Language` header are displayed on top regardless of sorting.

**Comment by flukeout** [comment]
Yeah, it makes sense to highlight a choice that we have an inkling might be useful. Does the ``Accept-Language`` header include only one language, or multiples?

**Comment by gideonthomas** [comment]
@flukeout it usually is an array of one or more locale codes.
