### ISSUE TITLE
Figure out if we need to localize the name of `tutorial.html`

### ISSUE THREAD

**Issue by simonwex** [mozilla/thimble.mozilla.org#1357]
This includes the tutorial file name...
https://github.com/humphd/brackets/blob/bramble/src/bramble/client/main.js#L40

... and error messages in the same file.

**Comment by simonwex** [comment]
This should be pretty simple, if it ends up being complicated, we can punt.

**Comment by humphd** [comment]
I wonder if this is necessary at all.  Web servers don't localize "index.html", despite the content being in one language or another.  Also, error messages from the client api are only meant for developers.

I'd WONTIFX this. @gideonthomas, what do you want to do here?

**Comment by gideonthomas** [comment]
Yeah we won't localize the error messages. The only thing that *might* need to be localized is `tutorial.html`. We localize it in the preview pane's navbar so I think it might make sense to also localize the name of the file (since "tutorial.html" is our own creation, so we can change how it works). cc @alicoding for thoughts on this.

Either way, I wouldn't say that this is high priority.

**Comment by alicoding** [comment]
I would agree with @humphd in regard to not localize `index.html` since that will make it complicated/break the loading of `index` page etc. Though file name in general I don't think would matter if we leave it as is and instead focus on the title + content instead.

**Comment by gideonthomas** [comment]
@alicoding yeah we're not going to localize `index.html` since it will break everything else. This is more about the `tutorial.html` page.

**Comment by gideonthomas** [comment]
I think we're gonna say no to this for now and we can re-open this later on.
