### ISSUE TITLE
Localize "Upload zip files"

### ISSUE THREAD

**Issue by simonwex** [mozilla/thimble.mozilla.org#1359]
https://github.com/humphd/brackets/tree/bramble/src/extensions/default/UploadFiles

**Comment by simonwex** [comment]
Hey @gideonthomas, could you add some details here? -- I believe this is the dialog that lets the user upload files, not sure what "DnD" refers to.

**Comment by humphd** [comment]
The DnD (Drag and Drop) stuff is shared utility code that the Upload Files dialog uses.  It includes a bunch of user-facing error and success messages in modal dialogs.  For example:

* https://github.com/humphd/brackets/blob/bramble/src/utils/DragAndDrop.js#L300-L303
* https://github.com/humphd/brackets/blob/bramble/src/utils/DragAndDrop.js#L313
etc

We should move these to the main Brackets strings file instead of hard coding them all.
