### ISSUE TITLE
Use localized MDNDocs

### ISSUE THREAD

**Issue by simonwex** [mozilla/thimble.mozilla.org#1364]
This is both the viewer UI and fetching the localized docs from MDN.

https://github.com/humphd/brackets/blob/bramble/src/extensions/extra/MDNDocs/InlineDocsViewer.js
https://github.com/humphd/brackets/tree/bramble/src/extensions/extra/MDNDocs

**Comment by simonwex** [comment]
This'd be good to include in the diagram (#1355)

**Comment by gideonthomas** [comment]
@simonwex the MDNDocs api is not great since it's missing some important data we need in it's response structure (it's easy to get docs for HTML elements and CSS rules but any data about HTML attributes seems to be missing with no easy way to acquire it). This is the api that I tried using: https://developer.mozilla.org/en-US/docs/MDN/Contribute/Tools/Document_parameters#metadata

I'm going to try using DevDocs instead which really uses MDNDocs for HTML and CSS.

**Comment by gideonthomas** [comment]
This is probably not going to happen anytime soon. We'll stick to using WebPlatformDocs for now

**Comment by gideonthomas** [comment]
We will eventually pick up MDNDocs since WebPlatformDocs is still in its alpha release and it is localized only in English, Deutsch, español, français, 日本語, 한국어, Nederlands, português do Brasil, Türkçe, 中文 , 中文（简体）‎ , 中文（繁體）

**Comment by gideonthomas** [comment]
Ok, so I think I have to retract my earlier statement. I will stick to MDNDocs and create a scrapper to extract the content and commit it to the src tree because it seems like WebPlatformDocs is even harder to get content out of since it is a wiki and the mediawiki interface is pretty complicated (and not too well documented for our purposes). We should run the script every once in a while to re-fetch content.

**Comment by gideonthomas** [comment]
Doesn't look like we're going to do this anytime soon. Closing until we formulate a plan for whether this is required and how we're going to approach this.
