### ISSUE TITLE
Stylus support?

### ISSUE THREAD

**Issue by geordieF** [mozilla/thimble.mozilla.org#1385]

**Comment by gideonthomas** [comment]
Hi @geordieF, thanks for the suggestion! What is your use case that requires support for stylus/touch?

**Comment by geordieF** [comment]
I mean the preprocessor

**Comment by humphd** [comment]
It's not something we plan to add, no.  We've got basic support for LESS, since Brackets already has LESS baked into the code itself; but even than is less than perfect, since we only operate on the contents of a single file at a time vs. doing proper imports.

I'm going to close this, but if it's something you wanted to do, I could give you advice on how I'd do it, and we can re-open or do a PR.
