### ISSUE TITLE
[DEV] - When editing HTML, the changes aren't reflected until the local server is restarted. 

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.mozilla.org#1397]
I'm updating `userbar.html` and my changes are only reflected locally if I restart the server. As far as I remember, this is new behaviour - the changes used to be visible when refreshing the editor, without needing a restart.

**Comment by gideonthomas** [comment]
Seems like nunjucks is caching the templated html files for some reason

**Comment by humphd** [comment]
I think that when we're in development mode, we should be passing extra options to the nunjucks environment here:

https://github.com/mozilla/thimble.mozilla.org/blob/fa3dde088dc016a562520e62a9df1f5558ba8f70/server/templatize.js#L6

See discussion here:

https://github.com/mozilla/nunjucks/issues/479

And API docs here:

https://mozilla.github.io/nunjucks/api.html#configure

**Comment by flukeout** [comment]
I'll try out the suggestions in the discussion, I think it's an important fix as it makes contributing super annoying.

**Comment by flukeout** [comment]
Or @humphd - if you have anyone in particular looking for an issue right now, this would be a great one.

**Comment by humphd** [comment]
No one yet, but people will need new bugs to work on next week, so I'll make sure someone grabs it.

**Comment by JohnEJames** [comment]
@humphd  I would be interested in trying to fix this bug.  But I really don't know where to start for this.

**Comment by humphd** [comment]
@JohnEJames great, this bug is causing people headaches, so it would be great to fix.  See my comment above: https://github.com/mozilla/thimble.mozilla.org/issues/1397#issuecomment-277725957.

Basically, you need to modify this https://github.com/mozilla/thimble.mozilla.org/blob/fa3dde088dc016a562520e62a9df1f5558ba8f70/server/templatize.js#L6 to do what is described here: https://github.com/mozilla/nunjucks/issues/479#issuecomment-227789598 (note the `{ noCache: true, watch: true }` bits.

If you do it right, changing files in https://github.com/mozilla/thimble.mozilla.org/tree/fa3dde088dc016a562520e62a9df1f5558ba8f70/views will cause `nunjucks` to recreate the templates again (i.e., not just the first time they are needed).

Does that make sense?

**Comment by JohnEJames** [comment]
Yeah, that makes sense, is this issue big enough that I dont need to find another bug? or would you like me to find another?

**Comment by humphd** [comment]
It's probably not huge, but start on it and see how you do.  If you finish quickly, grab another bug.

**Comment by JohnEJames** [comment]
Okay, thanks! I'll start working on this issue!

**Comment by JohnEJames** [comment]
Hey so, I started spending more time towards this bug and made some changes that @humphd  suggested
https://github.com/mozilla/thimble.mozilla.org/blob/fa3dde088dc016a562520e62a9df1f5558ba8f70/server/templatize.js#L6 

now is this: 
`  let engine = new Nunjucks.Environment(paths.map(path => new Nunjucks.FileSystemLoader(path), { noCache: true, watch: true }), { autoescape: false });`

After testing my function, I first thought it was working but after further testing I noticed some weird things.

**Example 1**
I Edit the html, then instantly go to my profile to reload it 
![example1](https://cloud.githubusercontent.com/assets/10540058/23327130/d1714c04-fad4-11e6-8379-273a52762a45.gif)

**Example 2**
I edit the html, and then let it stand for a few seconds then reload it
![example2](https://cloud.githubusercontent.com/assets/10540058/23327131/d500b364-fad4-11e6-9543-01932721bcd9.gif)

**Comment by humphd** [comment]
As I said in class, you're now one of the most knowledgeable people on this issue in our community, since you've been digging into it.  As such, I don't have much advice, except to say that if it were me, I'd look at what other people do in their code:

https://github.com/search?l=JavaScript&q=nunjucks+nocache+watch&type=Code&utf8=%E2%9C%93

This search has hundreds of examples of other projects doing this, I'd study what they do and experiment.

Also, which HTML are you editing and testing when you see if this works?  This bug is about fixing our server's HTML templates, not the HTML in Brackets.  For example, these files:

https://github.com/mozilla/thimble.mozilla.org/tree/master/views/editor

**Comment by JohnEJames** [comment]
Ah I see, I very much misread the Issue. I'll start to test it with the HTMl templates. Sorry about that

**Comment by gideonthomas** [comment]
@JohnEJames, if you're curious, the two issues that you mention above can probably be fixed once we implement https://github.com/mozilla/brackets/issues/607 since we can add an "Are you sure, you have unsaved work" confirm dialog based on the events implemented in that issue and avoid this problem.

But yeah, this issue is about the HTML templates in `server/views` :)

**Comment by JohnEJames** [comment]
I've been having some luck with this code:

`let engine = new Nunjucks.Environment(paths.map(path => new Nunjucks.FileSystemLoader(path)), {noCache: true, watch: true, autoescape: true });` 

I dont have to restart the server to see my changes, but I have to go to back to the homepage

**Comment by JohnEJames** [comment]
So I've been reading the Nunjucks api, and been trying to do the syntax properly. But so far I've had no luck.
This is the code that I've tried to get working:
` let engine = new Nunjucks.Environment(paths.map(path => new Nunjucks.FileSystemLoader(path)), {watch: true, noCache, true, autoescape: true });`

Reading the Nunjucks API:
watch (default: false) reload templates when they are changed (server-side). To use watch, make sure optional dependency chokidar is installed.
noCache (default: false) never use a cache and recompile templates each time (server-side)

Which is suppose to fix this bug, but it still won't work for me. any thoughts @humphd or @gideonthomas ?

**Comment by JohnEJames** [comment]
It works, but I have to keep spamming Refresh until the page loads

**Comment by flukeout** [comment]
Fixed by @JohnEJames in https://github.com/mozilla/thimble.mozilla.org/pull/1808
