### ISSUE TITLE
Thimble is not functional when 3rd party cookies are disabled, or tracking protection enabled

### ISSUE THREAD

**Issue by autonome** [mozilla/thimble.mozilla.org#1437]
Enabling tracking protection in Firefox makes Thimble non-functional.

STR:

1. Create a project in new Thimble

Expected: Thimble project editor loads

Actual: The screen is stuck on "loading project" forever

This is very important to fix considering MoFo and MoCo are campaigning hard to convince people worldwide to do this.

Consolidating Thimble's services under a single origin should resolve this. We should work with ops to figure out a path to making this happen.

**Comment by humphd** [comment]
What does "Enable tracking protection" mean exactly?

Consolidating Thimble to a single origin won't work if we want to allow arbitrary code execution by the user.  We split this in two so that we could safely allow users to write any code without having it execute in the context of their authenticated session (i.e., editor iframe separate from hosting app).

cc @simonwex, @jbuck

**Comment by humphd** [comment]
@gideonthomas, @Pomax didn't we hit this before with a user and never figure out what was actually going wrong?  One thing I know we do in Thimble is use `localStorage`, which I think shares permissions with cookies in FF.

**Comment by cadecairos** [comment]
I just tested with Firefox, Tracking Protection doesn't affect Thimble. Disallowing third party cookies however, causes a "SecurityError" in my console

**Comment by gideonthomas** [comment]
@humphd yeah it's coz we use localstorage

**Comment by jbuck** [comment]
The current architecture of Thimble has us running a shell on thimble.mozilla.org that handles user authentication and loads the actual Thimble editor via an iframe on mozillathimblelivepreview.net . The reason we have two origins here is that Thimble can run arbitrary Javascript and running it on a completely separate domain is the only way we can do that safely. We can't do something like run the editor on a shared subdomain because you can launch cross-subdomain attacks if you're able to run Javascript.

I realize this poses problems with 3rd party cookies and/or tracking protection, but given the constraints I'm not sure how to change this architecture.

**Comment by autonome** [comment]
One of the sec team folks suggested using postMessage to ship state to/from the iframe instead of using localstorage, removing the need for cookies. C'est possible?

**Comment by gideonthomas** [comment]
@autonome yeah that should be possible. Another option that @jbuck suggested is to check if `localstorage` is accessible or not and if not, continue to load thimble but throw up a warning saying "so and so features are unavailable because localstorage is disabled".
One thing to consider is that one of the main reasons we use `localstorage` is because it is synchronous. Using `postmessage

@humphd which one do you think would be easier to implement?

**Comment by humphd** [comment]
We use `localStorage` in a very limited way, namely, to cache any unsynced filesystem paths when the user closes the app before all have been processed, see https://github.com/mozilla/thimble.mozilla.org/blob/1fbdaae7a974746fb99c18f28e0b88fdd9e648b9/public/editor/scripts/path-cache.js#L42-L46.  There are other ways we could do this, and in the worst case, use a memory backed solution for the case that `localStorage` isn't accessible.

**Comment by humphd** [comment]
I went back to look at why we do what we do, and the real issue is that we lack `IndexedDB` in private browsing mode with Firefox, which I've discussed here https://bugzilla.mozilla.org/show_bug.cgi?id=781982#c27.  I'm not sure what we should do here.  I could use a memory-backed filesystem instead of `IndexedDB`; but I think we decided against this because you'd lose your work on refresh, couldn't publish/save to the server, etc.

I'm not sure what the right answer is here.  I'd love to see Firefox do what Chrome does, and give users a temporary db even when in private browsing mode.

**Comment by autonome** [comment]
The external domain is the unsafe one, where preview is executed, and where
the problem happens... is that right? Is the work not saved/persisted in
the editor (the safe domain)?

My understanding from your previous comment was that the problem is in the
previewer page (unsafe domain with no storage when 3rd party cookies are
disabled). Is that wrong?

**Comment by humphd** [comment]
There are 2 domains, let's call them thimble (host app) and brackets (iframed).  Both windows need access to the same filesystem, which we've built on top of IndexedDB.  We run that db in thimble, and proxy it using MessageChannel in brackets.  So the db is running on the same domain as the app (i.e., "third-party" isn't the issue).  Firefox, unlike Chrome, won't let you run a db in a private tab, which sucks.  In addition, we us localStorage on the thimble domain (again, same origin) to cache paths that need to get synced to the server in the future.

I've got a memory backed version of our filesystem, which I could use here when IndexedDB is not working (we already use WebSQL if it's there and IDB isn't).  But I'm unclear on how compelling this is going to be, since you'll lose work as soon as you navigate away.

**Comment by autonome** [comment]
Thanks for clarifying, David! where does the "private tab" enter the
picture? And why does this only occur if I have 3rd party cookies turned
off?

I disagree that memory-backed will not be compelling. I'm constantly
saving/editing/previewing when I use Thimble. A workflow where the user
edits something in a Thimble project and then quickly navigates elsewhere
in the same tab is possibly an edge-case.

Either way, it's far preferable to locking out users.

**Comment by gideonthomas** [comment]
@humphd I don't think private browsing matters here since you cannot load thimble in that scenario. We show an error while loading thimble in that case.

As for caching paths, we only do that on navigation away from the page right? We can add a fallback for unsupported `localStorage`. If `localStorage` is unsupported, we **fallback** to the `mtime` for each file. Then, on loading Thimble, when we're pulling down all the files, we check to see which `mtime` is later (the one on the server or the one on the client) and write or push up the file accordingly. This would also mean that we would need to change `publish.webmaker.org` to optionally accept/return `mtime` in the payload for file requests and configure thimble to send the `mtime` in its requests. 

This solution will work but will take a considerable amount of effort! I still favor @jbuck's solution to show a warning instead and leave it at that - I feel like it's the easiest solution to implement and more or less serves our purpose.

cc @Pomax for thoughts

**Comment by Pomax** [comment]
I'm not sure what the right solution is here - "third party cookies" are not fine grained enough for my taste because just because it's not "the same site" that doesn't mean it's "third party" (in this case for instance mozilla owns all the domains involved, and I trust Mozilla, so I want their sites to read/write cookies). Rather than making the browser whole-sale block them, I use extensions to manage who gets cookie access (and thus localStorage) and who doesn't, so my inclination is to go with @jbuck's solution - throw a warning when cookies are disabled. And maybe treat it as a teaching moment to explain why cookies and localStorage are linked. That's not professional advice though, more personal opinion.

**Comment by gideonthomas** [comment]
Ok I've just realized that we might be overthinking this! The "Block third-party cookies" option enforces the same-origin policy even for `localStorage` (this has been pointed out above). 

I spun up a dyno on heroku and pushed Brackets there so that I could test with different domains to investigate where we're setting data in `localStorage` from Brackets. Apparently Brackets' core is what uses `localStorage` directly to set prefs (none of which we care about). So, I removed/replaced code and now it seems to work.

@humphd would you be able to review the PR: https://github.com/mozilla/brackets/pull/545

**Comment by humphd** [comment]
Smart, smart, smart!  I've left comments in that PR.

**Comment by Pomax** [comment]
yeah, good deep-dive!

**Comment by autonome** [comment]
Thanks for the fix! When will it be deployed?

**Comment by gideonthomas** [comment]
@autonome, I'm planning to deploy on Monday

**Comment by gideonthomas** [comment]
@autonome it should be working now

**Comment by autonome** [comment]
Thanks Gideon! I tested in Firefox nightly with 3rd party cookies set to
"only visited" and I'm still getting stuck "Loading Project" when starting
a new project.

**Comment by gideonthomas** [comment]
hmm, weird. I'm not able to reproduce this with the same setting (Firefox Dev edition though).
Can you try clearing your cache and seeing if this works?

**Comment by fabrixxm** [comment]
I still have the same problem.

With 3rd part cookies set to "only visited", i get this in console

```
08:48:19.920 Content Security Policy: La direttiva “frame-src” è deprecata. Al suo posto utilizzare la direttiva “child-src”.  (sconosciuto)
08:48:23.110 La pagina è stata ricaricata in quanto la dichiarazione della codifica caratteri del documento HTML non è stata trovata durante la scansione preliminare dei primi 1024 byte del file. Spostare la dichiarazione della codifica nei primi 1024 byte del file.  index.html:27
08:48:26.779 Unable to use localStorage in Brackets with:  DOMException [SecurityError: "The operation is insecure."
code: 18
nsresult: 0x80530012
location: https://mozillathimblelivepreview.net/bramble/production/dist/main.js:1]  main.js:1:2520
08:48:33.611 [Bramble] unable to initialize URL cache DOMException [SecurityError: "The operation is insecure."
code: 18
nsresult: 0x80530012
location: https://mozillathimblelivepreview.net/bramble/production/dist/main.js:17]  main.js:2:30819
```
