### ISSUE TITLE
Add Albanian (SQ) language

### ISSUE THREAD

**Issue by elioqoshi** [mozilla/thimble.mozilla.org#1453]
Hey,

Not sure how to get this started, never worked on Pontoon, but the Albanian community would love to localize Thimble in Albanian. How can we proceed?

**Comment by Pomax** [comment]
That's great to hear! @gideonthomas should be able to help get you started.

**Comment by gideonthomas** [comment]
Hi @elioqoshi! Thanks for volunteering!

Thimble uses Mozilla's Pontoon to localize content. It is a great tool that allows you to click and change most strings on the different elements in a Thimble page directly. We highly recommend reading [https://developer.mozilla.org/en-US/docs/Mozilla/Localization/Localizing_with_Pontoon](https://developer.mozilla.org/en-US/docs/Mozilla/Localization/Localizing_with_Pontoon) to acquaint yourself with Pontoon's interface and navigation. It also tells you how to translate strings using the interface.

You will need a Persona account to localize strings on Pontoon. Here's how you sign up for one:
* Go to https://login.persona.org
* Click on the "Sign In" button on the top right corner
* It will ask you for an email address and for you to create a password. Once that is done, you will now be able to login to Persona with these credentials.

Go to [https://pontoon.mozilla.org](https://pontoon.mozilla.org). Select your language from the list on the top-left corner. Select "Thimble" from the adjacent option and click "Go". Since there are two different sets of strings, you can toggle which one you want to edit from the option adjacent to "Go". Your options are "Homepage" and "Editor". From there, you should be able to localize strings by clicking on the UI elements that have a dashed border when you hove over them. You can also localize some strings not visible on the page by clicking on the hamburger menu on the top-left corner.

Every translation you make will be a suggestion which will need approval from the Albanian community and that should happen pretty quickly. You will be able to see your changes on https://thimble.mozilla.org about a week after your translations come in, as that is when we release new translations.

If you have any questions, feel free to ask out here!

**Comment by elioqoshi** [comment]
Hey @gideonthomas Thanks! What does "Albanian Community" mean, when it's us who ask to do that? :) Who is approving the translations?

**Comment by gideonthomas** [comment]
Ah, sorry for not elaborating! Pontoon has "teams" that usually contribute translations to different Mozilla products. Hence, there is an Albanian team that will approve translations that you suggest.

**Comment by elioqoshi** [comment]
@gideonthomas How can I know who is on the team?

**Comment by gideonthomas** [comment]
@elioqoshi you can find the list of contributors here: https://pontoon.mozilla.org/sq/contributors

However, the best way to contact them is by subscribing to the dev-l10n list here: https://lists.mozilla.org/listinfo/dev-l10n and sending an email with your questions
OR
through IRC on the Mozilla network (irc.mozilla.org) in the #l10n channel

**Comment by elioqoshi** [comment]
Thanks @gideonthomas !
