### ISSUE TITLE
Discuss strategy for storing timestamps in the projects db.

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.mozilla.org#1454]
I'm picking up work again on the currently-broken [thimble stats dashboard](https://thimble-dashboard-staging.herokuapp.com/). As part of that effort, I'd like to aggregate the number of projects created per day for each of the last 30 days.

Since the last time I worked on it, the way we stored dates has changed. They're now stored as a timestamp with timezone in the GMT time zone...

![image](https://cloud.githubusercontent.com/assets/25212/13937546/ce3a30ea-ef82-11e5-9094-6bd35bfe009a.png)

It seems that we are always saving the time something was made relative to the server time only, and not the author's local time & timezone, correct? So if I and someone say, in China, make a project at the same time, they'll have a nearly identical timestamp in the db.

I'm guessing _most_ of the projects that get created are in North America, and way fewer get created on saturday and sunday. However, if we display a weekly trend against the GMT timezone, different days get the "weekend lull", which isn't representative.

To account for this we can either...
* Pick a 'base' timezone to record the times in that is more representative of where most of the projects are created
  * So, I can ask the database for the PST equivalent of all of those times and map that out
  * This works well if _most_ stuff is made close to that timezone, but the stats and daily groupings won't make as much sense if it isn't
* Record the timezone along with each timestamp depending on what timezone that user is in.

The second option seems pretty good for me - I think the _absolute_ time that something is made is less important than the clock time relative to the author, at least for stats.

Anyway, pardon the ramble - wanted to get my thoughts down as I work on this and to follow up on our conversation. What do you think @Pomax and @gideonthomas?

For now, I'm going to use the strategy of asking the DB for all of the times converted to PST, I think this will give a good approximation of the trends.

**Comment by Pomax** [comment]
I'm not sure I understand which problem we're trying to solve here - the server is the authority when it comes to reliable time stamping (just because a client computer says it's day X at time Y doesn't mean that information is correct in the slightest). The fact that a project made in Vancouver at 10am on a Monday and in Beijing at 1am on a Tuesday are the same UTC time is an obvious consequence of this, but the idea that timestamps tell us anything about locales seems trying to get the wrong information out of time stamps. If we want that level of differentiation, then we should store locale along with the timestamps, which as far as I know we now do (hurray!) so the question becomes "what are you trying to show?" We can do clustering based on locale now, which tells use the (rought) timezone correction that each cluster needs applied, and then we can visualize local-time-accurate results in the dashboard.

**Comment by gideonthomas** [comment]
@flukeout did we solve this issue over Mattermost? Can this be closed or is more discussion warranted?
