### ISSUE TITLE
Issues with Publishing

### ISSUE THREAD

**Issue by MooseRuler** [mozilla/thimble.mozilla.org#1475]
I'm using thimble as a text editor while im learning to code. I've made a simple website using html and css. I tried publishing it, after i tried clicking the link it would send me to a page claiming that "the content is unavailable". I thought it was a time sensitive issue so i waited 24 hours. Problem still occures, i've tried unpublishing my work and then republishing it, doesn't seem to work.

**Comment by Pomax** [comment]
hi @MooseRuler, can you provide us with the link that your project claims it has been published to?

**Comment by MooseRuler** [comment]
here you go https://thimbleprojects.org/mooseruler/59226 it should be a website about a game review.

**Comment by gideonthomas** [comment]
Hi @MooseRuler don't worry, your project has been published. Unfortunately, you are seeing a "Not Found" page because the project is missing an `index.html` page.  To confirm, try going to https://thimbleprojects.org/mooseruler/59226/rainbow.html to see that your files have been published.

When a url such as the one you have posted above (which does not specify a particular file) is requested by the browser, the server serving this project needs a default or "main" page to serve as a landing page. Normally, servers are configured to search for an `index.html` file and serve that as the "main" page. Since it couldn't find one in your project's main directory, it didn't know what to serve and instead showed a "Not Found" page.

The solution here would be to rename one of your html files (which you would like to be shown when you hit https://thimbleprojects.org/mooseruler/59226) to be `index.html`. Then everything should work as expected.

**Comment by MooseRuler** [comment]
@gideonthomas Thank you so much for your help! haha thats probably a noob mistake! xD

**Comment by gideonthomas** [comment]
Haha np! It's a pretty common mistake actually that even skilled devs make.

**Comment by angielopez** [comment]
I am having the same problem, except I have an existing "index.html" file already.

**Comment by humphd** [comment]
@angielopez what is the link to your published project?
