### ISSUE TITLE
I can't load one project

### ISSUE THREAD

**Issue by wpdlsksh** [mozilla/thimble.mozilla.org#1489]
https://thimble.mozilla.org/en-US/user/gus6590/214139

can't load only this project. 
loading does not end. 
Other projects, can be loaded.

**Comment by cadecairos** [comment]
I don't see any error in the application logs for this project, so it's being successfully downloaded to your computer, as far as I can tell.

What web browser are you using, ansd which version of it?

**Comment by wpdlsksh** [comment]
I use firefox 46.0.1 
I use the computer in labs of the university.
I think this computer is slow, i will try again in other places

**Comment by cadecairos** [comment]
Yeah it should totally work in that browser. Please let us know how it goes!

**Comment by wpdlsksh** [comment]
All computer can't load project. other lab's pc , my pc and mobile. if you can give me that project, plz send that project to my email wpdlsksh@gmail.com

**Comment by wpdlsksh** [comment]
give up. can't find a way.

**Comment by wpdlsksh** [comment]
I must submit this project next week. how can I get this project?

**Comment by cadecairos** [comment]
@gideonthomas can you please manually pull the project out of the database and attach it to this issue?

**Comment by gideonthomas** [comment]
yep will do

**Comment by gideonthomas** [comment]
Hi @wpdlsksh!

Firstly, I would like to apologize for the time delay in getting this done. We were having some issues trying to get your project! But I totally understand that this has been a major inconvenience for you and I do sincerely apologize.

It looks like your project has been published at: https://thimbleprojects.org/gus6590/73463/aa.html
(Note the /aa.html at the end. This is needed because you don't have an `index.html` file and so cannot see anything at https://thimbleprojects.org/gus6590/73463). Feel free to remix that project to get it back.

However, if you prefer to just extract the tarball, here it is: https://drive.google.com/file/d/0BwCd-6qteGa8VjRUWlljRG5MVVE/view?usp=sharing
(let me know if you have any issues accessing it)!

Let us know how the process goes and we're happy to help if you encounter any further issues (promptly this time :) )

**Comment by wpdlsksh** [comment]
Thank you. You've been a great help

**Comment by wpdlsksh** [comment]
Thank you. You've been a great help
