### ISSUE TITLE
logging out in the editor view moves people to the landing page

### ISSUE THREAD

**Issue by Pomax** [mozilla/thimble.mozilla.org#1494]
The expected behaviour would be to be redirected to the page I was already editing instead of being booted out of Thimble and to the thimble landing page instead.

**Comment by gideonthomas** [comment]
I don't think that this is really expected behavior. I believe that we had discussed this before in terms of seamless transitions between the authenticated and unauthenticated states so we implemented a seamless transition one way i.e. when you authenticate and you have a project open, we save that project to your account. 
If I remember correctly, there were two reasons why we decided not to do the other way too. It wasn't a real use case - users logging out and then wanting to continue to work on their project and also since the complexity (both technical and UX) associated with keeping that state when logged out (informing the user that all changes will not persist to their account for e.g.) was too much.
