### ISSUE TITLE
Thimble project gallery protoype

### ISSUE THREAD

**Issue by khanh2003** [mozilla/thimble.mozilla.org#1505]

**Comment by gideonthomas** [comment]
Hi @khanh2003! Can you elaborate on what you mean by showing "all of the user's projects"? Doesn't it already do that? You should be able to see all of the projects you made in the projects list.

Also, we're still working on our starter projects and figuring out the right content that will fit in with our curriculum and target audience. But you bring up a good discussion point about possibly having starter projects revolve around the concept of levels of difficulty or levels of advancement -> cc'ing @chadsansing and @flukeout to note this as a possible idea

**Comment by flukeout** [comment]
To follow up, you can access your projects via the dropdown menu when you're signed in to your account. Let us know if you have any problems with this.

![new-project](https://cloud.githubusercontent.com/assets/25212/16662646/4e251d0c-442d-11e6-9330-
a5428b5e5cd2.gif)

**Comment by khanh2003** [comment]
What I mean is this!
![screen shot 2016-07-08 at 10 42 51 am](https://cloud.githubusercontent.com/assets/17680976/16676799/cdd9777a-44f8-11e6-86c7-5c3f309e2219.png)

**Comment by khanh2003** [comment]
So, everyone can get inspirations for their projects, and learn new things.
And a search bar.

**Comment by gideonthomas** [comment]
Ah I see, we're still discussing on what the best way would be to discover other user's projects and this is part of our "Thimble in a classroom" initiative. I'll find the relevant bugs and link them here.

**Comment by khanh2003** [comment]
#1532

**Comment by khanh2003** [comment]
Anyone listening?!
-

**Comment by ryanwarsaw** [comment]
Hi there @khanh2003. Sometimes these things can take quite a while, while I'm not on the Thimble team and can't provide insight on the status of this (perhaps @gideonthomas could speak to this?)  I would encourage you to continue to share your feedback and ideas! They are valued much and rest assured that they are all read and considered!

**Comment by jgmac1106** [comment]
You mean instead of a list display having a thumbnail image of the project
appear?

A few questions
- @khan2003 My guess is there will be a lot of brainstorming around Thimble
and Thimble classroom at Mozfest. I also believe much of the design team is
knee deep in getting ready for one of MoFo's biggest events of the year.
- In your suggested idea Would a user have to select the thumbnail image
(they won't)? would Thimble select an image from the project? Would Thimble
auto generate a screenshot as a png for display?
- There was talk of adding a Twitter/Facebook cards to Thimble projects
shared on multimedia. Should this be teachable moment so people learn how
to add their own cards and the Thimble social media assets would be the
default if users do not change? Would adding this complex code be too
confusing for new users who maybe learning wat a <p> tag does?

I agree with @khan2003 you the My Projects page needs some serious love. I
have so many projects now I can spend too much time looking for one I want.
Plus you can't right click to open in a new tab so your navigation path has
to go project>my projects>a project>my project>open another project.

Rest assured the team behind Thimble has been tracking these issues for a
long time and when they get the capacity to work on Thimble Classroom and
the My Projects I am sure they will take great ideas like yours into
consideration.

**Comment by gideonthomas** [comment]
Hi @khanh2003 I apologize for the inactivity on this thread. At present, we aren't actively working on new features for Thimble based on https://github.com/mozilla/thimble.mozilla.org/wiki/Roadmap#the-thimble-development-roadmap-is-currently-paused. 

I think it is important to mention though that feedback (such as yours) is still very much appreciated and encouraged so that we can refer back to it once we revisit the roadmap and decide on how we will continue to improve and enrich Thimble (I believe that this will be happening very soon definitely with an update by the end of the year). We are also gathering data on applying Thimble in the classroom at MozFest this year.

Until then, we are currently in the "supporting" role for Thimble and working on fixing some serious bugs that have popped up related to data loss as well as total inaccessibility of Thimble (such as https://github.com/mozilla/thimble.mozilla.org/issues/1556 and https://github.com/mozilla/thimble.mozilla.org/issues/1550).

We are however vigilant to code contributions (along with feedback) and are more than happy to review and accept them into our code base.

(also, thank you very much @ryanwarsaw and @jgmac1106 for replying as well as providing feedback and maintaining the conversation)

**Comment by khanh2003** [comment]
@jgmac1106 
1/ no. i really hate that. but i would like a quick search bar every time i visit my projects
2/ an iframe displaying that project (using sandbox attribute you can mute, disable annoying modals) or if you like, you can take the picture of project server-side. a user have to select the thumbnail image>no, they won't. and it'll make the project gallery ugly
I mean a project gallery for all user in this issue (although the my projects page is bad too(
3/ a quick comment thread but please not social media comment plugin. they are usually blocked in some countries.
@gideonthomas anyway, i afraid that this project will die soon. the `development path currently paused` is a signal of a project's death. **please, don't give up, dev team**. this is great and everyone loves it. hosting static sites doesn't cost much money. you are having some serious issue that can bring thimble down, but let's try more.

please, don't give up, dev team. we `<3` thimble.
=

**Comment by Pomax** [comment]
@khanh2003 hosting a static site that is used by thousands of people a day and has to transfer terabytes of data each month most certainly costs a fair bit of money ;)

That said, we revisit the roadmap every six months, with the next revisit at the start of December. We all love Thimble, and we all want to work on it, but there are many projects we have to work on, and so with Thimble mostly at a point in its life where new features are nice to have, but only bugs *need* to be fixed, most of our attention has to go to projects that are not at that level of maturity yet. It's not just a matter of "what we want", in absence of a wider contributor community in terms of hacking on the code it's literally a matter of "what we have the employee-hours to do" and this half-year stretch we only have the employee hours to do bug fixes. 

That doesn't mean we're not listening, and we're already looking at moving some effort back onto Thimble, but we need to figure out how much of that is something that we should be doing, and how much of that is things are things that we should ask others to help us do instead.

So on that note: would you be interested in programming on Thimble, and implementing a -what sounds like- imgur style project gallery concept where people can see all projects being published, with a comments thread per project, and a gallery of "most upvoted" thimble projects?

**Comment by khanh2003** [comment]
If you are busy, I can help. But I need some docs to start working :D #1324
At least I don't have to worry that you don't have enough money to run this project and the message is `stage 1 out of 3` of this project's death. Can you call all the old contributors to work on the docs?
I don't know node.js but I'll learn when contributing to this project. I am good at frontend.

**Comment by Pomax** [comment]
The problem with hand-picking is that someone needs to do the hand picking, and with events that yield literally hundreds of thimble makes a day, that takes a lot of time. I'm not talking about likes on facebook, which are only seen by a handful of people and don't yield a meaningful "summary" main page, but more upvotes on reddit.com or imgur.com, where the community gets to upvote content they think other people should see too, and everyone can either just look at "the new stuff as it gets submitted", or they can look at "those items that were popular enough across the entire community to make it to the front page".

We are most certainly not going to have any capacity to work on a gallery of all projects until we do re-road-mapping in December, but if you want to help out we do have enough time to help you get started prototyping your own idea around this to see how far you can get with it. 

Let me ping @humphd and @gideonthomas on this because they're good at explaining how to set up thimble and brackets for the obvious "thimble frontend" part, as well as the publishing service that you would need to work with (because a gallery would need to somehow be able to ask the publishing service for some kind of summary information ordered on time and popularity, for presenting *something* in the gallery). Let me also ping @simonwex who is heads the production teams at the Mozilla Foundation and might have some good advice on getting started with something like this, too.

Finally, there is the Thimble channel on the Mozilla Foundation "mattermost" instance (which is a bit like Slack but open source) over on https://chat.mozillafoundation.org/mozilla/channels/thimble - there are generally people in there during North American work hours to both help you get started, and help answer questions you might have.

**Comment by gideonthomas** [comment]
Hi @khanh2003, I'm not sure if one of us has gotten back to you with this information or not but you can find the setup docs [here](https://github.com/mozilla/thimble.mozilla.org#setup). I would advise that you begin there since the setup is a bit involved and you might run into some issues there and if you encounter problems, feel free to ping me here or on Mattermost (gthomas). 

If you have already set the project up, you probably want to choose which component of the gallery feature you would like to try to implement:
- Image representation of a published project - Somehow we need a way to represent a published project as an image. This might involve just having a screenshot of the landing page, or something else (We're open to other ideas). If it is a screenshot, we need code to make that possible. I believe some previous work has been done on a similar feature in one of our old applications here: https://github.com/mozilla/webmaker-screenshot. Maybe that might provide some insight into how to approach this problem.
- Getting data from the publishing service to display projects that will be shown in the gallery - This is mainly the backend piece that needs to be written. It involves creating API endpoints on our Publish service to accept an image representation of the project to store somewhere (maybe S3 or the database) and also to provide data needed (project title, description, image, remix link, etc.) to populate the gallery.
- Layout of the gallery itself - This will probably be mainly design oriented. You can start by creating simple HTML/CSS/JS files that will work with dummy data (data that is made up) and style it in such a way that it shows what you envision the gallery will look like. It doesn't have to have the header/footer and all the other Thimble-specific components that exist on the other pages. We can then work together on integrating that prototype page into the Thimble codebase and make the project data dynamic using the Publish service and our templating engine - [Nunjucks](https://mozilla.github.io/nunjucks/).
- Social features of the gallery (share, comments, etc.) - This is also primarily design and ideation about how these would look in the gallery. You may want to work on this after the layout part mentioned above has been worked on.

Once you've chosen one of the above, we can help you figure out where to put the code and how the integration of it works with Thimble.

**Comment by flukeout** [comment]
Filed #1625 as a follow up.

**Comment by flukeout** [comment]
Closing as follow up was filed.
