### ISSUE TITLE
Links are broken in the preview for missing head elements

### ISSUE THREAD

**Issue by samueller** [mozilla/thimble.mozilla.org#1514]
We recently taught a first class to many 13-18 year old kids HTML/CSS and nobody's links were working in Thimble. Turns out, if you omit the `<head>` element (perfectly valid HTML), links just go to a blank page in the preview. When publishing the links work fine though:
https://thimbleprojects.org/ucode/86940/

Also, the remix button is missing. That can be a good thing sometimes as I noted in another issue:
https://github.com/mozilla/thimble.mozilla.org/issues/1503#issuecomment-233224108

(to remix)
https://thimble.mozilla.org/en-US/projects/86940/remix

**Comment by gideonthomas** [comment]
Hi @samueller thanks for reporting this! There seems to be 2 parts to this bug so I'll address them separately.

1. The missing remix button - Duly noted. The remix button is missing in the published version for this project because of the missing `<head>` element. I think that's a case we should handle. I also agree with having the ability to toggle the remix button's visibility but I will add comments in the issue you have linked.

2. Links not working - This is a bug (a regression I think) in our link code. There really are two issues here. 
 * First, the link in your project does not work because of Mixed Content issues i.e. using `http://youtube.com` instead of `https://youtube.com`. This was fairly easy to fix by just adding the `s` after `http`. Unfortunately, if a website does not support `https`, it cannot be loaded on Thimble. In spite of this change, the link still does not work, which brings me to the real problem.
 * When you click on that link, currently, it tries to load Youtube in the Preview window. This is actually an impossible task and hence it is failing. Instead, we had decided to open that link in a new tab/window in your browser. It seems like that is no longer happening and needs to be investigated cc @humphd. Accordingly, I am going to change the title of this issue to reflect this.

Thanks for filing this and we will get to fixing this issue soon.

**Comment by samueller** [comment]
This issue is more than just about external links loading in the preview. Relative links also show a blank white page with a missing `<head>` element. If the `<head>` element is there, then relative links load within the preview.

**Comment by gideonthomas** [comment]
hmm, @samueller would you be able to provide an example project that I could remix? I can't seem to reproduce this issue.

**Comment by samueller** [comment]
@gideonthomas I provided a link to remix above, here it is again:
https://thimble.mozilla.org/en-US/projects/86940/remix

I updated it to have a relative link as well

**Comment by gideonthomas** [comment]
hmm yeah it seems like links are totally broken! Thanks for catching this! I'll update the ticket

**Comment by gideonthomas** [comment]
As mentioned above, links in the preview do not work and show a blank page when a `<head>` element is missing. This is relevant to relative links since external links should be loaded in a new tab (which is also broken).

**Comment by samueller** [comment]
Issue seems simple enough, Thimble is not inserting its JavaScript code in the `<head>` element if the `<head>` element doesn't exist.

**Comment by gideonthomas** [comment]
Yep that's basically it! Brackets does not inject the remote scripts.

**Comment by samueller** [comment]
Curious about the status of this issue. It's pretty major IMHO as many students get frustrated by it very early on.

**Comment by gideonthomas** [comment]
@samueller I have a patch up for this, we will get it in ASAP
