### ISSUE TITLE
Oh no! The page you're looking for  is not available!

### ISSUE THREAD

**Issue by MsZabel** [mozilla/thimble.mozilla.org#1530]
Why won't my link work - i published 
https://thimbleprojects.org/ccwebtest/90043

**Comment by gideonthomas** [comment]
@MsZabel are you sure you published the project? From our database, the id 90043 is the id of your project but not of the published one (the database shows us that the project has not been published). Can you try clicking the "Publish" button on the top right corner and then in the dialog that pops up, click the "Publish" button again?

**Comment by mrcallaghan** [comment]
@gideonthomas  I have a student with a similar issue.  Watched him publish the project in class, but published link is not working.  Here's the link:  https://thimbleprojects.org/mlweese/111296

**Comment by humphd** [comment]
Question: do either of these projects *not* have an `index.html` page (i.e., did you rename it)?

**Comment by gideonthomas** [comment]
@mrcallaghan looks like that project's index.html file was renamed to index-1.html and that's why you aren't able to see anything at the link above. You will be able to see the contents if you hit up the link: https://thimbleprojects.org/mlweese/111296/index-1.html. (we're working on a good way to remind users through the interface of the need to have an index.html file).

@MsZabel I don't see a project associated with that link you've provided above. I see three projects published by that username:
- InstructorGuide v1 which apparently has a published link (https://thimbleprojects.org/ccwebtest/90051) but for some reason is not accessible
  - We still have your content so I will update the link to make it accessible
- JS4WorkingWEb accessible at https://thimbleprojects.org/ccwebtest/97657/
- Untitled Project which has not been published yet
If you could clarify which project you are referring to above, it would help us narrow down the problem.

**Comment by gideonthomas** [comment]
We have come up with a UX solution here: #1569, will be tracking the conversation there as well.
