### ISSUE TITLE
"publish" button frequently does nothing unless I slow-click down and back up

### ISSUE THREAD

**Issue by Pomax** [mozilla/thimble.mozilla.org#1534]
If I just quickly click the "publish" button for my project while moving my mouse around because I'm still busy, quite often nothing happens and I end up having to position the mouse over the button, and click without moving the mouse at all.

It feels like the wrong event is being tapped into in order to determine whether a user clicked the publish button, where it listens for "click" (which can get frustrated by a click-drag when a user is clicking and moving the mouse at the same time) when it should be listening for "mousedown" instead.

**Comment by flukeout** [comment]
Also, the very top edge of the button doesn't have an effect.

**Comment by humphd** [comment]
We do the event handling for this here:

* https://github.com/mozilla/thimble.mozilla.org/blob/fa3dde088dc016a562520e62a9df1f5558ba8f70/public/editor/scripts/editor/js/fc/bramble-ui-bridge.js#L333
* https://github.com/mozilla/thimble.mozilla.org/blob/fa3dde088dc016a562520e62a9df1f5558ba8f70/public/editor/scripts/editor/js/fc/bramble-ui-bridge.js#L305-L322

I wonder if we need to stop that event once it fires (i.e., `e.preventDefault();` and `return false;`).

**Comment by cgsingh** [comment]
I would like to attempt to fix this issue.

**Comment by flukeout** [comment]
Sounds good @cgsingh - I'm pretty sure the only reason this happens is because the button shifts downwards when it is clicked, and so the mouse isn't pointing at it anymore. You can see that behavior here... 

![publish](https://cloud.githubusercontent.com/assets/25212/22382507/cfbdde42-e47a-11e6-9831-552836b30a94.gif)

Let me know if you want some ideas on how to solve this or if you've got your own.

**Comment by cgsingh** [comment]
Thanks for pointing that out @flukeout. If you've got any ideas, I'll gladly take them. Right now I'm in the process of setting up Thimble and all its dependencies so I can actually start working. I just wanted to reserve this issue for my class so nobody else takes it, ha.

**Comment by cgsingh** [comment]
I'm pleased to say that I've fixed the bug and I only edited the bramble-ui-bridge.js file. Instead of click(), it uses the mousedown mouse event, however it'll only call the showPublishDialog() function if the left-button was pressed. This also strangely solves the top-edge issue as well, but I'm not complaining! I'll be making a pull request as my assignment instructs me to do. Thanks for giving me the chance.
