### ISSUE TITLE
Add images dynamically via JS - failed

### ISSUE THREAD

**Issue by khanh2003** [mozilla/thimble.mozilla.org#1535]
# SERIOUS PROBLEM! Fix it.

Go to this URL:
https://thimbleprojects.org/khanhcrazy/90416/
The icon in the top-left corner works fine.
Now click Remix.
The icon doesn't show.
![hoc462](https://cloud.githubusercontent.com/assets/17680976/17481491/b1e1ceba-5da7-11e6-9ea2-4b8b2dbd5705.png)
![screen shot 2016-08-08 at 8 35 36 pm](https://cloud.githubusercontent.com/assets/17680976/17481502/ba81697c-5da7-11e6-86e0-f45f6f73b234.png)
![screen shot 2016-08-08 at 8 35 32 pm](https://cloud.githubusercontent.com/assets/17680976/17481505/bf52c266-5da7-11e6-849b-5106a983c317.png)
Read the code please!

**Comment by Pomax** [comment]
on an HTML5 technical note, `<img>` is a void element (i.e. it may not have any element content, only attributes) and as such does not need a closing tag. Browsers will look the other way when you do, but leaving it off is proper HTML5 syntax (this changed with respects to HTML4.01 and below, when the closing `</img>` was still necessary)

**Comment by gideonthomas** [comment]
Hi @khanh2003,

It looks like you're loading the images dynamically through JS. Unfortunately, that is not something Thimble can do in its current state. 

There are bunch of complications that we face when attempting to implement something like this. The most important one is the complexity of string parsing. When we encounter a link in HTML (js, images, etc.), on the editor side, we get the contents of that file in the file list that you see, replace the link with a generated blob url based on the contents of that file, and only then pass it onto the preview to show the result. Note that this happens on the editor side. Unfortunately, if you try to use these links in a string in javascript for e.g., we will have to search for it and repeat the same process. Unfortunately, searching for HTML in strings in JS can be very tricky and complicated and error-prone (we might end up replacing a string that was not meant to be replaced).

I don't think this feature was an intended use case for Thimble as a learning tool. Instead, might I suggest a workaround? Would you be able to move the HTML used in `design.js` directly into the HTML file that links to it? That should work since all the links will be parsed correctly.

**Comment by Pomax** [comment]
It looks like this happens because while brackets modifies HTML such that image links are turned into blob links, when you use locations in JS, there is no blob rewriting, and so the virtual file system that Thimble relies on is not used.

Instead of using string manipulation and innerHTML setting (which is quite error prone and potentially page-breaking), you can do what you want by defining real HTML elements on the page, and then moving them around/toggling them with javascript instead, so you get something like:

```html
<div class="inactive icons">
  <img src="Hoc426.png" class="thingbutton">
</div>
```
with CSS

```css
.icons {
  display: none;
}
```

and the in JS you can do things like this:

```
// make the 'thingbutton' icon an active button
var icon = document.querySelector('img.thingbutton');
icon.addEventListener("click", function(evt) {
  // trigger anything you like in plain JS here
});
var realParent = document.querySelector("css selector for the element you want the active icon to live in");
realParent.appendChild(icon);
```

**Comment by khanh2003** [comment]
ok, thanks.

**Comment by khanh2003** [comment]
Changed my mind.
What about AJAX? If you don't replace the URL in JS files, I'm sure AJAX won't work.
Or are you thinking that children are too young to learn AJAX? AJAX is important!

**Comment by humphd** [comment]
We have another Bramble bug on this, which requires us using Service Workers vs Blob rewriting. It's in progress, but is a big change.

On Aug 9, 2016 9:25 AM, khanh2003 <notifications@github.com> wrote:

Changed my mind.
What about AJAX? If you don't replace the URL in JS files, I'm sure AJAX won't work.
Or are you thinking that children are too young to learn AJAX? AJAX is important!

-

**Comment by khanh2003** [comment]
Hint: On Chrome, you just use FileSystem API.

Sorry but your project is so complex so I can't contribute.

**Comment by gideonthomas** [comment]
@khanh2003 I think if you use `XMLHttpRequest` directly (I might be wrong though) it should work (I remember writing a patch for that a while ago).  
<br>

> Sorry but your project is so complex so I can't contribute.

It's actually something we're working on - better documentation, better modularity, easier setup.

<br>
The problem with using the FileSystem API is that it is *only* supported in Chrome.
