### ISSUE TITLE
iframes don't work

### ISSUE THREAD

**Issue by Pomax** [mozilla/thimble.mozilla.org#1538]
I tried to make a page a little more organised by refactoring several example sections into separate html documents that are included on the main page with `<iframe href="./filename.html"></iframe>`, but brackets does not do the right thing in this case, preserving the `href` attribute instead of rewriting it so that it points to a thimble filesystem blob resource.

**Comment by humphd** [comment]
I suspect this is due to us not rewriting html "links", since doing so can result in infinite loops, with a.html pointing to b.html, and vice versa. We probably need the Service Worker server rewrite for this, or else to special-case iframes.

On Aug 11, 2016 1:46 PM, Mike Kamermans <notifications@github.com> wrote:

I tried to make a page a little more organised by refactoring several example sections into separate html documents that are included on the main page with <iframe href="./filename.html"></iframe>, but brackets does not do the right thing in this case, preserving the href attribute instead of rewriting it so that it points to a thimble filesystem blob resource.

-

**Comment by Pomax** [comment]
I see

(on a sidenote, your email replies seem to post your reply *with* the entire message quoted including the "you are receiving this because you are subscribed to this thread, reply to this email directly etc. etc" footer... makes for huge comments when the actual information is only one or two sentences =)

**Comment by gideonthomas** [comment]
I can try to find the bug that deals with circular linking. If we have that somewhere, we can probably close this, otherwise, it's good to have this evolve into the broader issue

**Comment by Pomax** [comment]
ha! You know what? I used `href` instead of `src` as linking attribute. With `src` it works perfectly fine. I've been javascripting so long I've forgotten basic HTML syntax >_>
