### ISSUE TITLE
ADD folder not a fille 

### ISSUE THREAD

**Issue by FERMAT1991** [mozilla/thimble.mozilla.org#1561]
a can't add a folder that has all my image and my css style

**Comment by humphd** [comment]
Browsers won't allow you to drag an entire folder from the file system into a page for security reasons--only files are allowed.  To get around this, we support importing a `.zip` file, which might contain files *or* folders:

https://github.com/mozilla/thimble.mozilla.org/wiki/Using-Thimble#upload-archives

This is a valid request, but since we can't get around the security restriction, I'm going to close this.
