### ISSUE TITLE
Page Not Found after publishing

### ISSUE THREAD

**Issue by gideonthomas** [mozilla/thimble.mozilla.org#1569]
Most of the bugs filed related to this are because of a missing `index.html` file in their projects.

The solution that we have come up with is to explain why an `index.html` is needed probably as a dialog box or something when a user renames the index file, deletes it or publishes without one. The reason we also show the dialog during publishing is to account for the case when a user remixes a project without an index file.

As an additional step, we should provide the option to automatically generate an index.html file before publishing the project.

Issues closed as a result of consolidating duplicates:
- https://github.com/mozilla/thimble.mozilla.org/issues/1563
- https://github.com/mozilla/thimble.mozilla.org/issues/1560
- https://github.com/mozilla/thimble.mozilla.org/issues/1530
- https://github.com/mozilla/thimble.mozilla.org/issues/1261
- https://github.com/mozilla/thimble.mozilla.org/issues/1260

**Comment by flukeout** [comment]
@gideonthomas is the solution you came up with fleshed out in more detail in another issue somewhere? If not, we can start that work here.

**Comment by gideonthomas** [comment]
What I mentioned above is basically what we discussed in the call. I don't think we specced out UI details for it so it would be good to start that here.

**Comment by flukeout** [comment]
Can you weigh in on solution #1260 - it's suggested by your 'additional step' as well. If we are able to just do this - we won't have to worry about adding anything to the dialog.

I'll work on some publish dialog ideas in the meantime. Maybe we could just prevent publishing without a root 'index.html` file - or maybe we make it non-deletable?

**Comment by humphd** [comment]
FWIW, I'm currently working on a patch to Brackets to have it monitor renames/deletes of `index.html` and let the user know so that they can undo it, add one, or just be aware when they load it.

**Comment by gideonthomas** [comment]
@flukeout we should probably still put something in the Publish dialog because it is not obvious that the `index.html` file was generated. It could lead users to think that such a file will always be generated and is not a Thimble specific thing. Removing it from the Publish dialog will take out the educational aspect of it which I think should be our focus in this issue (with the directory structure thing being secondary)

**Comment by humphd** [comment]
The Bramble bit of this is up for review in https://github.com/mozilla/brackets/pull/564

**Comment by humphd** [comment]
I want to start on the Thimble side of this too, which means dealing with what happens when you publish.  I have a question.  We have no good way to flag a file as generated vs. user created, especially across remixes.  At the point of publishing, I can look for `{root-dir}/index.html` and if it's missing, automatically generate something like you have above.  However, this file will be static, and if the user (or the remix user) doesn't touch it, but other aspects of the filesystem change, it will go out of sync.  I'm not sure that's a huge issue, but I want to flag it.  I don't think we should invent some complex set of flagging for this case.

There are a few ways to go here:

* We could choose to have the generated page not refer to anything in the filesystem as such, and just provide a generic "Hey, you don't have an index.html file, so that's why you're not seeing your stuff..." message.  This would be primarily aimed at the original author, who would hopefully correct the problem by editing the generated `index.html` file.
* On publish, we could scan the root dir for other HTML files, and suggest something that will work for the publish URL vs. something that will break.  This assumes that there is an HTML file of some kind (a fairly safe assumption, but not required I guess).  So instead of doing what we do now, which is to show "Here's a link you can share... https://thimbleprojects.org/humphd/128353", we'd do "Here's a link you can share...https://thimbleprojects.org/humphd/128353/other-file-we-found.html"
* I could do exactly what's suggested above and statically generate an `index.html` file that will show you all the various files (or maybe just the HTML files?) in the root dir.

Which way should I go?

**Comment by flukeout** [comment]
@humphd I like your first bullet point suggestion - generating an index.html page with some generic copy that won't go out of date if the project contents change. I figure the first person to see that will be the project author right after publishing anyway, which will hopefully encourage them to act on the issue.

**Comment by humphd** [comment]
@flukeout I agree, that feels the most resiliant to remixing, and also the simplest.  Would you be willing to do some kind of good looking static page for me?  I can wire it in so that it gets added and synced up.

**Comment by flukeout** [comment]
Will do. I'll probably make a Thimble project and drop the link in here.

**Comment by humphd** [comment]
Awesome thanks! Also, you're so meta! @flukeout++

**Comment by flukeout** [comment]
Just to clarify, are we adding this index.html file to just the published project, or also into the working, editable copy of the project?

**Comment by gideonthomas** [comment]
Doing it on the published project might make more sense. @humphd since Thimble is aware of whether the index.html needs to be created or not, we can probably pass in a query param when publishing to the publish server to indicate that publish needs to create the index.html file before uploading to S3

**Comment by flukeout** [comment]
Yeah that sounds good, I'll assume that for the time being in the copy of that generated page, which I'll paste a mockup of shortly.

**Comment by flukeout** [comment]
Here's my take on this page, let me know your thoughts.

![image](https://cloud.githubusercontent.com/assets/25212/20077383/fdb8017a-a4f0-11e6-859c-823aa71478ca.png)

**Comment by gideonthomas** [comment]
@flukeout this page looks great (you did this in half a day? 😮 )!

Can we change some of the terminology in the copy? I remember a bunch of kids not knowing what a "server" was in a session I was hosting in Toronto. Any way we can make it a little more vague or explain what a server is? Also, "404" often doesn't mean anything to most users, maybe change it to something like "you will see an error saying that your page was not found"?

**Comment by flukeout** [comment]
Haha thanks. I'll take another stab at it with some more approachable copy and post and update here in a bit.

**Comment by humphd** [comment]
I like this a lot, @flukeout .  I also like the idea of sending a param to publish indicating that it should add the page to S3, but not include it in the project--nice idea @gideonthomas.

I'm happy to do the Thimble-side changes of this, but maybe @gideonthomas could take the publish patch?  I'm less well acquainted with that code.

**Comment by flukeout** [comment]
@gideonthomas I can't find it but I thought we had a ticket for adding a message to the Publish dialog for index-less projects. Anyway, I came up with a little mockup

![image](https://cloud.githubusercontent.com/assets/25212/20081596/6e282e9e-a505-11e6-8def-b40d1dd1cccc.png)

I guess it could be yet another line of defense, haha.

Wether we decide to implement this as well, we need to make sure that our copy and messaging about this issue is standard across:

* Publish popup dialog (above)
* Auto generated index-page (screen cap earlier in this thread)
* Dialog popup when attempting to rename/delete the index page (currently a PR)

What does everyone think about adding a message to the Publish dialog as well? Is it getting to be too much?

**Comment by flukeout** [comment]
And updated copy for the generated ``index.html``

![image](https://cloud.githubusercontent.com/assets/25212/20081811/b5ab5a38-a506-11e6-9777-3ac19a4d6322.png)

**Comment by gideonthomas** [comment]
@flukeout both these mockups look great! I vote for doing both.

@humphd sure thing! Let me know if you need any help with it. I'll implement the publish part.

**Comment by flukeout** [comment]
Maybe we can ditch the description field in the dialog while we're at it :D

**Comment by gideonthomas** [comment]
@flukeout do you think we will be adding it back when we implement the gallery though?

**Comment by flukeout** [comment]
I'd imagine so yes, we can just comment it out for now. It's lame having it there without any real use. It doesn't even serve as a good internal reminder for the author because it only lives on published projects.

**Comment by humphd** [comment]
Amen to dropping that desc field.

**Comment by flukeout** [comment]
Okay, @humphd - here's the index page: https://thimbleprojects.org/flukeout/129439/
Let me know if you run into any problems or issues.

**Comment by flukeout** [comment]
Ping @humphd @gideonthomas - just checking in that you've got what you need for this. Let me know.

**Comment by humphd** [comment]
@gideonthomas said he was going to do this at the publish server, so bouncing this to him to implement.

**Comment by gideonthomas** [comment]
Yep sorry, that page should be fine.

**Comment by flukeout** [comment]
On an unrelated note this always trip me up when i'm looking at my tabs...

![image](https://cloud.githubusercontent.com/assets/25212/20321305/d434fe18-ab29-11e6-9dca-210de3cf8b77.png)

**Comment by flukeout** [comment]
Hey @humphd and @gideonthomas - what's the status of this issue? Seems like we were making some great progress, but just sort of stalled out.

The generated index page is ready to go: https://thimbleprojects.org/flukeout/129439/

We can split out the warning dialog message into another issue.

**Comment by flukeout** [comment]
Just to follow up on this as it seems stuck, what if we just add some help copy to this page...

<img width="519" alt="image" src="https://cloud.githubusercontent.com/assets/25212/22752600/fc1ecfce-eded-11e6-8f6d-39b51b40943a.png">

``Is this your project? If you're seeing this, add an index.html file to it``

This would solve a lot of our support requests and it would also make a good first bug.

@gideonthomas Let me know if you're planning to get the stuff in this issue landed, but I feel like maybe we should just go with what I've described here if that will take too long.

**Comment by gideonthomas** [comment]
@flukeout up to you. I can try to get it done by next week, but if you think that this will get done faster (or is generally a better solution), we can totally go with this.

**Comment by flukeout** [comment]
Let's not prioritize this issue for now @gideonthomas - the changes I suggested to the 404 page are live now, and I think it has basically the same effect.

**Comment by flukeout** [comment]
Alright, I'm going to close this as we've adressed it in some way with the 'missing html page' warning. We can file subsequent improvement & feature issues if we need them.
