### ISSUE TITLE
quick add of bootstrap

### ISSUE THREAD

**Issue by FERMAT1991** [mozilla/thimble.mozilla.org#1571]
It will be nice if I can add bootstrap quickly 
great work so far keep up the good work .
thank you

**Comment by flukeout** [comment]
We could solve this and similar use-cases by providing a bunch of remixable templates. Not sure where we'd put them though - need to work on the discoverability piece on the homepage.

**Comment by humphd** [comment]
I agree that the best way to do this is at the project level vs. the file level, namely, having pre-made projects that people can remix.

I think that our homepage could really use a refresh to include some new templates.  But, even if we don't want to totally redo this, it might be nice just to have a `Click Here for More Remixable Projects...` link that takes you to a big page of projects with things like Bootstrap, Material Lite, A-Frame, some game libs, whatever.  This seems like a pretty trivial thing for us to do, and could be a big win for people wanting to jump into something quickly.

**Comment by jgmac1106** [comment]
+1 to this idea.

**Comment by gideonthomas** [comment]
I think we should discuss this further. I actually don't think it's a good idea to only have remixable templates containing these libraries for two main reasons:

1. I can't think of any other product that does it in that manner. Since other products like JSFiddle, CodePen, etc. do it on a per project basis, allowing the user to choose which libraries to include, I don't think it makes sense to sharply deviate from that.
2. It is very limiting to how much a user can customize what libraries are included in their project. We can only create so many combinations of these libraries to generate templates, but it definitely will not account for all use cases.

I'm not saying that we should not create templates that use these libraries at all. I think those would be useful as a starting point for a bunch of users. But I do think it is important to leave it open-ended and let users select what they want to include in their project.

**Comment by humphd** [comment]
@gideonthomas I think that trying to do what JSFiddle, CodePen, etc. do is not our job--they already do it, and do it well.  We should do what we do well, which is allowing filesystems full of files *and* folders to be used for projects.  They have to do hacks to include library X in the environment because they have no easy way to literally include the file along with your code.

As far as trying to support every possible combination, I think that's a red herring: we currently support none of them, so how does adding support for some of them not make us better?

**Comment by gideonthomas** [comment]
I don't think we need to confine ourselves with the same UX as JSFiddle or CodePen which as you mentioned is ideal for their use case. It would take some thinking into how to integrate these different libraries into a project in a way that effectively utilizes our filesystem infrastructure and basically all the differentiators that we have w.r.t. CopePen, JSFiddle, etc. 

But the underlying problem of allowing easy integration of commonly used libraries in a website still remains. Remixable templates do not really address the integration problem and instead provide a compromise. I'm pretty sure adding whatever set of libraries we decide to support to the filesystem of a project is fairly trivial. The tricky bit here would be figuring out what UI/UX would be ideal to show them this feature and how to use it.

**Comment by jgmac1106** [comment]
This is how I learned bootstrap (my first real library I used) a year or so ago. I googled one page website template and found: https://startbootstrap.com/template-categories/one-page/

I then downloaded the zip files. I could not use Thimble for the project so I just used a regular text editor.

From there it was just a series of lessons from Google "How do I use accordion tables in bootstrap? how do I embed iframes in bootstrap? etc.

If we had  link(s) on the Thimble home page to stuff that @humphd suggested I think it could work....and be awesome

Getting people to write the tutorials would be a great "first bug" for a campus club, a computer science class, or just an individual  to contribute.

**Comment by jgmac1106** [comment]
This is how I learned bootstrap (my first real library I used) a year or so ago. I googled one page website template and found: https://startbootstrap.com/template-categories/one-page/

I then downloaded the zip files. I could not use Thimble for the project so I just used a regular text editor.

From there it was just a series of lessons from Google "How do I use accordion tables in bootstrap? how do I embed iframes in bootstrap? etc.

If we had  link(s) on the Thimble home page to stuff that @humphd suggested I think it could work....and be awesome

Getting people to write the tutorials would be a great "first bug" for a campus club, a computer science class, or just an individual  to contribute.

**Comment by jgmac1106** [comment]
This is how I learned bootstrap (my first real library I used) a year or so ago. I googled one page website template and found: https://startbootstrap.com/template-categories/one-page/

I then downloaded the zip files. I could not use Thimble for the project so I just used a regular text editor.

From there it was just a series of lessons from Google "How do I use accordion tables in bootstrap? how do I embed iframes in bootstrap? etc.

If we had  link(s) on the Thimble home page to stuff that @humphd suggested I think it could work....and be awesome

Getting people to write the tutorials would be a great "first bug" for a campus club, a computer science class, or just an individual  to contribute.

**Comment by jgmac1106** [comment]
This is how I learned bootstrap (my first real library I used) a year or so ago. I googled one page website template and found: https://startbootstrap.com/template-categories/one-page/

I then downloaded the zip files. I could not use Thimble for the project so I just used a regular text editor.

From there it was just a series of lessons from Google "How do I use accordion tables in bootstrap? how do I embed iframes in bootstrap? etc.

If we had  link(s) on the Thimble home page to stuff that @humphd suggested I think it could work....and be awesome

Getting people to write the tutorials would be a great "first bug" for a campus club, a computer science class, or just an individual  to contribute.

**Comment by Pomax** [comment]
@humphd hmm, but one of the great things about a good IDE is being able to say "yeah actually I need this dependency" and have it go and grab that for you without having to interrupt your workflow. At the very least some way to say "hey add this *from URL* please" so that you can just give Thimble the url for bootstrap's release archive (we can unpack `.tar.gz`, right?) makes things much nicer than having to be in the browser, download files to your computer, leave the browser, unpack them to a folder, then drag the folder back into the browser. This should be entirely doable without the "leaving the browser" part. It least, it feels like it should be.

**Comment by flukeout** [comment]
Going to close this for now, as we aren't planning on implementing this as a feature. Given the direction we've decided on, we could accomplish this via...

* A starter kit
* Including it as one of the code snippets
  * Maybe all of the required links in the head of an HTML file?
