### ISSUE TITLE
Cannot load sound files from p5js

### ISSUE THREAD

**Issue by bleungwpg** [mozilla/thimble.mozilla.org#1589]
https://thimbleprojects.org/benleung80/140868

I have a published thimble project above.  I am using p5js in order to load sounds.  The project works fine if I run it locally on my computer.  However when I try to run it on thimble the project fails. I have also tried to run the file off the thimble server rather than hosting it through github but it still fails.

The problem does not appear to be related to hosting files on dropbox as the image file loads properly. However as soon as I try to preload the sound file the program craps out into an infinite loading file.  You can comment out the line of code in the sketch.js file in function preload() to see that the program works properly without it.

function preload() {
  picture1 = loadImage('https://dl.dropboxusercontent.com/s/0fjvux8xprt0yb8/image1.jpg');
  
  // comment the line of code below and the program works.
  sound1 = loadSound('https://dl.dropboxusercontent.com/s/bziq4gufuakv7go/dolow.mp3');

}

**Comment by bleungwpg** [comment]
The sound file works only when it is published but not when I try it locally.

**Comment by bleungwpg** [comment]
locally as in on my thimble account under preview

**Comment by humphd** [comment]
This is related to https://github.com/mozilla/brackets/issues/549.  Basically, any URL you work with in JS will break in Thimble at the moment, because we can't properly intercept it and rewrite it into a Blob URL.  The way to solve this is to switch to using Service Workers for our network layer.  It's something I've started on, but it's not close to being done, unfortunately.

**Comment by humphd** [comment]
See also #1322.

**Comment by bleungwpg** [comment]
Awesome, glad to hear!
