### ISSUE TITLE
Investigate: do non-english characters in the project title and/or description prevent it from loading?

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.mozilla.org#1591]
We had an issue recently where we suspect that a non-english character (like ä) caused Thimble to not be able to load a saved project for a user.

@gideonthomas do you want to add any details?

I'll test with a few different chars and see what happens.

**Comment by humphd** [comment]
Not sure if this is related at all, but I remember we hit something like this with MySQL and Popcorn Maker long ago related to encoding of strings.  @jbuck, @Pomax, @cadecairos, @ScottDowne  might remember details.

**Comment by jbuck** [comment]
What text encoding is the database using? The specific problem we ran into with Popcorn Maker was that we were using String.prototype.length() to count Content-Length instead of Buffer.prototype.length() when uploading text containing multi-byte UTF-8 characters.

**Comment by gideonthomas** [comment]
To clarify, this is purely happening on the front-end. On first load, the data makes it to publish.wm.org fine. On the front-end, I don't think I saw any pending network requests which probably means that the tarball is making it across fine. So the issue is most likely either when we're untarring the contents or when writing to the filesystem which is Filer backed by IndexedDB. We are always working with buffers on Thimble and that's what we're passing to Filer as well which directly writes it to IndexedDB.

For a bit of context, we are having trouble specifically with this project:
[Lagar och bestämmelser.zip](https://github.com/mozilla/thimble.mozilla.org/files/629111/Lagar.och.bestammelser.zip)

More info:
"title": "Lagar och bestämmelser"
"description": "Skoluppgift lagar och bestämmelser, webbutveckling"

I cannot reproduce this locally. It gets stuck on "loading project". I have to clear IndexedDB and then it loads ok.

**Comment by flukeout** [comment]
Closing this as it's pretty old and we haven't run into something like this for a while.
