### ISSUE TITLE
publishing problem

### ISSUE THREAD

**Issue by V1ncenz0** [mozilla/thimble.mozilla.org#1592]
Hello thimble, I have a problem with my new project. I can see it in the demo but when it try to publish it and I click on the link. It redirect to page saying oh no. Can you help me please.

Swk

**Comment by gideonthomas** [comment]
Hi @V1ncenz0!

In your project, did you happen to rename or delete your `index.html` file? Whenever you head to a url like `https://mozilla.org`, browsers will show you the contents of `https://mozilla.org/index.html`. A missing `index.html` file will result in you seeing the "Not Found" page. If you adda new `index.html` file OR rename one of your existing html files to `index.html` (right-click on the file name on the left in the file list in your project and click "Rename"), it should resolve your issue.

Let me know if this helps otherwise we can investigate further.

**Comment by V1ncenz0** [comment]
Hi,
It Washington actually the problem thank you for the advice.

Vincent D.

**Comment by flukeout** [comment]
And closed! Even more reason to finish up #1569
