### ISSUE TITLE
CSS problem

### ISSUE THREAD

**Issue by V1ncenz0** [mozilla/thimble.mozilla.org#1594]
Hello, I just wanna say that there is an issue with the style.css. Sometimes, when I am working on my project, all my CSS content disappear. Is it an issue or is it just me?

**Comment by gideonthomas** [comment]
Hi @V1ncenz0! I'm sorry that you're experiencing data loss. Would you be able to provide a few more details so that we can help figure out what's going wrong?

- Are you renaming the CSS file by any chance?
- Did you refresh the page or close and re-open the page in between the last time you saw the contents and then when you found it missing?
- Did you see a "Saving Failed...Retrying" error near the project title at any point?

**Comment by flukeout** [comment]
Also, have you published the project? If so - can you share the URL so we can have a look?

**Comment by flukeout** [comment]
As it's been more than a month, I'm going to go ahead and close this.
