### ISSUE TITLE
Tutorial creation option in file-tree is not available after when tutorial.html is deleted

### ISSUE THREAD

**Issue by rlchung** [mozilla/thimble.mozilla.org#1596]
After when tutorial.html is deleted, the tutorial creation option in the file tree is still unavailable to the user. Refreshing the page, however, fixes the issue. Similar to #1279.

![](https://i.gyazo.com/52508250e00e523b46526d05ef31371d.png)

I believe the issue to be with how the toggling between `tutorialAdded` and `tutorialRemoved` is handled. I have referenced the relevant code below:

https://github.com/mozilla/thimble.mozilla.org/blob/master/public/editor/scripts/editor/js/fc/bramble-menus.js#L210-L237

**Comment by gideonthomas** [comment]
Thanks for reporting this @rlchung!

It seems like this bug is in the editor code which resides in [this repository](https://github.com/mozilla/brackets). 

If you (or anyone) is interested in taking this bug on, the details below might be helpful.

Instead of using the filesystem's `unlink` function to delete the files, we seem to be using `rm` instead. However, the code that triggers the `tutorialRemoved` event that unhides the "Tutorial" option in the menu (as you have linked above) is only present for the `unlink` command which can be [found here](https://github.com/mozilla/brackets/blob/master/src/bramble/client/main.js#L695-L699). To fix this:
- Copy that piece of code and paste it in the callback of the [function call here](https://github.com/mozilla/brackets/blob/master/src/bramble/client/main.js#L738)
- Modify it to make sense in that context (creating a new variable for `wrappedCallback` for e.g.)

**Comment by MargarytaChepiga** [comment]
I would like to work on this bug. Can I do that?

**Comment by humphd** [comment]
@MargarytaChepiga yes, it's yours.  Let me know if you need advice on tackling it.

**Comment by Shank09** [comment]
Duplicate bug. [#1321](https://github.com/mozilla/thimble.mozilla.org/issues/1321)  This was opened 1 year ago.

**Comment by humphd** [comment]
@MargarytaChepiga same question on this bug.  What's the status of your fix?

**Comment by MargarytaChepiga** [comment]
@humphd  Here is the PR: https://github.com/mozilla/brackets/pull/693
