### ISSUE TITLE
Your Projects List > Add ability to open a project in a new tab.

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.mozilla.org#1627]
Currently, the project opens inside the same browser tab as the Your Projects page, which is annoying if you just want to quickly check what it is.

We could either...
* Figure out while command+click doesn't open a new tab
* Add a separate "open in new tab" action

**Comment by humphd** [comment]
Looks we're doing a `window.location.href` hack with this, which is probably breaking the default way of opening.  We should see if we can do this via a proper link.

https://github.com/mozilla/thimble.mozilla.org/blob/20fa70c77fb6a9dbdad29492989715178954fada/public/editor/scripts/project-list.js#L37

**Comment by omytryniuk** [comment]
I would like to work on this issue.

**Comment by gideonthomas** [comment]
Changes need to be made [here](https://github.com/mozilla/thimble.mozilla.org/blob/master/views/editor/projects.html#L30-L31). It basically needs to be wrapped in an anchor tag. 
We probably need to pass in `locale` and `querystring` as well into [options here](https://github.com/mozilla/thimble.mozilla.org/blob/master/server/routes/projects/read.js#L76) so that they can be used in constructing the url for the anchor tag.

**Comment by omytryniuk** [comment]
@humphd, @flukeout, @gideonthomas - Thank you very much for all your assistance. Feel free to let me know if you need anything else.

**Comment by humphd** [comment]
Nice work @omytryniuk!  I have no doubt that we'll have more bugs for you to tackle next.
