### ISSUE TITLE
Add affordance for the Quick Edit UI

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.mozilla.org#1641]
The quick edit UI (accessible via Command + E) is one of the coolest parts of the editor, but I'm guessing that almost nobody knows its there or uses it. For reference...

![image](https://cloud.githubusercontent.com/assets/25212/22081556/e1ab6362-dd78-11e6-93e1-26256c2741a3.png)

Can we add a visual affordance somewhere for when the colorpicker (or other quick edit UI) is available?

**Comment by humphd** [comment]
I remember trying to look for a way to do this in the past, and as far as I know, there is no event, or automatic way to know whether or not there is a Quick Edit feature for the given cursor position without simply trying it.  The code that generally manages these "inline editors" lives here https://github.com/mozilla/brackets/blob/master/src/editor/EditorManager.js.

**Comment by mfainshtein4** [comment]
![afforance-change](https://cloud.githubusercontent.com/assets/11540135/22959673/25bf0746-f306-11e6-95ef-a3c98a4fef65.png)
I initially thought of something along these lines where beside the line number there would be a display of the color selected. which also acted as a button that opened up the quick edit.

**Comment by humphd** [comment]
One thing we could try here is to have some kind of timer or event listener that tries to see if there *is* an inline editor (or even inline doc) available for the current cursor position, and if so, fire an event.  We could listen for that either in Brackets or Thimble, and alter the CSS on some button that would indicate you can click to pop-open the associated inline widget.

Figuring out when to do this, so that it 1) doesn't run too often; 2) doesn't spam the UI with too many events; 3) doesn't change state so often that the cursor is gone by the time you try and click it.  Maybe we need some kind of "cursor is idle for N ms" code to then go and fire this.

@flukeout can you mock-up some kind of UI for what I'm describing above?  I'll happily mentor someone through fixing this.

**Comment by gideonthomas** [comment]
@flukeout can you add some info here about why this is a "good first bug", i.e. are we looking for a design, are we looking for code, etc.?

**Comment by flukeout** [comment]
Maybe we need to reframe more as an experiment issue and ask it as a question:

"Can we find a good way to determine if the Quick Edit UI for color is available for use depending on the current cursor position."

It looks like someone was experimenting with this issue already but has since deleted their comments, so maybe it's too in depth for a starter issue.

**Comment by humphd** [comment]
The backend work for this is happening in https://github.com/mozilla/brackets/issues/499

**Comment by humphd** [comment]
I'm moving this forward in https://github.com/mozilla/brackets/pull/826, closing here.
