### ISSUE TITLE
Shift + Command doesn't cycle through all the files in a project.

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.mozilla.org#1646]
One project I have has three files, but hitting Shift + Command only cycles through two of them. You can see this behavior below..

![shiftcommand](https://cloud.githubusercontent.com/assets/25212/22082420/9309ed1a-dd7c-11e6-9445-aa21d4759614.gif)

...if we're going to keep this keybinding (which I don't like) let's at least fix it so that it cycles through all of the files in the project.

**Comment by humphd** [comment]
I can't get "Shift + Command" to do that, are you pressing something else too?

**Comment by humphd** [comment]
btw, bindings are here: https://github.com/mozilla/brackets/blob/master/src/base-config/keyboard.json

**Comment by flukeout** [comment]
It only happens in Chrome (not FF), and not always. Sometimes it takes adding a new file to the file tree. But once it 'kicks in' I can navigate between the files with this binding, even though it doesn't appear in the .json file you linked.

**Comment by flukeout** [comment]
Also, it happens only if you first press and hold shift, then press command. Not the other way around.

**Comment by humphd** [comment]
The code in question here is this:

https://github.com/mozilla/brackets/blob/master/src/command/Commands.js#L119-L120

For some reason, `Shift-Cmd` on mac is triggering `Shift-Cmd-[` and that fires the `navigate.prevDoc` function, which is this:

https://github.com/mozilla/brackets/blob/master/src/document/DocumentCommandHandlers.js#L1536-L1563

It looks to me like they've done their own special keyboard handling in here, because that binding is never really registered.

A good fix might be to not have `Shift-Cmd` become `Shift-Cmd-[` and this would go away.  Another fix would be to just not register the `navigate.prevDoc` command.

**Comment by simonwex** [comment]
👍 for "A good fix might be to not have Shift-Cmd become Shift-Cmd-[" as @humphd says.

**Comment by flukeout** [comment]
Yeah, will close this and re-file as an issue to remove this uhh "feature"
