### ISSUE TITLE
Thimble hangs when deleting last HTML file and refreshing browser.

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.mozilla.org#1652]
I'm consistently able to get Thimble to hang on the "spinning thimble" screen. 

**Steps to reproduce**
* Create a new project from scratch (via homepage button)
* Delete the index.html file
* Refresh browser

Result...

![result](https://cloud.githubusercontent.com/assets/25212/22216100/8de3a086-e152-11e6-8127-2b9a2591397f.gif)

Clearing indexdb resolves this.

**Comment by Pomax** [comment]
is there a hard dependency on there being an `index.html` in the filesystem?

**Comment by humphd** [comment]
I think so, or the live preview code gets confused.  Likely what's happening here is that when we mount the filesystem, it tries to find an `index.html`, and either fails, or we fail to call a callback/errback.

We mount the filesystem in Thimble here:

https://github.com/mozilla/thimble.mozilla.org/blob/fa3dde088dc016a562520e62a9df1f5558ba8f70/public/editor/scripts/editor/js/bramble-editor.js#L28

Which ends up in here:

https://github.com/mozilla/brackets/blob/master/src/bramble/client/main.js#L372

The `fs.stat()` call here seems to do the right thing in the error case, though:

https://github.com/mozilla/brackets/blob/master/src/bramble/client/main.js#L380

But I suspect it's somewhere along this code path.

**Comment by dangkhue27** [comment]
I would like to work on this if no-one is working on it.

**Comment by humphd** [comment]
Sounds good, @dangkhue27, go for it.

**Comment by humphd** [comment]
From email:

>I am currently working on this issue. I believe I found where the issue is. It is on [line 134 from file RemoteEvent.js](https://github.com/mozilla/brackets/blob/master/src/extensions/default/bramble/lib/RemoteEvents.js#L134) from the bracket repo. Basically, when we delete the index.html file, the editor won’t be viewing any document and when we call “getCurrentlyViewFile” function it will return undefined. However, I am not sure how to fix this issue, one solution would be throwing an error? I also wonder if I am on the right track on fixing this bug? Can you please advise?

I think you're right, it's probably not sending back that `bramble:loaded` event.  I tried to reproduce this locally, and I see the following exception being thrown on my console:

```
RemoteEvents.js:135 Uncaught TypeError: Cannot read property 'fullPath' of null
    at Object.loaded (RemoteEvents.js:135)
    at finishStartup (main.js:124)
    at UI.js:60
    at Directory.getContents (Directory.js:152)
    at UI.js:39
    at UI.js:320
    at HTMLIFrameElement.onload (compatibility.js:50)
```
There are likely a few fixes we could do here.  The first, and simplest, would be to alter the code there to not crash if the return value is null.  Something like this:

```js
function loaded() {
    var initialFile = MainViewManager.getCurrentlyViewedFile();
    var fullPath = "";
    var filename = "" 

    if(initialFile) {
        fullPath = initialFile.fullPath;
        filename = Path.basename(fullPath);
    }
```

This isn't a complete fix, because we probably need to inject a default `index.html` file in the filesystem if there isn't one, and do it prior to this code being called.  However, this will at least stop the crash, and let the initial loading complete.

Try doing that and see what happens.  Then we can keep looking for a better way to deal with an filesystem that lacks an html file.
