### ISSUE TITLE
Thimble + VR : Integrate Aframe's visual inspector tool.

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.mozilla.org#1654]
To see it in action, visit https://aframe.io/examples/showcase/helloworld/ then click on the **Visual Inspector** button in the top right of the screen. 

Could we embed this view in Thimble somehow? Swap it out for the editor when someone wants to use it? Persist the changes made in the inspector in the scene's markup?

**Comment by humphd** [comment]
That page is interesting.  There are a few ways you could go here:

* you could run the same filesystem we use in that page, and then they could "Save" their work in the visual editor, then jump back to Thimble to do the rest of the coding--the changes would automatically show up due to file system watchers

* you could connect their "Save to HTML..." button to Thimble and have it send that to the editor instead

* You could mash the two tools together somehow within Thimble.  I'm not sure if this would be a pretty experience, since they both take a lot of space, and making them live together could be cluttered.

**Comment by pranay414** [comment]
@gideonthomas I would like to try this and I think this is GSoC 2017 project right?

**Comment by flukeout** [comment]
Not pursuing this feature anymore.
