### ISSUE TITLE
Add link to the Help page on the loading screen overlay

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.mozilla.org#1665]
The loading page appears when a project is loading. Sometimes, when something goes wrong, Thimble get stuck here indefinitely. In those cases, it would be good to direct people to the help page: https://support.mozilla.org/en-US/products/webmaker/thimble

![image](https://cloud.githubusercontent.com/assets/25212/22269339/d5d96cac-e23f-11e6-9631-9d13120036ab.png)

**Possible copy**

* If the project won't load, there are some things you can **get help here**
* Is thimble stuck? Try one of the solutions on the help **help page**

We'll need to publish a page on the support site that addresses the common problems & solutions before this goes live and link directly to it.

We can sort out the final copy once we start on this.

**Comment by evantsyferov** [comment]
I want to work on this bug.

**Comment by edyedy123** [comment]
Id like to work on this one too

**Comment by flukeout** [comment]
Are you able to collaborate on this one? Otherwise I think we should give @evantsyferov first crack. Let me know.

**Comment by edyedy123** [comment]
I'll just work on another bug.

**Comment by flukeout** [comment]
Thanks @edyedy123 - what about bug #1333 ?

**Comment by edyedy123** [comment]
Thanks for the suggestion but I've chosen to work on https://github.com/mozilla/thimble.mozilla.org/issues/1229.

[https://avatars0.githubusercontent.com/u/25212?v=3&s=400]<https://github.com/mozilla/thimble.mozilla.org/issues/1229>

Fix or change tutorial styling so that images don't extend ...<https://github.com/mozilla/thimble.mozilla.org/issues/1229>
github.com
Fix or change tutorial styling so that images don't extend over the edge of the tutorial. #1229




________________________________

**Comment by gideonthomas** [comment]
@evantsyferov how are you doing with this issue? If you need any help figuring out where the code lies for this, let us know.

@flukeout quick question: what do you think about only showing that copy below loading project after a timeout (we can try with 15s, and add analytics so that we can tweak it later).

**Comment by humphd** [comment]
@evantsyferov here are a few places for you to start looking at code:

* https://github.com/mozilla/thimble.mozilla.org/blob/fa3dde088dc016a562520e62a9df1f5558ba8f70/views/editor/bramble.html#L118-L125
* https://github.com/mozilla/thimble.mozilla.org/search?utf8=%E2%9C%93&q=spinner-container&type=Code

**Comment by evantsyferov** [comment]
@flukeout do you want the link for the help page to show up when a project is loading or  only when a error occurs with a project loading?

**Comment by flukeout** [comment]
Good question @evantsyferov - what do you think a good time would be? I guess it really depends on the quality of the users network connection.

If we show the button during a normal but slow loading process, it might be a signal that something is broken when it really isn't. My initial reaction is to just add the link or button there all the time.

``Is loading stuck? <a>Try these steps</a>`` kind of thing.

**Comment by flukeout** [comment]
Addressed in https://github.com/mozilla/thimble.mozilla.org/pull/1730
