### ISSUE TITLE
clicking 'Your Projects' returning to Thimble homepage

### ISSUE THREAD

**Issue by lkisac** [mozilla/thimble.mozilla.org#1684]
After creating a new project and saving it, I tried clicking on the 'Your Projects' link in the dropdown under my username and it sends me back to the Thimble homepage.
It was working earlier, but suddenly stopped.  I'm running it in a Chrome browser.
**EDIT:**  I cleared the cache and cookies (for the past day) and refreshed the page and it works now.  What could be the reason for the cache or cookies preventing the project list to be displayed?

**Comment by gideonthomas** [comment]
Hi @lkisac, would you be able to let us know when you encountered this issue and if you tried before that and it worked? We pushed up a fix for this recently so that you wouldn't have to keep clearing your cache, but unfortunately, some people who already experienced this problem might not be able to recover from that issue until they clear their cache once (the idea was that they would never have to do it again).

**Comment by lkisac** [comment]
Hi @gideonthomas, I encountered this issue just yesterday.  It did work for me previous but suddenly didn't after a few minutes until I cleared the cache manually.  Thanks
