### ISSUE TITLE
Allow option to edit .svg files instead of showing a preview.

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.mozilla.org#1745]
One of the cool aspects of SVG files is that you can change them by modifying their code in a text editor. However, in Thimble, we default to the "Image Preview" mode always for .svg files. Let's add a toggle to allow editing ``.svg`` files?

![image](https://cloud.githubusercontent.com/assets/25212/23033468/097d6f28-f42d-11e6-95fd-c60da32f8908.png)

**Comment by humphd** [comment]
This already exists, I wrote it for @Pomax, it's an extension called `SVGasXML` https://github.com/mozilla/brackets/tree/master/src/extensions/extra/SVGasXML.

What we don't have is an easy way to toggle it on/off.

**Comment by Pomax** [comment]
Is this an extension or built in brackets? It feels like a nice thing to have here is a "view as actual file" button so you can toggle between "view image" and "view source" mode.

**Comment by humphd** [comment]
It's an extension I wrote to change how an `.svg` gets loaded (image vs. xml).  We could add some kind of toggle UI to make that switchable at runtime.  Right now it's startup-only.

**Comment by gideonthomas** [comment]
Is this still a good first bug? Not sure what the work to be done here is? Is it just adding the toggle UI?

**Comment by Pomax** [comment]
it would make sense to have the toggle in the extension itself, so that brackets lets you toggle, rather than needing it in our own UI

**Comment by humphd** [comment]
Probably the Image Viewer needs to get extended to show/load the underlying XML when that extension is loaded.  Here's where the Image Viewer code lives: https://github.com/mozilla/brackets/blob/master/src/editor/ImageViewer.js

**Comment by peiying16** [comment]
We can add the this toggle and remember the setting like this issue https://github.com/mozilla/thimble.mozilla.org/issues/1631
One of the difference is that this issue needs a condition after the user clicking on the svc file. If it is "view source", it displays the source code instead of the image view.
Can anyone locate the file which defines the activity when the user click on a svc file. I would like to try this issue.

**Comment by humphd** [comment]
The logic for how to open it happens here: https://github.com/mozilla/brackets/blob/master/src/editor/ImageViewer.js#L372-L388

**Comment by peiying16** [comment]
Thanks @humphd I got most of the things done. 
However, it still has a bug. For example, if I drag and drop an SVG file, I cannot open it as XML. If I add more than 1 file, I cannot open the last SVG file only. Then I debugged and locate to the getOpenDocumentForPath function on the file https://github.com/mozilla/brackets/blob/master/src/document/DocumentManager.js#L119-L133
It returns null, only when I click on the last SVG file.

**Comment by peiying16** [comment]
Every time I add an SVG file, I need to refresh the page to make the last item works.

**Comment by humphd** [comment]
@peiying16 can you show me after class tomorrow on your laptop?  Maybe we can debug together.

**Comment by peiying16** [comment]
@humphd Sorry, I have another class.  I can show you Friday if you have time.

**Comment by humphd** [comment]
OK, we that works too.  My guess is that the image viewer is not considered a document, so doesn't get loaded.  Likely what you have to do is close/re-open the image (in image view or editor) when the preference gets flipped.  It's just a state issue, since you are expecting a different outcome now, but were running under the old assumption before the pref was flipped.

**Comment by peiying16** [comment]
I give up this issue.

Here are some codes I added. 
https://github.com/peiying16/brackets/tree/issue1745
https://github.com/peiying16/thimble.mozilla.org/tree/issue1745

I add a toggle under editor option. It determines if it will show image or the code.
The problem is that it only works after I refresh the page. If I don't refresh, when I click on the svg file, the editor doesn't show image or the codes (does nothing).

**Comment by peiying16** [comment]
https://github.com/mozilla/brackets/issues/494
This issue may help fixing this bug.
