### ISSUE TITLE
Missing "Project Title" on editor header

### ISSUE THREAD

**Issue by humphd** [mozilla/thimble.mozilla.org#1747]
![screen shot 2017-02-16 at 3 08 49 pm](https://cloud.githubusercontent.com/assets/427398/23038969/e82b46ba-f459-11e6-9c72-d4831109f9e1.png)

On our [staging server](https://bramble.mofostaging.net) I'm noticing that we suddenly don't have any text for the project title.  Above, the top is staging, bottom is production.

**Comment by gideonthomas** [comment]
This seems to only be the case for anonymous projects.

**Comment by omytryniuk** [comment]
I would like to work on this bug

**Comment by humphd** [comment]
@omytryniuk it's yours, go for it!  I think a pretty recent commit introduced this, so you might want to take a look back over our recent fixes.

**Comment by Pomax** [comment]
If you're feeling adventurous, you can use git's "bisect" functionality for this: it's a way to say "what I'm looking at right now looks right/wrong" and have git narrow down which exact commit makes the code change from right to wrong, really quickly so you can look at what got changed.

You start by saying `git bisect start` while on master, and because master has the problem we want to investigate, you say `git bisect bad` to let git know there is a problem. You can then look at the commit history for thimble over on https://github.com/mozilla/thimble.mozilla.org/commits/master and pick something from, say, a few days ago and then check that out using `git checkout commitHashCodeHere`. You can then run thimble again. If that has the problem too, `git bisect bad` and you pick an (even) older commit, and repeat. If, however, things look good, you say `git bisect good` and then git starts doing the magic for you. Once it knows at least one bad and one good point, it will pick a new commit for you so that all you have to do is run Thimble, and say `git bisect good` or `git bisect bad` based on what you see Thimble do. After a few of those (usually less than 10) git will be able to tell you exactly which commit introduced the problem.

**Comment by omytryniuk** [comment]
@Pomax Thank you very much for telling about "bisect". It is a really nice tool to find the issue. @humphd You are absolutely right - it is the result of recent fix. 
Here is the [commit](https://github.com/mozilla/thimble.mozilla.org/commit/392fb9dccc4a228b21dfe88cfe415cb56a6acded) that introduces this.

What I have discovered working on this bug. 
As I understand, [here](https://github.com/mozilla/thimble.mozilla.org/blob/392fb9dccc4a228b21dfe88cfe415cb56a6acded/public/editor/scripts/main.js#L64-L76) we initialize the project. Before we had the init function ProjectRenameUtility.init inside Project.init that actually named the project (by default).

**ProjectRenameUtility.init(appUrl, BrambleEditor.csrfToken);**

Since we do not have this function anymore(after the commit I have mentioned above), the newly created **anonymous** project is missing a title(there is no issue with signed-in users because ProjectRenameUtility.init will be called later separately).
I was playing around and, just for curiosity tried to call this function (as an anonymous user) in main.js. 

  if(!projectDetails.userID){
		  // Initialize the project name UI
		  ProjectRenameUtility.init(appUrl, BrambleEditor.csrfToken);
  }

It added the title, however when I rename the project afterwards, the title name was not saved. The reason is that in the new fix, ProjectRenameUtility requries 3, not 2 as before arguments. The last one arg is publisher:  function ProjectRenameUtility(appUrl, csrfToken, publisher) 
I might be wrong, but as I understand we can pass "publisher" argument only if the user is **logged-in**, otherwise, publisher is undefined and [this function](https://github.com/mozilla/thimble.mozilla.org/blob/392fb9dccc4a228b21dfe88cfe415cb56a6acded/public/editor/scripts/editor/js/fc/project-rename.js/#L136) fails when I rename the project name. 

I will work on it these days and I hope I will be able to fix it as soon as possible. I would also like to hear your thoughts, suggestions that can be helpful. Especially, @gideonthomas, I know you were working on this part of code before, and I would really appreciate if you give me some advice. Thank you very much!

**Comment by humphd** [comment]
Nice debugging work @omytryniuk!  CC'ing @lkisac who might be interested in this regression.

@omytryniuk a tip for you: when you write code snippets in issues like you did above, you can use [backticks](https://help.github.com/articles/creating-and-highlighting-code-blocks/) to format it and do highlighting.  It helps the code stand-out, and keep its indentation.

**Comment by omytryniuk** [comment]
Thank you, @humphd!
Basically, I was able to fix it in the next way. Here is my solution:

1. Even it is anonymous, we should call ProjectRenameUtility.init from Project.init() to give the title to our project. There is no need to do it for logged-in users, because it will be called twice in the app, as  ProjectRenameUtility.init for logged-in users is called [here ](https://github.com/mozilla/thimble.mozilla.org/blob/392fb9dccc4a228b21dfe88cfe415cb56a6acded/public/editor/scripts/editor/js/fc/bramble-ui-bridge.js/#L344). In our case, we will call ProjectRenameUtility.init here to rename **ONLY** anonymous project. otherwise, logged-in user's project will be renamed twice.

```javascript
  function init(BrambleEditor, Project, SSOOverride, ProjectRenameUtility) {
  
    var thimbleScript = document.getElementById("thimble-script");
    var appUrl = thimbleScript.getAttribute("data-app-url");
    var projectDetails = thimbleScript.getAttribute("data-project-details");
    var editorUrl = thimbleScript.getAttribute("data-editor-url");
	
    // Unpack projectDetails details
    projectDetails = JSON.parse(decodeURIComponent(projectDetails));
	
    Project.init(projectDetails, appUrl, function(err) {
	
      if (err) {
        console.error("[Bramble] Failed to load Project state, with", err);
      }

      // Initialize the name UI for an anonymous project
      if(!projectDetails.userID){
        ProjectRenameUtility.init(appUrl, BrambleEditor.csrfToken);
      }
	  
      // Initialize the login links
      SSOOverride.init();

      BrambleEditor.create({
        editorUrl: editorUrl,
        appUrl: appUrl
      });
    });
  }

  require(["bramble-editor", "project/project", "sso-override", "fc/project-rename"], init);
```

2. It will be successfully renamed, however, if we want to rename it again(still anonymously), this time using UI, we will get an [error](https://github.com/mozilla/thimble.mozilla.org/blob/392fb9dccc4a228b21dfe88cfe415cb56a6acded/public/editor/scripts/editor/js/fc/project-rename.js#L136)
My solution is to check whether user is logged-in or not, before executing this line. 

```javascript
function save(context) {
    context.saveButton.text("Saving...");

    persist.call(context, context.titleBar.val(), function(err) {
      if(err) {
        console.error("[Bramble] Failed to rename the project with ", err);
        return;
      }

      Project.setTitle(context.titleBar.val(), function(err) {
        if (err) {
          console.error("[Bramble] Failed to update the project internally: ", err);
          return;
        }
        editingComplete(context);
        analytics.event("ProjectRenamed");
	
        //Check whether the project is not anonymous 
        if(context.publisher){
	    context.publisher.showUnpublishedChangesPrompt();
        }

      });
    });
  }
```

I think the people who worked on the previous bug did a great job, and that is why I was trying to make the changes that do not affect their work. 

Here is how it works now. 
![fix1](https://cloud.githubusercontent.com/assets/13225708/23562185/7286f26c-000f-11e7-8727-99422a14fd77.gif)

**Comment by humphd** [comment]
Pull Request please!

Also, I love how you talked about the good work already done on this code, and wanting to work with it to improve things.  Open source is always about a community of developers and users iterating on something to make it better bit by bit, vs. throwing things out and starting over.  Glad you've had that same realization!
