### ISSUE TITLE
Create a default index.html when the project folder does not have one

### ISSUE THREAD

**Issue by dangkhue27** [mozilla/thimble.mozilla.org#1778]
This is a follow up from issue #1652. @humphd said:

> This isn't a complete fix, because we probably need to inject a default index.html file in the filesystem if there isn't one, and do it prior to this code being called. However, this will at least stop the crash, and let the initial loading complete.

The solution I am proposing is to create a default `index.html` file [after looking for the index.html](https://github.com/mozilla/thimble.mozilla.org/blob/master/public/editor/scripts/project/project.js#L249). If the file is not found, I will create a default index.html after this code.

Please let me know if I should do this approach or something else.

**Comment by humphd** [comment]
NOTE: we have default files already, see https://github.com/mozilla/thimble.mozilla.org/tree/master/default/empty-project.  We would just need to a) `GET` that file from the server; b) `writeFile` it to the user's filesystem.

I think this is a good idea, go for it.

**Comment by dangkhue27** [comment]
Thank you for the advice. I will start working on it.

**Comment by humphd** [comment]
@dangkhue27 how is this coming?

**Comment by babhishek21** [comment]
I'm working on #1776 , which deals with showing a tutorial file by default over any other html file when a project is loaded.
Now as it stands, this issue was fixed in #1822 by making sure that an `index.html` file is created if none exists.
My question is: What do I do, when `tutorial.html` exists, but `index.html` does not? Do I let the code create an `index.html` file, but still show `tutorial.html`?

**Comment by humphd** [comment]
This was fixed in https://github.com/mozilla/thimble.mozilla.org/pull/1822, closing.
