### ISSUE TITLE
Icons in footer are sitting slightly too high.

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.mozilla.org#1827]
![image](https://cloud.githubusercontent.com/assets/25212/23682406/817e2330-0348-11e7-9de7-9a259ba253b9.png)

They need to be moved slightly lower so that they are better aligned with the action labels.

**Comment by Lakshmikanth-mkce** [comment]
I would like to work on this issue

**Comment by hkirat** [comment]
Hey
This seems like an interesting bug
Check this
![screenshot from 2017-03-08 17-11-02](https://cloud.githubusercontent.com/assets/8079861/23702695/5c2567b2-0422-11e7-90d2-372650a23187.png)

At first I thought something was wrong in the allignment of the svg file. So I replaced all the icons with one. 
Turns out thats not the issue. The first three appear in the same line and the fourth and the fifth one are messed up, irrespective of the icon.

I would like to work on this too.

**Comment by flukeout** [comment]
Hey @hkirat - since you're already tackling https://github.com/mozilla/thimble.mozilla.org/issues/1824 let's let @Lakshmikanth-mkce take a shot at this one. That is strange though, about the 4th icon!

**Comment by hkirat** [comment]
Hey @flukeout,
Sure no issues. I'll close my P.R. on the same.

**Comment by flukeout** [comment]
@Lakshmikanth-mkce - are you still working on this issue?

**Comment by hkirat** [comment]
@Lakshmikanth-mkce : The fix will be similar to [this](https://github.com/mozilla/thimble.mozilla.org/pull/1832) P.R.

**Comment by hkirat** [comment]
I think this was fixed [here](https://github.com/mozilla/thimble.mozilla.org/commit/21545ddd9fb513dbf61a327c7a35bb6de7247e5c#diff-93529a1b7567a5ac2701f243f7b48e9eL156)
Should be good to close.

**Comment by humphd** [comment]
@flukeout can you please close this if it's actually fixed how you want in your other patch?
