### ISSUE TITLE
html tags displayed on the pop-up window

### ISSUE THREAD

**Issue by MargarytaChepiga** [mozilla/thimble.mozilla.org#1833]
Hi,

I notice this bug:
![issue 1](https://cloud.githubusercontent.com/assets/15698572/23715382/7419ae3c-03fa-11e7-8746-2004722f94dd.gif)

Basically, when uploading a zip or tar file if the file size is up to 3MB then it's going to unzip the files and display a successful message. Inside the message, we can see html tags. 

I want to fix this issue, any suggestions on how to find the pop-up window with the message displayed?

**Comment by humphd** [comment]
I think this is likely the same bug as #1772, and both are going to be in Brackets vs. Thimble.

In Brackets we have a script that localizes strings using the Nunjucks templating library.  It's a bit complicated because we merge two different localization systems, one from Brackets itself, and the other from Thimble's Pontoon translation service.  The details don't really affect this bug, other than to point out that the code that does all this is https://github.com/mozilla/brackets/blob/master/scripts/properties2js.js.

My guess is that we need to turn off autoescaping, see https://mozilla.github.io/nunjucks/api.html#autoescaping when we define the environment here: https://github.com/mozilla/brackets/blob/master/scripts/properties2js.js#L51.

You can run this code by doing the following at the command line in your Brackets repo:

```
grunt exec:localize
```

Which runs this code, btw https://github.com/mozilla/brackets/blob/master/Gruntfile.js#L437
