### ISSUE TITLE
Research: What collaborative features do Students & Teachers want

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.mozilla.org#1837]
Since this is one of our main explicit audiences, we should find out what kind of use cases they are interested in.

**So far, we've heard**
* Teachers need access to student work to make sure that it's appropriate and meets the school's standard for online behavior
  * Currently, one teacher did this by allowing all students to sign in with one shared account and name their Projects after themselves.
* ...

**Comment by flukeout** [comment]
Paging @jgmac1106

**Comment by kyletower** [comment]
As a teacher, I would like to see what each student/user contributed to each webpage/site. This will help me as I grade collaborative web building projects. I would like to see revision history implemented as well. This will allow me to see if the students actually built the website themselves instead of copy/pasting it from else where. Additionally, it will help me see the students' design and thought process. There is a "See Revision History" with a PLAY button on Cloud 9 that shows the source code being built in hyper-lapse speed.

**Comment by gideonthomas** [comment]
Will file follow-up issues about revision history once we get our foundational prototypes set up.
