### ISSUE TITLE
Figure out a better Vagrant Provisioner than shell scripts

### ISSUE THREAD

**Issue by humphd** [mozilla/thimble.mozilla.org#1849]
We see a lot of contributors getting stuck when their Vagrant provisioning doesn't work for some reason.  Sometimes that's due to network errors, filesystem permissions, host OS/bios issues, the list is long.

We currently run our provisioner as a [shell script](https://github.com/mozilla/thimble.mozilla.org/blob/master/scripts/setup-services.sh), which is 100% better than what we had to do before with manual setup.  We could go further, though, and switch to a better provisioner, see https://www.vagrantup.com/docs/provisioning/

Things like Ansible, Chef, Puppet, etc. all have advanced state checking in addition to commands to be run, which means that they will ensure that your environment has whatever it needs vs. just assuming that running the command once is good enough.  Things can and do fail, and we need to deal with that.

If anyone has a background in this, we could use some guidance and help.

**Comment by Pomax** [comment]
Do we have an "inventory" of the pain points for contributors? Are the issues around the console itself, or around not getting enough information from the shell script?

**Comment by humphd** [comment]
What I've seen happen is that the scripts in `setup-services.sh` will fail for some reason, but the Vagrant provisioner will assume things are OK and be done.  If it runs things once, it's happy, and assumes things are OK.  In reality, we need tests to be run that say, "Yes, indeed things are as they should be" and these other provisioners do exactly that.

One of my students expressed interest in working on this, and I spoke with one of my Linux guru colleagues about advice on which one to choose.  Hopefully we can improve this.

**Comment by humphd** [comment]
I've confirmed with my colleague that Ansible is likely a good choice here vs chef/puppet.

**Comment by JohnEJames** [comment]
@humphd  I would like to work on this issue!

**Comment by humphd** [comment]
Great!  Please chat with us as you do it vs. just dropping a big patch when you're done.

**Comment by JohnEJames** [comment]
Hey, @humphd  Thought I'd mention my progress here instead of emailing you. I found a git repo of different examples on ansible here [Ansible Examples](https://github.com/geerlingguy/ansible-vagrant-examples). One of the main problems I am running into is that I can't seem to get Ansible to work on my desktop (Windows OS). So I am kinda at a stand still. I've googled the solution, and have tried the suggestion from other people and none of them seem to work for me. Recently my main focus was getting the playbook file to work before I create the ansible file. I was wondering if you knew anyway to get it installed?

**Comment by humphd** [comment]
What problem(s) are you running into on Windows?  Let's not have you stay blocked, get some details into this bug please, and/or come chat with us on Mattermost.

**Comment by JohnEJames** [comment]
After my investigation and trying to get Ansible to work on Windows and Linux I believe Ansible is not a great provisioner for this project.

# Windows
I first tried to get ansible to work on my main machine that runs Windows, but after investigation it wanted me to install [cygwin](http://cygwin.com/install.html) which provided more of a hassle then a solution. Even with Cygwin installed I was unable to get ansible to work or even install on my desktop. After five hours of trying to get it to work, I decided to start getting ansible to work on my Laptop that runs fedora.

# Linux
 I was able to install ansible very easily with `dnf install ansible`, but after that it started to become more of a hassle. I created a playbook to start testing it and used the command `ansible-playbook playbook.yml --check`. I was able to get the first task to work, but once it started to use the apt command It gave me the error

![screenshot from 2017-03-24 13-01-28](https://cloud.githubusercontent.com/assets/10540058/24305085/23eccdb4-1092-11e7-8e01-4bde4a2df8c9.png)


After Googling this error, and noticing alot of other people have been having the same error, which did not provide a valid solution:
[Python Apt Issue github repo](https://github.com/ansible/ansible/issues/6910) 
[Discussion about the Apt error](https://groups.google.com/forum/#!topic/ansible-devel/GUiOWZD1cO8) 
[Another git repo having an Apt issue](https://github.com/ansible/ansible/issues/14468)

After discussing this with @humphd  we both agreed Ansible is not a valid solution and I should start to look into other Vagrant provisioners

**Comment by JohnEJames** [comment]
So I started to look into chef-zero, I was able to install it and get it working on my windows machine. I created a "Kitchen" and created a recipe but when I tried to test it, it told me that `C:\opscode\chefdk\embedded\bin\perl.EXE: *** Couldn't reserve space for cygwin's heap, Win32 error 0` and with other errors such as recipe not found ect. I'll look into it more, maybe it's the way I'm trying to test it. Just thought I'd give you a status report @humphd

**Comment by JohnEJames** [comment]
Also here is what I get when I try to test the cookbook
![884231008d6710ee9048535c95818624](https://cloud.githubusercontent.com/assets/10540058/24336811/1facb462-1263-11e7-9adc-23cedb93596d.png)

**Comment by humphd** [comment]
This is all very fascinating, and depressing.  More "doesn't work with windows hosts."  What about Puppet?  Can you take a look at https://puphpet.com/ and see if it can do what we want?  It looks pretty easy to use.

**Comment by JohnEJames** [comment]
So from what I've seen from Puphpet I think this is a good solution, plus the GUI interface makes it a lot easier to write.

I wanted to lay out everything I did for the custom server config file I received from the website

for this section I refered the thimble Vagrant file [Vagrant File](https://github.com/mozilla/thimble.mozilla.org/blob/master/Vagrantfile)
![7a1c16b5553e6b7a401dcc274432bd6f](https://cloud.githubusercontent.com/assets/10540058/24528955/f759ddd4-1576-11e7-8ecd-2a6bef0c63cc.png)
![e56340cc4b5005902af3d20ca9248d6a](https://cloud.githubusercontent.com/assets/10540058/24528980/222e6336-1577-11e7-898a-56b12538c588.png)

This section I was not 100% on, so I went with my best judgement.
![b4f481ae5e70fa75d6688b013f67c4ef](https://cloud.githubusercontent.com/assets/10540058/24529008/3aa9475a-1577-11e7-86de-5d2ef8f29fdc.png)

This section is where I added all the APT install packages from the [setup](https://github.com/mozilla/thimble.mozilla.org/blob/master/scripts/setup-services.sh)
![98603100e06dfbbb98e25a6f225a9de3](https://cloud.githubusercontent.com/assets/10540058/24529039/5e4c865e-1577-11e7-947f-503bfd616ba6.png)
Here is where I got Nodejs to install, I was'nt sure on what version so I picked the latest, here is where the NPM install went from the  [setup](https://github.com/mozilla/thimble.mozilla.org/blob/master/scripts/setup-services.sh)
![15084b29fcab2806196fb0c737d95740](https://cloud.githubusercontent.com/assets/10540058/24529209/5b29c94a-1578-11e7-8475-806e078e43a2.png)

Here is the database that I created, I added both "publish" and "webmaker_oauth_test" and made the owner the thimble account
![2c246f65659a1bfed2652619e3a28bbc](https://cloud.githubusercontent.com/assets/10540058/24529080/980f0a7e-1577-11e7-9e61-eff4d226ed42.png)
![7e70f2703cb8a0d653c04b3f2f46f459](https://cloud.githubusercontent.com/assets/10540058/24529081/9964442a-1577-11e7-8197-c70b58c35d38.png)

My biggest problem now is integrating within Thimble, but I wanted to get your opinion first @humphd before I went any further, since you asked for Updates

**Comment by humphd** [comment]
I'm going to give up on this.  Eventually it would be great to not need Vagrant at all.  Until then, shell scripts are the best option.  Thanks for all the experiments.
