### ISSUE TITLE
Get rid of two javascript errors we always see

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.mozilla.org#1862]
When you load the editor, these two fellas here are always popping up...

![image](https://cloud.githubusercontent.com/assets/25212/23813343/553e9852-0593-11e7-86c0-5004128ccad9.png)

...and misleading us into thinking they're significant or related to problems we might be experiencing at the time.

**Comment by humphd** [comment]
paging @gideonthomas... these are because the strings aren't in the `src/` build but are going to be there when we do full localization and serve from `dist/`

**Comment by humphd** [comment]
The code in question is here: https://github.com/mozilla/brackets/blob/master/src/extensions/default/bramble-move-file/main.js#L16-L18

We are using strings from the Brackets `Strings` module, and for some reason it seems to think that they aren't there.  @gideonthomas I wonder if we should change our localization merge code to run on `checkout` vs. as a build step, so your `src/` dir is always right?

**Comment by gideonthomas** [comment]
@humphd I'm not sure I follow. I think the problem here is that we run `npm run unlocalize` which erases the changes we make to `src/nls/root/strings.js` which includes the string for "Move File". I wonder if there is a way to tell it to use strings from `dist` instead.

**Comment by dangkhue27** [comment]
I think I will fix this one before fixing #1227, but i'm not sure what needs to be done here. Can you tell me how can I start with this issue?

**Comment by dangkhue27** [comment]
@humphd Can you give me some details on this issue? I can dig further into the problem.

**Comment by humphd** [comment]
cc'ing @Shank09, @MargarytaChepiga

@gideonthomas can you please shed some light on this issue and what we should do to solve it?

For the benefit of those that I'm including in this bug, here is what I know:

* Adobe uses its own strings in `src/nls/*` and any parts of the Brackets code that use the `Strings` module, are basically using this.
* Thimble (and our fork of Brackets) has some strings that Adobe doesn't need.  Our localizers translate strings for Thimble, and we have scripts that download and merge strings with what Adobe has.  The code is https://github.com/mozilla/brackets/blob/master/scripts/properties2js.js and we call it in the Gruntfile here https://github.com/mozilla/brackets/blob/master/Gruntfile.js#L478 (it's defined here https://github.com/mozilla/brackets/blob/master/Gruntfile.js#L424
* We used to have an issue that whenever you called `npm run build` (which does this localize step I just mentioned) we would pollute the `src/nls/*` dir with all kinds of changes.  Contributors were confused, because they would have a dozen files suddenly change, and git would think they needed to get committed
* I wrote a patch that basically did an "undo" of the localization step after the build was complete, see https://github.com/mozilla/brackets/pull/600.  This is what's causing the strings to not be there anymore in `src/`

The fix is to somehow deal with the fact that we need these strings merged into `src/nls/*` but in such a way that we don't confuse our devs who are either going to a) have changes to files they didn't touch; or b) have strings missing.

For reference, you can manually generate and "ungenerate" these strings by doing:

```bash
$ grunt localize
$ grunt unlocalize
```

@gideonthomas what advice do you have here?  How should we fix this?

**Comment by humphd** [comment]
@dangkhue27 I assume you're doing this, right?  If not, let me know.

**Comment by dangkhue27** [comment]
@humphd Yes, I will try to fix this problem.
