### ISSUE TITLE
Tajik language support

### ISSUE THREAD

**Issue by muhammadkhon** [mozilla/thimble.mozilla.org#1866]
Hi. I am a Tajik programmer. I want to translate thimble Web interface into Tajik Language. Please create necessary TG folder for me and give me access to change it. Thank you.

**Comment by us-mahina** [comment]
Hi. My name is Mahina. I wrote above message from my collegue account,  We want to translate thimble Web interface into Tajik Language. Please create necessary TG folder for me and give me access to change it. Thanks a lot..

**Comment by Pomax** [comment]
Hi @us-mahina that sounds great! We don't do localization directly on the files in this repository, instead we use Pontoon for translations.  Maybe @gideonthomas or @humphd can start a Tajik locale for https://pontoon.mozilla.org/projects/thimble, and then you can start translating the strings that we use in our project.

**Comment by gideonthomas** [comment]
@TheoChevalier, would you be able to enable this locale on Pontoon? I don't see a team for it yet so am not sure of the procedure to get translations for this locale.

**Comment by us-mahina** [comment]
@gideonthomas , nice to meet you. We should be a team to start localization, am I right? We are a group of 6 students (programmers) want to have an access to do that.

**Comment by us-mahina** [comment]
@Pomax , thanks for support, I hope eo start soon :-)

**Comment by TheoChevalier** [comment]
Hi!
> @TheoChevalier, would you be able to enable this locale on Pontoon? I don't see a team for it yet so am not sure of the procedure to get translations for this locale.

Added the locale to Pontoon :) @us-mahina I’ll just need you to review the info here: https://pontoon.mozilla.org/tg/ then you’ll need to create a Pontoon account and let me know which email you’ve used. I’ll make you the locale manager and enable Thimble, then you can add more locale managers and or translators yourself.
You don’t **have** to be several people to start localizing, but of course more people are welcome, especially if you start localizing more projects in the future (you can request projects within Pontoon). Initially you need at least one locale manager. Locale managers can translate, but also assign translator permissions to other people in Pontoon for your locale.

Let me know if you have questions :)

**Comment by us-mahina** [comment]
@TheoChevalier , Thank you very much. Of course, I'll write if some problem

**Comment by Pomax** [comment]
I will close this issue as resolved, as translations for Tajik will get automatically be pushed into the thimble repository: when you get close to 100% translation it would be good to file an issue asking to turn on Tajik localization as one of the "enabled" locales

**Comment by us-mahina** [comment]
Ok. Thanks

**Comment by humphd** [comment]
It's very cool to learn about a language hitherto unknown to you by having people come and want to localize it.  Thank you, and welcome!

**Comment by us-mahina** [comment]
Thanks, good luck for everybody

**Comment by us-mahina** [comment]
@TheoChevalier , I create a Pontoon account by us-mahina@rambler.ru. 
I localized the Pontoon Intro. I hope I could, but if I have some edits, how I can do them? 
And when I can start to translate Thimble? I can not wait the moment I start. Thanks.

**Comment by us-mahina** [comment]
And why it shows 0%

**Comment by TheoChevalier** [comment]
@us-mahina Always great to see people motivated :D Thanks for the address, you should now have access to your locale permissions if you need to add more people: https://pontoon.mozilla.org/tg/permissions/

Pontoon intro is a test project so that people can use it to experiment with Pontoon (it’s the text you see on Pontoon homepage). Right now it says 0% because you’ve added suggestions, since you didn’t have translation privileges (you now have them!). You can now approve your own suggestions, and it will show 100%. Here’s some documentation on how Pontoon works if you want to learn more: https://developer.mozilla.org/en-US/docs/Mozilla/Localization/Localizing_with_Pontoon
To edit existing translations, just open any string, make some edits and hit the save button. You’re done https://pontoon.mozilla.org/tg/pontoon-intro/messages.properties/?string=33052

I’ve enabled Thimble for Tajik, it will be available here at next sync, probably in 10 minutes: https://pontoon.mozilla.org/tg/thimble/

Let me know if you have any issue with Pontoon

**Comment by us-mahina** [comment]
@TheoChevalier , Thanks a lot for help. I have a question: How I can add account to my team?

**Comment by TheoChevalier** [comment]
@us-mahina People need to create an account on Pontoon, then from here https://pontoon.mozilla.org/tg/permissions/ you can click on “all users”, type their address in the search field, then move the address into the translators column and click save. They will be able to submit translations instead of suggestions

**Comment by flukeout** [comment]
Hello @us-mahina - is there an email I can reach you at? I'm collecting information for a new contributors page on the Thimble website and I'd like to include you. Can you please email me at ``luke@mozillafoundation.org``? Thanks!

**Comment by TheoChevalier** [comment]
@flukeout Feel free to use https://pontoon.mozilla.org/tg/contributors/, it’s meant to keep track of active contributors for a locale. There’s also a view per project: https://pontoon.mozilla.org/tg/thimble/contributors/

**Comment by flukeout** [comment]
Thanks @TheoChevalier !
