### ISSUE TITLE
Issue in thimble environment setup(in vagrant up command)

### ISSUE THREAD

**Issue by GingerDragon7** [mozilla/thimble.mozilla.org#1870]
While setting-up the environment for Mozillla Thimble,a issue is coming on entering vagrant up command.

vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Box 'base' could not be found. Attempting to find and install...
    default: Box Provider: virtualbox
    default: Box Version: >= 0
==> default: Box file was not detected as metadata. Adding it directly...
==> default: Adding box 'base' (v0) for provider: virtualbox
    default: Downloading: base
    default:
An error occurred while downloading the remote file. The error
message, if any, is reproduced below. Please fix this error and try
again.

![screenshot 5 1](https://cloud.githubusercontent.com/assets/17198965/23836861/02b8fcbc-07a5-11e7-9d07-5f49ff6b4ce8.png)

**Comment by ryanwarsaw** [comment]
You're attempting to use the Vagrantfile for Thimble in order to run brackets, this is incorrect. Please refer to https://github.com/mozilla/thimble.mozilla.org#installing-brackets-bramble for instructions related to brackets setup.

**Comment by humphd** [comment]
@GingerDragon7 the comment above from @ryanwarsaw is right, but let me elaborate on it a bit.

We have 2 repos, Thimble and Brackets (there are actually quite a few more, but these are the main ones).  Even though they are both needed to run Thimble, we have them separated because we run the editor portion of Thimble (i.e., Brackets) on a different domain than the rest of the Thimble app.  We do this because we allow users to write and execute untrusted scripts.  We can't trust scripts running in Brackets to interact with Thimble (and tokens like user info, session, cookies, etc), so we don't.  The web isolates these two script contexts via the single origin security model.

In your case, you're running a command that should be run in Thimble vs. Brackets, and it complains that it can't find the info it needs to run (e.g., no `Vagrantfile`).

If you have more questions, let me know, but the right answer here is to follow the Thimble instructions in the Thimble repo, and Brackets instructions in the Brackets repo.

**Comment by GingerDragon7** [comment]
@ryanwarsaw @humphd thankyou,i am reading the corresponding documentation and trying again.
