### ISSUE TITLE
Experiment: Collaboration via Operational Transformations (OT)

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.mozilla.org#1876]
According to @humphd - there are some JS libraries already available that do Operational Transforms (including ones specifically related to CodeMirror). OT might be a good way for us to keep the contents of files in sync, so let's try it out.

**MVP Goal**
Create a basic collaboration prototype that allows two people to edit the same file in real time. They will be able to see the changes made to the file as they type.

For now, let's not worry about displaying usernames and cursors, etc. Let's see if we can keep the file in sync without any errors or hiccups.

**Comment by babhishek21** [comment]
I found a few ways we could go about this:

+ [ShareJS](https://github.com/josephg/ShareJS) (now [ShareDB](https://github.com/share/sharedb)). OT library by former Google Wave devs, which is now integrated into a full-blown webapp framework. I had trouble with it back in mid-2016, mostly because the docs were virtually non-existent. I hear @humphd got it running on a Code Mirror instance

+ [y-js](http://y-js.org): A good collaboration library. OT is one part of it. Offline-first and P2P support are two big things (But I'm guessing we don't need WebRTC and related stuff). Comes with its own database and sync models. I tested it locally and it worked great! The adapters are also easy to extend and customize. Comes with a lot of pre-built bindings. While there are none for Code Mirror (that Bramble uses), extending its Text/Rich Text adapter is certainly doable.

+ [Woot](https://bitbucket.org/d6y/woot): This is actually not OT. It achieves collaborative text editing through a different set of algorithms that maintain user intention. Has a good model in Javascript. Just comes with resolution model: so complete freedom to choose our own sync / delivery methods to clients and our choice of DB. Haven't found the time to test it yet. If someone can help me our on this, let me know.

+ [Together.JS](https://togetherjs.com): Mozilla product. Was used in previous implementations of Thimble. Full-blown collaboration suite. But fairly non invasive by keeping its computation in the client. Needs a separate hub server (kind of like in **y-js**, if you don't use a P2P sync model).

I think all of these are pretty great to work with. If I had to choose, I'd go with **TogetherJS** or **y-js**. Please feel free to test about.

I am on a tight ship here as I was planning to make this into my GSoC proposal. Some comments on how to go about that (reach me by email or on the Mattermost instance) would be great!

**Comment by humphd** [comment]
@babhishek21 your research parallels mine.  I found a few other options too, but most of them were abandoned.

I think we need to experiment with a few options, and see what works best.  Trying to design this outright without more data on how different scenarios work isn't wise, imho.  Because Brackets uses CodeMirror, and because so many of these collab/sharing libs have demos that use CodeMirror, I think we should start there.

Brackets wraps a `CodeMirror` instance per editor in `Editor.js`, see https://github.com/mozilla/brackets/blob/master/src/editor/Editor.js#L403.  It then hooks into various events/methods of the `CodeMirror` instance in order to pass data back and forth.  My theory is that we should try to hook in at this level, and then the rest of Brackets will "just work" since it uses the `Editor` vs. the `CodeMirror` instance (usually, there are places where it talks to the `codeMirror` instance).  This is what https://github.com/share/share-codemirror and https://github.com/ejones/sharedb-codemirror do, for example.

We'll have to deal with message routing, since we can have an unlimited number of editors open at a time, and therefore an equal number of `CodeMirror` instances.  We'd have to deal with the fact that the user at one end might have `index.html` open, and someone else in a shared doc might be looking at `style.css`.

We'd also need to deal with the fact that the filesystems have to start in a synced state, and also figure out how to deal with late-joining collaboration users, when the filesystem is in flux.

I feel like I'm repeating things I've said in other bugs.  It might be nice to try and use `Together.js`, but realize that this code is not maintained, and we'd maybe want to update it's OT code using one other other projects.

Anyway, these are some rough thoughts to get us started.

**Comment by humphd** [comment]
Looking more at https://github.com/y-js is making me think we should be doing some parallel exploration with it.  We'd have to work a bit to make it compliant with `CodeMirror` vs. ace/quill, but the fact that they already have shared indexeddb stuff, shared fs, and work with multiple editors, this could be really good.

**Comment by humphd** [comment]
@dmonad has kindly [added CodeMirror support](https://github.com/y-js/y-text/commit/4b01839032d8ead1f8733cde88cc45f3922aae8c) to y-js, see https://github.com/y-js/y-richtext/issues/28#issuecomment-290065283, which also [includes an example](https://github.com/y-js/yjs/tree/11b30c707251a7d56385f6534350ead4a2ff6711/Examples/CodeMirror).  It would be great to play with this, and evaluate whether or not it can meet our needs.  It looks quite promising to me.

**Comment by gideonthomas** [comment]
@hkirat you might also be interested in following this bug

**Comment by hkirat** [comment]
Thanks for referring me here @gideonthomas 

I went through the code of yt.js, especially [y-text](https://github.com/y-js/y-text).
It looks good and thanks to the example above a working prototype of collaboration in Codemirror is ready. (This is something we would've needed to implement in Togetherjs)

As @humphd suggested to include Collaboration in Thimble we would need some more modifications to this.

I tried replicating the example above to run multiple instances of Codemirror like we do in Thimble.
Although the code suggests that handling multiple instances shouldn't be an issue, I ran into a few problems for which I have filed an issue [here](https://github.com/y-js/y-text/issues/8).
This problem seems to exist for Ace as well. You can't run multiple instances of Ace in the same window.
I will be following up on that issue to see what can be done about that.

But overall y-js does seem like a good option for including collaboration in Thimble.

**Comment by hkirat** [comment]
The issue was fixed. 
I've made an example to demonstrate the functioning of multiple instances of CodeMirror in a single webpage [here](https://github.com/hkirat/collaborativeCodeMirror).
This takes care of most of the points mentioned by you above.
Keeping the files in synced state, routing the changes to the right files etc.

**Comment by flukeout** [comment]
Hey cool @hkirat - would you mind creating a gh-pages branch for that repo so we could try it out without having to clone etc?

**Comment by babhishek21** [comment]
@hkirat Good job extending the the Y-js [Codemirror example](https://github.com/y-js/yjs/tree/11b30c707251a7d56385f6534350ead4a2ff6711/Examples/CodeMirror). 

You should however consider defining your own transportation route. Currently their fallback servers tend to be slow (I have experienced latencies upto seconds long) and highly unreliable.

**Comment by hkirat** [comment]
Hey @flukeout 
I have pushed the changes to github pages.
Heres the link : http://singhharkirat.com/collaborativeCodeMirror/

@babhishek21 Yes including our own hubs for transportation would be an option later. This example was meant for the issues related to routing and syncing. 

This is one problem that doesn't happen with Togetherjs though.

**Comment by babhishek21** [comment]
So I found something: [Google MobWrite](https://code.google.com/archive/p/google-mobwrite/). Looks relevant. Uses a Differential Sync and diff-match-patch along with a few other tricks.
