### ISSUE TITLE
using folders in Thimble

### ISSUE THREAD

**Issue by bfalchuk** [mozilla/thimble.mozilla.org#1889]
Can't seem to make folders work correctly.. E.g., when extending the Back To School prototype, as a test i downloaded the main image , created a folder "images" then uploaded the same image into it. Then in index.html style info i reference the jpg from its folder like: 

```
      .front {
        position: absolute;
        width: 100%;
        height: 100%;
        background-color: #ffd800;
        background-image: new url('images/14125034804_225aa8ac52_b.jpg');
        background-size: cover;
        background-position: center;
      }
```
..but this does not appear to work (tried many variations of the url including "./images/<filename>" etc.

How, in general, do we use and make reference to media on our project folders?  In a separate project wherein I am testing a Three.js boilerplate I also failed to achieve image loading in a line like this:

` var floorTexture = new THREE.ImageUtils.loadTexture( '/images/checkerboard.jpg' );`

..even though the above line was in index.html and i have a top level dir called images in which one finds the checkerboard jpg file.

**Comment by bfalchuk** [comment]
Hmm. ok i seem to have resolved half of this .. using the line:

`background-image: url("images/14125034804_225aa8ac52_b.jpg");`

without the 'new' token, and that seems to have made it functional. Sorry for the confusion.
Still working on trying to get the Three.js hello world going, including the scripts that load textures..

**Comment by bfalchuk** [comment]
.. I published a Thimble hello-threejs-world test here: 
[hello-threejs-world-on-thimble](https://thimbleprojects.org/bwf2000/231728/) 
This prj worked on local webserver so i zipped it up and uploaded it to Thimble.  The THREE.ImageUtils.loadTexture(url) doesnt seem to work on upload.. Am I missing something about Thimble that I should know (e.g., permissions, capabilities, .. etc.)? 

For reference, the textured scene should look like this:
![should](https://cloud.githubusercontent.com/assets/26441959/23966267/15236f48-0991-11e7-8325-a24194a1b92f.PNG)

..but ends up looking like this:
![does](https://cloud.githubusercontent.com/assets/26441959/23966276/1e1ad0fa-0991-11e7-9f16-aafabb05a221.png)





Thanks for help.

**Comment by flukeout** [comment]
Hey @bfalchuk unfortunately I think this is happening because of the way that the Thimble environment handles references to files in it's little filesystem..

@humphd explains it in this issue: https://github.com/mozilla/thimble.mozilla.org/issues/1859#issuecomment-285775863

So in your case, I think that's probably what is happening. I believe that you could probably make this work by referencing the texture in a way that will work on the published project. Unfortunately, that won't work in the Thimble editor.

It's something we're aiming to fix.

**Comment by flukeout** [comment]
To illustrate this point, I remixed your project and changes how you reference ``checkerboard.jpg`` in the code to this...

``var floorTexture = new THREE.ImageUtils.loadTexture( './css/images/checkerboard.jpg' );``

This is a path that will work when the project is Published, as you can see here...

https://thimbleprojects.org/flukeout/231738/stem/HelloWorld.html

Again, this isn't great because it won't work in the editing environment but is a sort of halfway there solution.

**Comment by bfalchuk** [comment]
Oh thanks @flukeout . Disappointed that I can't do round-trip in-editor Three.js yet then, though I note that your template 'roadmap' lists Three.js and others, so I'm hopeful for the (near??) future.  (how can i track this?)

Otherwise, i'm finding this tool nonetheless MORE and MORE useful for more vanilla html/js/css projects, so that's great.

**Comment by flukeout** [comment]
Glad to hear it @bfalchuk - I'll see if there's an issue to track this problem anywhere and let you know!

**Comment by humphd** [comment]
@bfalchuk this is high on my list of TODOs, but it's gonna take me a bit to finish reworking things to use service workers.

In the meantime, please keep filing bugs on things you notice that we could improve.  Glad you're liking Thimble!

**Comment by flukeout** [comment]
@humphd is there a tracking issue for the rework?

**Comment by humphd** [comment]
https://github.com/mozilla/brackets/issues/549 is probably the best one.

**Comment by flukeout** [comment]
We should add something to our in-progress help file about this too. I'll do that.

**Comment by flukeout** [comment]
Closing this issue as it's known and as addressed as it will be for now.

**Comment by flukeout** [comment]
@bfalchuk - also, if you haven't give A-frame a try - works pretty well in Thimble.
