### ISSUE TITLE
Consolidate issues for Thimble, Brackets, Publish, ID, Login into Thimble repo

### ISSUE THREAD

**Issue by humphd** [mozilla/thimble.mozilla.org#1899]
I want to propose that we merge the issues for all these repos into mozilla/thimble.mozilla.org.  We've basically been doing this with Thimble and Brackets, and it's mostly worked out OK.  Users have no idea where the boundary between the various repos is when they report something--they just use "Thimble" so file bugs there.

Our devs also don't seem to care, since there are ~150 issues being ignored in publish/id/login right now, and I think ~80% need to just get closed.  Whatever was going to happen once upon a time with all these services being separate and properly managed, the reality in 2017 is that there is Thimble, and its dependencies.  Whatever we're going to do with them moving forward might as well get tracked in a place where people are paying attention.

My proposal is that we do a triage of each repo, and anything that's worth keeping, we re-file in Thimble.  Then we close down issues in that repo, and add a note to the readme/package.json about where to file bugs.  From that point onward, we'd just use PRs in those repos, but co-ordinate work and file things in Thimble.

cc @gideonthomas, @simonwex, @flukeout, @cadecairos, @Pomax.

**Comment by ryanwarsaw** [comment]
I like the idea of of consolidating Thimble & Bracket issues, but I think publish, id and login should remain in their respected repositories since they were and may still be used in the future for multiple services, and not just Thimble specifically.

**Comment by humphd** [comment]
Might be used for what?  Unbundle them again in the future when they are needed to stand on their own.  Right now they get no attention, seems like a great way to lose track of things.

**Comment by ryanwarsaw** [comment]
Both services ```login.webmaker.org``` and ```id.webmaker.org``` were used not only for Webmaker, but also in Thimble and the rest of our product offerings. If we were to create a new service today, I would assume we'd likely use our existing architecture for login and OAuth2.

However I'm not as familiar with ```publish.webmaker.org``` but if we're still using it for X-ray Googles, or multiple services besides Thimble I'd put it in the same category as above.

Additionally, we did something similar with Webmaker and I think in this particular case we're going to create bit of an organizational nightmare with many tickets applying to multiple services, and then of course Github notifications not showing tags (hard to sort through, etc).

**Comment by gideonthomas** [comment]
I sorta agree with @ryanwarsaw on this one. Let's consolidate all the Brackets issues into Thimble. For publish, login and id, I suggest we consolidate all the issues specific to Thimble in this repo and the ones that aren't, let's just leave them in their own repo.

For issues that are fairly generic in the three services,
- For publish, let's make a judgement call. If the issue is more relevant to Thimble, let's close and re-file it here. Otherwise, let's just leave it.
- For id.wm.org and login, let's leave the more generic ones there.

**Comment by Pomax** [comment]
I'm going to be a contrarian here and point out that you *cannot* bring issues from one repo into another and expect things to work: github segments code in repositories, and issues relating to code goes with that code, not in some completely other, independent repository. If you want to manage issues across repos, then github *does not have* the UI in place to do that. If that's really what you want, then you need to start using services like ZenHub, and you need to tell your contributors that there will be meta issues that they will not be able to see until they install the same tooling.

The best you can do is dual-file: file the issue on the repo it belongs to, and create a parallel issue on thimble to make sure there is a crosslink. Anything else, and you're fighting how github is structured, instead of taking advantage of it.

**Comment by humphd** [comment]
Closing, as we're not likely to do this.  We tend to file in the Thimble repo now, which is "good enough."
