### ISSUE TITLE
major-version update several dependencies

### ISSUE THREAD

**Issue by Pomax** [mozilla/thimble.mozilla.org#1908]
based on https://github.com/mozilla/thimble.mozilla.org/pull/1828, let's find all the dependencies that require a major version update, and then tackle them one by one:

- [ ] cryptr
- [ ] fs-writefile-promise
- [ ] glob
- [ ] grunt-cli
- [ ] grunt-contrib-csslint
- [ ] grunt-lesslint
- [ ] jquery
- [ ] helmet
- [ ] wolfy87-eventemitter

**Comment by badrmodoukh** [comment]
Hi I would like to work on this :)

**Comment by Pomax** [comment]
@badrmodoukh that's great, please do! Please address each dependency in a separate PR, though

**Comment by badrmodoukh** [comment]
@Pomax just to make sure, I need to make a separate PR for each of these dependencies, but doesn't this mean that when I update all of these dependencies at the end they will not all be gathered together, since each one is in a separate PR

What I am trying to say is, is this the way I am suppose to do this: 

- update the cryptr dependency and send a PR for it
- update the fs-writefile-promise dependency without the updated cryptr dependency and send a PR for it 
- update the glob dependency without the updated cryptr and fs-writefile-promise dependency and send a PR for it
- and so on ...

Is this right?

**Comment by badrmodoukh** [comment]
@Pomax never mind I will just 

- update the cryptr dependency and send a PR for it
- update the fs-writefile-promise dependency with the updated cryptr dependency and send a PR for it
- update the glob dependency with the updated cryptr and fs-writefile-promise dependency and send a PR for it
- and so on ...

This way makes more sense

**Comment by Pomax** [comment]
@babhishek21 no, please do not do that. Each of these updates should work independently of the others, so please literally do file:

- a PR for cryptr
- an independent PR for fs-writefile-promise
- an independent PR for glob

and so forth. None of the major version bumps should in any way need to rely on "another library being a major version ahead". Updating all of them independently should be perfectly valid, as none of them indicate that they rely on each other.

**Comment by badrmodoukh** [comment]
@Pomax sounds good, thanks for the clarification

**Comment by babhishek21** [comment]
@Pomax You mentioned the wrong guy.

**Comment by Pomax** [comment]
my apologies @babhishek21

**Comment by badrmodoukh** [comment]
@Pomax I created the 9 different PR :)

**Comment by Pomax** [comment]
Awesome - some are insta-merges, but some require some more detail testing/investigating *what* changes so we can tell whether there is the potential for bugs.
