### ISSUE TITLE
Ideas to showcase our community

### ISSUE THREAD

**Issue by humphd** [mozilla/thimble.mozilla.org#1911]
I've been interested to see how some of the projects similar to us are doing outreach to their users, showcasing things, and other bits of PR.  We have an amazing community of people who are really good at teaching and learning the web, why don't we do more with that?

Here are some ideas I think we could try:

* Get better at presenting ourselves via Twitter and other social media.  https://twitter.com/MozillaThimble is hilarious and depressing, and https://twitter.com/MozThimble is not much better (253 followers!).  The folks at https://twitter.com/CodePen are doing a great job of this, for example.  It would be great, for example, if we had a way to say, "Check out this cool thing you can do in Thimble" or "User xyz just made this amazing thing, go remix it" or "Thanks to contributor-XYZ for fixing this bug" or "Check out this cool class teacher-xyz is doing in France with Thimble!"  Something playful; something fun, something semi-regular.
* Do some kind of [Twitch](https://www.twitch.tv/) or YouTube channel where people in our community can literally teach the web using Thimble.  Instead of us trying to build starter kits for every possible use case, let's embrace the random.  Why not have people who love Thimble and the web record themselves doing something, maybe trying some new thing in CSS.  When they're done, we put the "show" up online, along with a link to the thing they made so you can remix and do it too.
* I'd love to extend the vibe and focus of https://medium.com/read-write-participate/why-i-love-working-on-mozilla-thimble-8abbac7d1d9b#.e9lvlp53s.  Unlike a lot of tech projects, which are purely technical, for pros only, and focus on a very narrow slice of the web's/world's population, I think we should be celebrating and showcasing who we are a lot more.

What are the other ways that this could happen that I'm not considering?  Let's turn this bug into action items, and file spin-offs based on things we want to try.

We've got a world class tool.  We've got fun people all over the world teaching and learning with Thimble.  We've got endless pre-made platforms we could inject Thimble into vs. trying to build it all from scratch.  We've got lots and lots of people who want to contribute and help, but maybe don't code.  Let's put this altogether somehow.

@jgmac1106, @chrislarry33, @simonwex can you guys please CC people you know in our community who might be good at some of this, or have ideas?

**Comment by jgmac1106** [comment]
I was just talking about this on Telegram with some club captains.

I was highlighting how Hackernoon and FreeCodeClub have become to of the
biggest tech pubs on Medium. Quincy in particualr has done a great job
cultivating a community of writers talking about how and why they learn.

In short term we need:
-Social share buttons in the publishing dialogue
-Utilize the RWP pub on Medium.
-Maybe start a medium series "the new pub type" that just showcase cool
projects
-Instead of trying to establish our own Twitter chat team up with existing
chats to sponsor theirs (#edtechchat, #kidscancode, 5thchat, etc). Draw
from other audiences.
-Still encourage #thimble as a hashtag just for our own data collection. I
haven't set up a tool to scrape the tweets but that is easy enough
-Make sure every contributor registers at mozillians.org for our records.


Long Term
-We need a community space. This could be Discourse but forums are dead and
dying.  Chat apps like Mattermost (or we just give up and accept Telegram
as our default chat app) will be the future plus will integrate the
learning bots to be developed in the future.
-We need to groom non technical community managers.
-Twitch and or Youtube Live integration would be cool. I am also exploring
the Twilio sdk for personal projects but its dirt cheap. Could use that.
-Is there anything in Air Mozilla roadmap that would allow for live
screencasting?
-Once badging gets out of piloting from the IMLS project we should go gung
ho in developing recogintion systems for contributors.

**Comment by humphd** [comment]
https://github.com/mozilla/thimble.mozilla.org/issues/1298 is related to this.

**Comment by flukeout** [comment]
Thanks for getting this started @humphd - I agree we're not doing all of the right things. Some of this stuff is 'features' that we can build, but other aspects require active monitoring and management (curating community projects, posting to twitter, sending out emails if we have a list). We could use that as a lens to prioritize the work. We're stretched as it is just working on the product. 

There is also #1543, related to adding an embed to the Remix button. However, I misinterpreted the issue, and we should probably be adding it to the publish dialog (along with social buttons as @jgmac1106 mentioned.

The old webmaker/thimble had the ability to add your project to a public gallery as a toggle on the Publish process. That gallery sorted these projects by all-time popularity (likes) so the same stuff was always up there. We could definitely improve on that. 

We could either curate what works shows up there or use some kind of criteria.

**Email**
I think setting up an email list could be useful also, we could start with a monthly newsletter type thing aimed at educators. We could include tips on using the tool as well as links to interesting activities / lesson plans.

Anyway, just dropping in some thoughts for now, I'll revisit later. Would be good to chat in person once we've got some more ideas dumped into this issue.

**Comment by jgmac1106** [comment]
I really like the idea of an email newsletter. Especially if we an crawl projects and display some what's new. 

Could also do a section "This weeks (or months) most remixed projects

**Comment by jgmac1106** [comment]
I think we should piggyback off of the mozilla club and campus clubs to really drive the issue.

Worry about anyone actively working on development and managing the explosive growth in the dev community to also focus on the learning community.

Maybe Thimble Community Facilitators become elevated volunteer roles people have to apply for.

**Comment by Pomax** [comment]
I'd try to steer clear of those two particular efforts, as "clubs" are currently being tackled by multiple groups, focussing on different timescales. Adding more overhead there is more likely going to slow things down, rather than give us some synergies.

**Comment by jgmac1106** [comment]
Good point @Pomax I was just trying to think about where the community we are focusing on developing resides. The Club Captain Telegram group seems to be the most active.

Didn't necessarily mean a Club Captain program but just looking there as a source of contributors who could be further groomed. Meant something like sending out an email to RCs and captains asking if they have anyone they would like to recognize or nominate for a "crucial new role to support the Thimble Team"

I just think you @flukeout and @humphd are going to have your hands full supporting the dev community....who should also be engaged in active storytelling.
