### ISSUE TITLE
Black text looks odd with so much white/gray

### ISSUE THREAD

**Issue by humphd** [mozilla/thimble.mozilla.org#1912]
The header has few lone bits of black text that really stand out:

![screen shot 2017-03-23 at 1 27 43 pm](https://cloud.githubusercontent.com/assets/427398/24261199/98e8d228-0fcc-11e7-84ac-50a696a40704.png)

Can we do better?  @flukeout

**Comment by flukeout** [comment]
For sure - unintended consequence of some recent changes.

**Comment by bkim49** [comment]
I would like to work on this bug as well @humphd

**Comment by humphd** [comment]
@bkim49 OK, talk to @flukeout for thoughts on what he needs done.

**Comment by bkim49** [comment]
@flukeout How should this issue be solved? Would you just want me to change the colour of the text?

**Comment by flukeout** [comment]
Hi @bkim49 - you can just match how the text looks in the production site - https://thimble.mozilla.org/ - thanks!

**Comment by bkim49** [comment]
I tried to fix this issue but could not find a solution. I attempted to make it the same as thimble page, but was unable to because the black text is not grouped within a selector. 

`a.navbar-login {
  color: white;
  opacity: 1;
  text-decoration: none;
  font-weight: normal;
}

a.navbar-login:hover {
  .transition;
  cursor: pointer;
  text-decoration: none;
  border-bottom: 1px solid;
}

/* Logged in menu */
#navbar-anonymous {
  position: relative;
  padding: 7px 9px;
  padding-right: 0;
  border-radius: 1px 0 0 1px;
  margin-right: 10px;

  &.strobe {
    -webkit-animation: strobe .3s linear 3;
    animation: strobe .3s linear 3;
  }
}`

`<div id="navbar-anonymous">
            <a title="Sign in to Thimble" id="login-link" class="navbar-login">Sign in</a> or <a title="Create an account" id="signup-link" class="navbar-login">Create an account</a> to Save and <span title="Publish and share your Project" id="navbar-publish-button"><img src="/img/icon/publish.svg" class="icon-publish">Publish</span>
          </div>`

In the thimble page, the opacity of "or" and "to Save and" is at 0.65. 

What I tried to do:
1. I try to change the opacity of navbar-anonymous selector which encapsulates the entire top right textbox. Result: It made "Sign in" and "Create an account" link to have opacity 0.65 as well. This does not solve the issue since in the thimble, these links are set as white.

2. I tried to override the nested selector by specifying its own opacity. 
Result: This did not work either. Apparently opacity cannot be overwritten. 

Only solution I can think of is to encapsulate the black texts into div selector and specifying the opacity separately to other selectors. @flukeout

**Comment by flukeout** [comment]
Hi @bkim49 - I'll check into it now and get back to you shortly.

**Comment by flukeout** [comment]
I think a good approach is to just look at the entire navbar element...

![image](https://cloud.githubusercontent.com/assets/25212/24416518/e3da408e-1399-11e7-81c6-32de5741f92a.png)

Then we can take a look at what styles apply to it...

![image](https://cloud.githubusercontent.com/assets/25212/24416540/f98a2c78-1399-11e7-8a04-527850488430.png)

In produciton, there used to be a ``color: #b9d6c3;`` rule on that element, but now it's missing. Let's set one and see what happens.

We can use the previous color above, but instead, let's use something different. Let's try ``rgba(255,255,255,.65)`` - I like using slightly transparent white because if we end up changing the background color of the navbar, the text will still look good.

OK - give that a shot. If it's working well, please open a PR with the change!

**Comment by bkim49** [comment]
I will try this tonight. Thank you for the feedback! :smile:

**Comment by flukeout** [comment]
Closing - fixed in https://github.com/mozilla/thimble.mozilla.org/pull/1922 - woop! 👍
