### ISSUE TITLE
Improve auto-complete feature.

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.mozilla.org#1919]
Right now our auto-complete seems pretty aggressive, and I'm not sure it's very useful. For instance, take a look at this screencap...

<img src="https://cloud.githubusercontent.com/assets/25212/24421303/9dc1a6b2-13aa-11e7-930c-24ef3a9bc369.png" width="250" />

There is almost no time when this is helpful and I find it quite jarring to see this thing always popping up and going away as I type.

**Questions**
* Do we have more control over when this comes up?
  * Can we show it after you've typed more stuff or when the list of matching options is shorter?
* Can we hook up GA metrics to this to see if it's being used at all?

Anyway, I think we should just disable it by default and make it something you can turn on.

Thoughts?

**Comment by humphd** [comment]
I disagree with this, personally.  I think it's really useful, and you are coming at it as a professional dev who knows what he wants to type.

That said, all these hint mangers are extensions, for example https://github.com/mozilla/brackets/tree/master/src/extensions/default/HTMLCodeHints is for HTML, and https://github.com/mozilla/brackets/tree/master/src/extensions/default/CSSCodeHints is for CSS, etc.  Each one can likely be tuned, and we could teach it how to show you less, or only after you've typed something.  There might also be something we can do in the hint manager that loads all these--maybe it can make decisions about when to ask for hints (no chars vs. 2 or 4, etc).

In terms of GA, there is no analytics mechanism in Brackets at all.  We could a) add it directly to Brackets; b) add an API in Brackets that pushes it out to Thimble, and have Thimble track it.  But I'd question the value of this, since we don't use the analytics we have now.

**Comment by flukeout** [comment]
You're right. I'll close and consider refiling an issue to make autocomplete it an optional, on-by-default setting.

**Comment by humphd** [comment]
#1761 is that bug, I think.
