### ISSUE TITLE
Remove strange effect on items deleted from Your Projects list

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.mozilla.org#1948]
Notice below, as the element disappears, the content sort of slides to the left. Let's get rid of that effect and just try to fade out the item and then collapse the list vertically.

![delete-effect](https://cloud.githubusercontent.com/assets/25212/24619951/b2d7ce5a-1850-11e7-92aa-ed4386feef61.gif)

**Comment by bbhagwandeen** [comment]
I'd like to work on this!

**Comment by bbhagwandeen** [comment]
Can you explain the collapsing a little more?

**Comment by flukeout** [comment]
Sure yeah...

* First, fade out the item so there is just a gap in the list
* Then, bring up the items below it so the blank space collapses

It's similar to what is happening now, we just need to separate the transition into those two phases. Let me know if that helps.

**Comment by bkim49** [comment]
`I would like to work on this bug! Thank you @flukeout

**Comment by bbhagwandeen** [comment]
@bkim49 im working on it still

**Comment by babhishek21** [comment]
This is missing a `assigned to contributor` label.

**Comment by bbhagwandeen** [comment]
Almost finished with this. Hoping to finish today. It takes a few minutes to add a new project to test the deletion so that keeps me back.

**Comment by bbhagwandeen** [comment]
Ok. So had a unfortunate setback yesterday. Was using Opera to do all the open source work I've been doing and for some reason, the fadeOut effect to the left wasn't working for me, so I thought I'd update the repo. Bad Idea. 45 mins per `vagrant up` and with a few errors, this adds up. I remember that once i updated the repo, I should also run `npm run build` in brackets but that didn't help last night. Did it again this morning and thimble starts up fine now. 
However, the fadeOut doesn't work in Opera at all. Wasn't using Chrome all this time because there was an error where Chrome refused to load a font (I assume because of an extension). Tried disabling all adblockers but the issue persisted. So, I downloaded an extension that power offs all other extensions until i push the button again and everything works fine: I can see the fadeOut effect working perfectly. 
Now I can continue working on this....

**Comment by flukeout** [comment]
Thanks for the udpate @bbhagwandeen

**Comment by ryanwarsaw** [comment]
@bbhagwandeen If you ever have questions or problems in the future, definitely come join us over in Mattermost (https://chat.mozillafoundation.org/login)! There are a bunch of people who would be more than willing to help or answer questions 😃

**Comment by bbhagwandeen** [comment]
@flukeout  let me know if [this](https://github.com/mozilla/thimble.mozilla.org/issues/2020) is what you wanted
