### ISSUE TITLE
Add touch events for the remix bar

### ISSUE THREAD

**Issue by gideonthomas** [mozilla/thimble.mozilla.org#2041]
In https://github.com/mozilla/thimble.mozilla.org/pull/1825, we noticed that the touch events for the remix bar don't work (so we removed them).

We need to implement events for the remix bar on touch devices so that it is usable. The code that we removed was:
```js
var isTouchDevice = 'ontouchstart' in document.documentElement;
var detailsBar = $(".details-bar");
detailsBar.attr("style", "");

if(isTouchDevice) {
  detailsBar.addClass("touch-mode");
} else {
  detailsBar.addClass("mouse-mode");
}
```

We also don't use jquery any more so we would need to handle it using regular DOM manipulation.

cc @flukeout

**Comment by aayushsanghavi** [comment]
@gideonthomas I'd like to work on this

**Comment by gideonthomas** [comment]
sure thing @aayushsanghavi! @flukeout and @Pomax might be able to give a bit more information about what's required here.

**Comment by Rajat-dhyani** [comment]
i looked at @Pomax  comment [here](https://github.com/mozilla/thimble.mozilla.org/pull/1825/files/a23d523979ab953f074ec8544c03e651bbaa2bfc#r108536379)
i think ontouchstart works for desktop i.e `return false` (on chrome) only if we are not viewing it in developer mode.
I have done some changes according to touch event [here](https://github.com/mozilla/thimble.mozilla.org/commit/7936e777bdcc2e58224b21959670ad1062f22251)
Though i am not sure if these are the things that you wanted to add here.

@aayushsanghavi  you can check these changes it might help you out if you are still working on this or otherwise i will open up the PR for the same.

cc: @gideonthomas @flukeout

**Comment by aayushsanghavi** [comment]
Looks like you've been working on this @Rajat-dhyani. Its good that you filed a PR. I was actually out of town for a couple of weeks so I was unavailable all this while. I guess you can continue your work on this issue then. 👍

**Comment by flukeout** [comment]
In looking into how this is handled, it seems like we may not be able to reliably detect when a browser is "touch-enabled". Chrome has changed it's implementation of the method we used to rely on. I think we should come up with a different solution here and maybe just rely on media queries and look for screen width, or have a design that just works in both circumstances (move away from ``hover`` or ``mouseenter`` approaches. I'll refile.
