### ISSUE TITLE
My Projects page doesn't scroll, cuts off projects list.

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.mozilla.org#2044]
![image](https://cloud.githubusercontent.com/assets/25212/25828685/79ec1200-3406-11e7-8a11-2a656647a3a1.png)

Looks like there is a ``overflow: hidden`` rule in editor.css that is being applied to this page also.

**Comment by hkirat** [comment]
This seems to be because of the scroll property being set to hidden [here](https://github.com/mozilla/thimble.mozilla.org/blob/master/public/editor/stylesheets/editor.less#L5)

layout.html is included on top of projects.html [here](https://github.com/mozilla/thimble.mozilla.org/blob/master/views/editor/projects.html#L1). Any reason for that? Shouldn't the layout.html present inside the editor folder be restricted only to editor/index.html. 

I think we should add a new folder "projects" [here](https://github.com/mozilla/thimble.mozilla.org/tree/master/views) and shift projects.html there.

Does this seem like the right approach?

**Comment by flukeout** [comment]
Hey @hkirat - that's probably a good idea down the road. For now, I added a new style that overrides the ``overflow: hidden`` in the ``projects-style.less`` stylesheet which gets applied only on the projects list.
