### ISSUE TITLE
When switching locales, stay on the same page.

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.mozilla.org#2102]
Right now if you navigate to the features page, and then switch the locale, you end up on the homepage. We should keep users on the same page.

**Comment by Cryzek** [comment]
I would like to work on this.
One way to do this, would be to save info using cookies, or local storage on the client side. Is this a good idea?

**Comment by humphd** [comment]
I think doing it in session storage probably makes sense, yes.  Thanks for taking this @Cryzek.

**Comment by gideonthomas** [comment]
Actually, we don't need to store anything in cookies. The issue is that the url paths are set incorrectly for the `features` and `get-involved` pages.

I think the only changes we need to make are changing [this](https://github.com/mozilla/thimble.mozilla.org/blob/master/server/routes/main/features.js#L15) to `` `/features${qs}` `` and [this](https://github.com/mozilla/thimble.mozilla.org/blob/master/server/routes/main/get-involved.js#L15) to `` `/get-involved${qs}` ``. That most likely should fix this.

**Comment by Cryzek** [comment]
@gideonthomas I observed that, if I'm on the features page, and switch the locale by clicking on a hyperlink with href such as "/en-GB/", a request is sent with path - "/en-GB/". At this point the information that user was on features page is lost. So ,
- either we can process the request url in frontend by attaching some logic to the click event on hyperlinks OR
- store the path and detect a change in locale on server using some form of local storage.

**Comment by Cryzek** [comment]
Oh. I get it now.  
Thanks @gideonthomas . I have created a PR for this.
