### ISSUE TITLE
link tags do not need to go in the head

### ISSUE THREAD

**Issue by Pomax** [mozilla/thimble.mozilla.org#2143]
adding a link snippet for a css file says 
```
    <!-- Add the <link> tag to the <head> tag of your HTML file -->
    <link href="style.css" rel="stylesheet">
```

but there is no need to do this. It's good form, certainly, but link tags can go anywhere and just work(tm)

**Comment by humphd** [comment]
Making that change would mean fixing this string:

https://github.com/mozilla/thimble.mozilla.org/blob/41e1af8451f4f763f1c9709b035a3f8f2c30092a/locales/en-US/messages.properties#L115

NOTE: if we change that string, we'll need to create a new, versioned key vs. just correcting the text, since we need to trigger a translation update in our localization system.

**Comment by grigoryk** [comment]
https://www.w3.org/TR/html5/document-metadata.html#the-link-element -> the spec implies that it should be in the <head>. I'm pretty sure it'll work wherever, but isn't there a valid perf argument to be made - especially for slower connections - for putting that stuff as high up as possible?

Maybe modify the comment describing the convention & potential performance impact? (if that is, indeed, a thing).
