### ISSUE TITLE
Exporting to zip has been removed. 

### ISSUE THREAD

**Issue by Spaceface13** [mozilla/thimble.mozilla.org#2157]
When making a project I use the publish to see the code but when I get enough done I publish to zip so that I can see the website without having to see the annoying remix button covering certain stuff. Is there any way I can hide the hide the remix button because the publish to zip feature seems to have been removed. Please help.

**Comment by humphd** [comment]
We still have that feature, it's just been moved to the files menu above the File Tree:

![screen shot 2017-05-17 at 10 14 56 am](https://cloud.githubusercontent.com/assets/427398/26158403/c2f03f78-3ae9-11e7-9330-38fa84fe7896.png)

We did this in response to user requests for a way to export projects to ZIP files when they weren't logged in.  Previously we only showed that "Export to .zip" feature when you were logged in, and in your user menu.  By moving it here, it's always available, and people no longer need an account in order to download their project.

Sorry for the confusion. It raises a question: @flukeout, do you think we should repeat that feature in a few places?  For example, we could also put a button to export as zip in the Publish dialog, which is another place people might think to look for it; we could also put it back in the user menu *and* also keep it in the file tree.

**Comment by flukeout** [comment]
Initially I was thinking of putting it at the bottom of the file view below the files, which I think might be a good place for it still. Then we could go back to the Plus icon for the file dropdown and everyone is happy!

**Comment by flukeout** [comment]
Closing this and will file a follow up feature request to potentially move it out of there.

**Comment by humphd** [comment]
Fix incoming in https://github.com/mozilla/thimble.mozilla.org/pull/2174
