### ISSUE TITLE
Rendering project Images from JS

### ISSUE THREAD

**Issue by dgregory10561** [mozilla/thimble.mozilla.org#2158]
When I push an external URL to HTML using the DOM innerHTML method it works perfectly.

When I try to do the same with an internal image, it doesn't render...

 document.getElementById("test").innerHTML = "<img src='selfie1.png'>"

**Comment by humphd** [comment]
So you're trying to use a filename in the project's filesystem as a URL?  Agreed, that should work, and it's a known limitation of our in-browser live development preview.  We're in the process of fixing it, and it's coming pretty soon in https://github.com/mozilla/brackets/pull/725.

For now, if you need to get this working, you'll have to put a element in your DOM like`<img id="img-url" src="filename.png" hidden>` and then read out its `src` attribute at runtime, which will give you a BLOB URL vs. a filename, and then it will work.

Sorry you're running into this.  I'm going to close because it's a known bug.
