### ISSUE TITLE
Figure out translation updating

### ISSUE THREAD

**Issue by Pomax** [mozilla/thimble.mozilla.org#2180]
We've been inventing new keys whenever we need to replace some words or even correct a typo for an established key and this is becoming an intractable solution: we cannot keep adding more and more keys for strings that are the same role with the same core summary. It creates an unmanagable keyset, and we run out of variations for keys fast.

@gideonthomas @humphd  @TheoChevalier what is the reason we cannot just change the key's value, as one would expect to be able to do? If pontoon cannot "see" differences, then that sounds like a bug in pontoon that needs to be addressed, as pontoon already pulls in our master file, and so should be able to, for all keys, compare the new values it sees to the values it already has stored, instantly flagging key/value pairs that need an update (not necessarily "invalidation", but flagging for potential retranslation, where a localizer can go "no need to relocalize, this was a typo fix in the original language that we don't have in our own locale", or can go "wow this is a pretty different string now, this indeed need to be retranslated".

Not being able to update strings is not a maintainable strategy here.

**Comment by TheoChevalier** [comment]
> We've been inventing new keys whenever we need to […] correct a typo for an established key 

Actually, we shouldn’t have changed keys in this case as it does not change the meaning, as explained here https://developer.mozilla.org/en-US/docs/Mozilla/Localization/Localization_content_best_practices#Changing_existing_strings

Regarding why we can’t just update the content, there are different reasons why we can’t just use the diffs. The main one is that strings must be invalidated once the original string has been updated.
For instance, let’s say you’re removing a variable from a string. If you don’t update the string ID, all the translations will keep displaying a broken variable until the translation is updated.

This discussion happened several times at Mozilla over the past 10 (maybe even 15) years, so I’m sure @pike can provide additional background here if needed

**Comment by TheoChevalier** [comment]
Also, not sure I understood the issue with running out of key IDs, you should be able to just increment the ID if you can’t think of an alternative name, right? Like `label` → `label2` → `label3`…

**Comment by Pike** [comment]
What we're doing is effectivly semantic versioning, and as Theo mentioned, if you just change words or typos in English, the intent here is to actually not bother localizers with your stuff at all. And thus, you shouldn't change the ID.

String IDs are a versioned API between the code and each localization, and when you make a change in the code that invalidates previous implementations in localizations, you need to change the contract, both in the caller and the callee. Making the decision on what's a semantic change has been often debated, mostly because there's actually no clean cut. We often face the situation where the question of whether the translation of the previous string is good actually requires you to understand the previous translations. Unclear strings in English are an example for that. Did the localizers understand the string, and actually have already fixed that problem? Or did they misunderstand the string and said something completely wrong? No way to tell without actually speaking a ton of languages.

This unclear line is actually the main reason why we haven't invested in an automated solution for this, and why gettext has all those problems with using English strings as keys for l10n. As comfortable as that is for the developer, it's not good for quality of the localized product.

Also, string IDs should be good variable names, so please don't just add integers. That's one of those cargo cults that started somewhere and don't stop, sadly.

**Comment by flukeout** [comment]
Thanks for chiming in @Pike and @TheoChevalier - if I understand it correctly, at least as far as typos go, we are free to keep using the same key and just update the string in ``en_us``.

@Pomax good to close?
