### ISSUE TITLE
Georgian localization - no one approves suggestions

### ISSUE THREAD

**Issue by georgianizator** [mozilla/thimble.mozilla.org#2239]
@TheoChevalier Hi, I make translation suggestions in Georgian language on pontoon, but seems project managers are not active, because last contributions were made 6 month ago. Can you tell me if there is a way to approve at least my own translations?

**Comment by TheoChevalier** [comment]
Hi @georgianizator, thanks for pinging us, we’ve received your email and are following up there. I’m going to close this issue since there don’t seem to have a Georgian localization for Thimble. In case you want to start localizing Thimble in Georgian, just use the “Request more project” button in Pontoon and we will be happy to set this up for you.
