### ISSUE TITLE
"Oh no, page not found" has odd CSS

### ISSUE THREAD

**Issue by humphd** [mozilla/thimble.mozilla.org#2264]
![screen shot 2017-06-05 at 2 26 56 pm](https://cloud.githubusercontent.com/assets/427398/26798169/87d33e18-49fd-11e7-8814-85cb21564cbd.png)

@flukeout suggests it might be bleeding CSS from the project.

**Comment by flukeout** [comment]
I'll create a project that reproduces this behaviour and post shortly.

**Comment by flukeout** [comment]
Okay yeah, there is an unnecessary link tag to ``style.css`` that the page doesn't need at all, and so it's pulling in the base styles from the project's root (since most of them have a ``style.css``).

Anyway, updated the file, and here we go...

* [error-final-i-swear.zip](https://github.com/mozilla/thimble.mozilla.org/files/1053270/error-final-i-swear.zip)

Sorry about this @cadecairos - would you mind updating the error page again? I'll file a follow-up issue to change this process, as clearly this isn't a great one.

**Comment by gideonthomas** [comment]
I did this.
