### ISSUE TITLE
DELETE for a project is too expensive

### ISSUE THREAD

**Issue by humphd** [mozilla/thimble.mozilla.org#2273]
![screen shot 2017-06-06 at 10 54 45 pm](https://user-images.githubusercontent.com/427398/26860310-498f529a-4b0b-11e7-8ff0-4ff9c167571f.png)

A DELETE of a big project can really crush the publish server.  In terms of optimizations for publish, this is another one to consider whether we can do something simple now, while we rewrite for serveless.  Maybe delete things in the background, but let the request finish, and just remove things from the UI?

cc @gideonthomas

**Comment by flukeout** [comment]
Plus 1 to that - beyond the performance aspect, we can also present the interaction differently in the UI. Currently if you delete 5 projects at once, there's a long delay before they get deleted, one by one. We shouldn't hold up the user-facing UI on this stuff, since the user doesn't really care about the actual time taken.

**Comment by humphd** [comment]
We had another set of bad spikes today, and the culprit was once again `DELETE` on a project.  The problem is database `SELECT`s.  Are we selecting the buffers in order to delete them?  Why would we do a `SELECT` at all vs. just doing a SQL `DELETE` where the project id is set?  cc @cadecairos, @gideonthomas.

![screen shot 2017-06-14 at 11 43 34 am](https://user-images.githubusercontent.com/427398/27141748-067413dc-50f7-11e7-8408-610cb40b2610.png)

**Comment by gideonthomas** [comment]
yeah it's because we do everything at the ORM level. Instead, we can do two optimizations here:
1. Only select the username, published project id which we can use to delete the entire object on S3.
2. Add a migration to make project deletes cascade to file deletes and publishedProject deletes which will in turn cascade to publishedFile deletes. Then, we can just execute a delete query on the project.

**Comment by flukeout** [comment]
"It wont be an actual problem" quote @gideonthomas

**Comment by humphd** [comment]
A bunch of stuff has landed on publish, and I think we're in better shape.  But I wanted to mention that DELETE can still be really expensive.  We had a spike this morning at 4am:

![screen shot 2017-08-18 at 10 49 51 am](https://user-images.githubusercontent.com/427398/29464205-2f72193e-8403-11e7-8550-e42ecaa717aa.png)

Here's one, for example:

![screen shot 2017-08-18 at 10 52 49 am](https://user-images.githubusercontent.com/427398/29464279-6f7c29de-8403-11e7-9293-79c82f527a68.png)

Why is it spending 20s in `delete /projects/{id}` with HAPI?  There's nothing noticeable in the native metrics at the same time period.

**Comment by Pomax** [comment]
Is there a way for us to tell how much time we spend in https://github.com/mozilla/publish.webmaker.org/blob/master/api/modules/projects/routes/delete.js#L15-L22 vs how much time we spend in the actual SQL query?

**Comment by humphd** [comment]
@Pomax I agree, it would be good to do the db deletes, but only trigger the S3 deletes and then return without blocking on their success.  @gideonthomas how hard would that be to do?

**Comment by flukeout** [comment]
@gideonthomas @humphd - also I can just remove the Delete button for now, always an option until we do a proper re-factoring.

**Comment by gideonthomas** [comment]
@humphd I can try to not block on it.
@flukeout, I think we should wait till Monday and see how it's doing and then decide if we want to remove the Delete button

**Comment by flukeout** [comment]
Sounds good - let's chat on Monday then.

**Comment by gideonthomas** [comment]
@cadecairos I did a bunch of research and there isn't really a clean way to do this - it always blocks the event loop at some point (because we use promises) and is hard to predict at which point that happens. Instead, I was wondering, what do you think about running it in a worker? What I was thinking was to set an interval in the worker for every n seconds. Whenever a delete comes in, we send the path list to be deleted to the worker which caches it. When the interval is hit, we run an S3 multiple object delete request with all those files.

**Comment by cadecairos** [comment]
A worker based solution WFM - lets just make sure it's reliable. We could make the worker polling based, rather than interval based. The polling solution would be queue based, and ensure that the worker never gets overwhelmed as it process one thing at a time. (or more, if we run multiple threads/workers)

**Comment by humphd** [comment]
This is what Celery is so good at in Python. Wonder if we could do similar here with a message queue.

On Aug 22, 2017 12:23 PM, Christopher DeCairos <notifications@github.com> wrote:

A worker based solution WFM - lets just make sure it's reliable. We could make the worker polling based, rather than interval based. The polling solution would be queue based, and ensure that the worker never gets overwhelmed as it process one thing at a time. (or more, if we run multiple threads/workers)

**Comment by cadecairos** [comment]
Yeah I'm thinking we could use SQS - but that means we need a solution for local development.

We can try researching nodejs based queues that we can use in localdev, or even as standalone workers in production - however, the logical separation of web and worker dynos on Heroku will make implementing it difficult there.

**Comment by humphd** [comment]
I still think this is a good idea, but might not be necessary with all the optimizations we've made in the past week on the publish db.
