### ISSUE TITLE
Change font style for filenames in dialogs so that they are easier to see when scanning.

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.mozilla.org#2325]
For example, in this dialog... 

![image](https://user-images.githubusercontent.com/25212/27361108-fefd9f0a-55d9-11e7-86d2-1002259609f1.png)

I think we should make the filename more prominent via bolding or something like that?

**Comment by pranavkumar2015** [comment]
I volunteer for this issue.

**Comment by gideonthomas** [comment]
Hi @pranavkumar2015, it looks like this issue was already fixed but we forgot to close it. You might want to check out some of the other issues we have [here](https://github.com/mozilla/thimble.mozilla.org/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aopen%20label%3A%22Good%20First%20Bug%22%20-label%3A%22Assigned%20to%20Contributor%22) to see if anything interests you.
