### ISSUE TITLE
New features not reflected/delayed on production.

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.mozilla.org#2330]
After today's push, we noticed that some of the new code changes don't work reliably. For example, with Image resizing, it works for me on Chrome, but not in Firefox. 

Chrome showed me the blue update bar, but Firefox never did. What could be the cause of these symptoms. I think for @gideonthomas, neither browser has the latest changes.

Curious what could be causing this. In my case, both browsers have their console open with the cache disabled.

cc @humphd

**Comment by flukeout** [comment]
Ok, shutting down Firefox and restarting it brought up the Blue Refresh bar. Refreshing made the new changes show up. Can you try the same @gideonthomas ?

**Comment by humphd** [comment]
This is probably more a learning issue for us about releasing and announcing, than a technical one.  The problem here is that the Service Worker for Bramble caches all the code so it will run offline.  When we push new code to staging/prod, we re-generate the service worker cache, and update our hashes for each file (i.e., it knows when any content changes at the byte level).

The service worker scripts will update themselves, and when they find a new script, install it and fire the event that gives the blue banner.  However, until this happens, you'll have old code.  A recent spec change means that [browsers should now choose](https://stackoverflow.com/questions/38843970/service-worker-javascript-update-frequency-every-24-hours/38854905#38854905) to always load the service worker from the network vs. browser cache--previously it was using headers on the file, which might mean it gets a cached version.

I think the lesson here is that we should alter our language and timing for releases:
* we shouldn't necessarily blog the same day we do a push to prod--let the changes get downloaded by existing users
* we should talk about how we are "rolling out a new feature" vs. "we have shipped"

As a side note: there are a [few strategies](https://github.com/GoogleChrome/sw-precache#runtime-caching) you can use for service worker caching and how you serve the files.  It's possible to do cache-first, network-first, etc.  We currently do cache-first, which is the fastest and best for offline ready-apps.

**Comment by flukeout** [comment]
Okay that sounds good. It's easy enough to change the messaging around that stuff.
