### ISSUE TITLE
Sync files in filesystem between webrtc clients

### ISSUE THREAD

**Issue by hkirat** [mozilla/thimble.mozilla.org#2342]
Right now, Collaboration works only between two open codemirror instances. This is fine as long as we have one file, but if we have more then one file, the changes made by a user in one file will show up in the file opened by the connected users in different files.

Right now, only the text inserted/deleted in each go is transmitted to the connected peers.
We should probably add a new parameter that should be passed, the file path. Files can then be identified on the basis of this path and peers can make the change accordingly. (at the file system level or in the codemirror instance

**Comment by humphd** [comment]
I agree that you're going to need a "routing" layer, which can deal with the path of the current editor.  Editors have `getFile()`, which returns a `File` object, which you can use to do `file.fullPath`.  This path will be absolute in the local filesystem, and each user will have a different root for his/her project files.  You can access that info using the `bramble/StartupState` module:

```js
var StartupState = require("bramble/StartupState");
...
var file = editor.getFile();
var fullPath = file.fullPath;
var relPath = fullPath.replace(StartupState.project("root"), "");
```

Now the `relPath` will be something like `index.html`, and you can use that to route between the collaboration end-points.  On the other end you can simply `Path.join(StartupState.project("root"), relPath)` to create a proper absolute path into *that* user's local filesystem.

**Comment by hkirat** [comment]
Hey @humphd 
Could you elaborate a little more on this one: 
```js
Path.join(StartupState.project("root"), relPath) 
```
Rest of them work fine.

**Comment by humphd** [comment]
When we create projects locally, we write to a so-called "project root" directory.  It's something you can guess, since it will be different for anonymous and authenticated users.  It's the directory that Brackets "mounts" (i.e., what Thimble tells the Bramble API to `mount()`).  Within Brackets you can get that dir by using `StartupState.project("root")`.  The `hosted.js` file uses `var projectRoot = "/7/projects/30";`, but that's just for local dev/debugging.  You can't assume it will be the same on both collaborator's machines.  For example, a file `index.html` might actually be at `/7/projects/30/index.html` on one, and `/165/projects/284/index.html` on another.

**Comment by humphd** [comment]
One thing you could do is recursively walk the project root and send the contents of each file.  I have a skeleton for this already written in https://github.com/mozilla/brackets/blob/master/src/filesystem/impls/filer/FileSystemCache.js.  Here, I walk the project root down and cache files as URLs.  You could modify that code to send the contents over webrtc.

**Comment by gideonthomas** [comment]
Discussion from chat:

> Start by just creating another file that will handle stuff at the file system level. Let's also not start by doing memory backed fs. Start with regular indexeddb since we can swap it out later. Here's the architecture we were thinking about:
Two clients are connected. There are 2 files - index.html and style.css. Client 1 has index.html open and client 2 has style.css. Client 1 types in index.html and will send codemirror events over webrtc over every key press or whatever it is right now. Client 2 receives these events and ignores these codemirror events because it does not have index.html open in the editor. On client 1, every n seconds, the contents of index.html are saved to the fs. When this happens, client 1 will also send a buffer diff (I have code in makedrive that knows how to calculate this and apply it to a buffer that we can adapt) of what was changed since the last time it was saved over webrtc. client 2 gets this and sees that it doesn't have index.htm open in an editor, so applies those diffs to the buffer it has for index.html and then writes it to the fs. So technically, for every change that a client makes to a file, it sends two types of events - one is a codemirror event and the other a buffer diff event. Other clients on receiving these two events will decide which one to use.

**Comment by hkirat** [comment]
This makes sense. However there are a few corner cases I can think of: 
 - Client 2 shifts to `index.html` before the nth second and hence doesn't have the changes made by client 1 yet.

**Comment by hkirat** [comment]
Me and @gideonthomas  had a chat around how we should implement this.
There are two approaches in mind right now: 
1. The one mentioned by gideon in the comment above.
 - File syncing and editor syncing takes place independently.
 - I send two types of events
   - ```js codeMirrorChange(delta, pathToFile) ````- emmitted every time I change something on my cm
   - ```js fileChanges(diffFromPreviousSendToNow, pathToFile) ```- emmitted every nth second by each client

 - If I receive
   - codeMirrorChange(delta, pathToFile)
    I check if I have this particular file open in the codemirror. If I do, I apply `delta` to it, if not I ignore this event
  - ```js fileChanges(diffFromPreviousSendToNow, pathToFile)
   I check if I dont have this file open, and apply the diffs I receive directly to the filesystem.

In this approach, *every* time I switch from one file to another, I need to send this event to all my connected peers as I am not sure if any of them have modified this file, since I have ignored all the codemirror events they sent me for this file.
Other than that this seems like a fine approach to follow.

2. Batching codemirror events.
I send only one event, 
   - ```js codeMirrorChange(delta, pathToFile)``` - emmitted every time I change something on my cm

When I receive 
  - ```js codeMirrorChange(delta, pathToFile)``` 
  I check if I have it open in the editor, if yes, I make the changes.
  If I don't, I store this event, and as I keep receiving these events, I keep batching them together so as to create a net diff that needs to be applied to the file that currently resides in my filesystem.

Every time I switch from one file to another, I check if I had received some changes for this file when I didn't have it open.
If yes, I apply those changes and then load the contents of the file in the editor.
If not, I simply open it.

Also, every nth second I clear all these diffs and store them in the file.

I have thought about both the approaches and both seem good to me. I would love some suggestions on these.

**Comment by humphd** [comment]
I don't think option 2 will work, because you often depend on files that you don't have open in an editor.  For example, a CSS file or JS script, or SVG image.  If the host changes these, I still need to have the changes applied to the *file* so that my preview can show the correct version vs. whatever old thing I have on disk.

I think you need to do option 1.

**Comment by hkirat** [comment]
@humphd In both the cases, files that are not open in the editor remain out of sync for `n seconds`. 
In the first case, I receive the events after n seconds, and in the second one, I keep receiving them, but I apply them to the file system after n seconds/whenever I open the file.

**Comment by hkirat** [comment]
And one case in the 2nd approach which I don't know how to handle would be the following: 
1. client A has `index.html` open, client B has `index.css` open.
2. Client B shifts to index.html, asks A for the current state of index.html, and they start collaborating.
3. Now client B shifts back to index.css
4. Now how does A know what to send back to B, since they were in sync a while back, but aren't right now.
For a client C who hasn't yet opened index.html, client A knows to send the diff between his currently stored file in indexedDB and his current editor version.
However, for client B, he doesn't know at what point he left index.html, hence doesn't know how to bring him back in sync.

**Comment by hkirat** [comment]
Closed via https://github.com/mozilla/brackets/pull/862
