### ISSUE TITLE
Set url for Collaboration server through bramble API

### ISSUE THREAD

**Issue by hkirat** [mozilla/thimble.mozilla.org#2351]
In reference to https://github.com/mozilla/brackets/pull/824#discussion_r125974184

**Comment by hkirat** [comment]
Hey @gideonthomas 
Could you elaborate a little on what is expected here.

**Comment by gideonthomas** [comment]
We want to augment the options passed to [Bramble.load](https://github.com/mozilla/brackets/blob/master/src/bramble/client/main.js#L131) so that it also accepts collaboration options (url, room name, etc.). We would want to store that in a variable here. Then, probably around [here](https://github.com/mozilla/brackets/blob/master/src/bramble/client/main.js#L306), you want to postMessage the collaboration options to Brackets (`_executeRemoteCommand`, here's an e.g. of [how to do that](https://github.com/mozilla/brackets/blob/master/src/bramble/client/main.js#L1007)). Brackets should listen for that event (probably [here](https://github.com/mozilla/brackets/blob/master/src/extensions/default/bramble/lib/RemoteCommandHandler.js#L72)) and run an api call (something like `Collaboration.initialize(options)`) which will start the collaboration stuff.
Note that your collaboration logic will have to change a bit (since it is currently very locked down to the `Editor`). Change Collaboration.js to be like:
```js
var _webrtc;
var _pending = [];
var _codemirror;

function initialize(options) {
    if(_webrtc) {
        console.error("Collaboration already initialized");
        return;
    }

    _webrtc = new SimpleWebRTC({
        // regular options,
        url: options.url || "localhost:8888"
    });

    _codemirror = EditorManager.getActiveEditor()._codemirror;

    _webrtc.joinRoom(options.room, function() { // do stuff });
}

function _handleMessage(message) {
    // stuff you already do in Collaboration.prototype.handleMessage
}

// rest of the functions

exports.initialize = initialize;
exports.<whatever functions you need to expose> = <function name>;
```

In `hosted.js`, you can then pass in options out [here](https://github.com/mozilla/brackets/blob/collaboration/src/hosted.js#L96) to work for either local development of production.

**Comment by hkirat** [comment]
This looks like the perfect approach. 
And where would Collaboration.js reside?

**Comment by hkirat** [comment]
You think it would be wise to have a Collaboration folder? With a CollaborationManager that we can probably include in RemoteCommandHandler?

**Comment by gideonthomas** [comment]
I'm not sure tbh, I'd say go with what you feel is right. I don't think we have created folders in the src/ dir directly before but I don't see why not. It really depends on how much code we intend to write. If we anticipate writing a lot of code, it's better to break them into modules in a folder/file structure (my opinion).

**Comment by hkirat** [comment]
I wouldn't want to disturb the directory structure of brackets. We could restrict to a new folder inside the editor folder if that seems like a good option. 
Or I could start with that and later we could shift accordingly.

**Comment by gideonthomas** [comment]
I think in that case let's just stick to a single file. We can modularize it later into folders (I don't think we want to create a folder in Editor).

**Comment by hkirat** [comment]
Sticking to `src/editor/Collaboration.js` for now
