### ISSUE TITLE
Thimble Project Remix is not rendering

### ISSUE THREAD

**Issue by dgregory10561** [mozilla/thimble.mozilla.org#2383]
My Thimble remix [https://thimble.mozilla.org/en-US/user/dgregory10561/764596/](https://thimble.mozilla.org/en-US/user/dgregory10561/764596/ )
does not render the images in my project.  I keep getting this link/message in the webpage pane:
"https://mozillathimblelivepreview.net/bramble/production/dist/vfs/50316/projects/764596/index.html"

The sharable link is:  https://thimbleprojects.org/dgregory10561/199996/   and this one renders some of the images but not all.  

I have tried it in both Chrome and Firefox to no avail.  I have also republished, and rebooted a few times.

**Comment by humphd** [comment]
@dgregory10561 I'm really sorry you ran into this, and appreciate you reporting it.  We're tracking the issue in https://github.com/mozilla/thimble.mozilla.org/issues/2385, so I'll close this bug and we can continue there.

One thing you can do in the future if you run into odd saving/syncing issues is to add `?logging=1` to your Thimble URL, and it will log extra debug info to the Web Console, which you could then copy/paste into a bug, and might help us track things down or understand more about what's happening.

If you run into other bugs, or have ideas for Thimble, file more bugs.  Glad you're using it to teach people to code!  That's exactly what we hoped people would do.

**Comment by flukeout** [comment]
In addition @dgregory10561 - we have fixed your project and added all of the previously-missing images to the database - it loads as expected now...

![image](https://user-images.githubusercontent.com/25212/28340602-3398fb32-6bc5-11e7-9135-266214392b77.png)

One thing I noticed is that even when your images weren't showing, I could still remix and publish your project, which would make the images work again. So that's something you can try in the future as a fix until we figure out the source of this.

At the time this started happening, did you experience any other issues with Thimble? Were you in the middle of leading a class or something like that that may have caused a usage spike?

Cheers.
