### ISSUE TITLE
Standalone Brackets - Bug when the editor loads with an Image Viewer open

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.mozilla.org#2386]
If you start the brackets editor standalone with the Image Viewer opened as the firs thing (to do this, add an image, select it, then refresh the browser) then the markup for the Image Viewer doesn't get removed when you open another file in the editor (or another viewer).

This is the DOM after I start editing an ``.html`` file, the viewer markup is still there...

![image](https://user-images.githubusercontent.com/25212/28383141-53d27eae-6c75-11e7-8ab5-50f276d30437.png)

This is because the ``destroy`` method for the Image Viewer is never called. This only happens if it's the first thing the editor loads and is the case for other viewers as well.

Not a huge deal as in Thimble we always open an index.html file first.

@gideonthomas might have some more info, as we tried to debug this together and failed.

**Comment by humphd** [comment]
I've seen this before too, and tried debugging it once.  It seems to have to do with some kind of check they do when switching views to determine whether or not to keep a file open, and it being the last file, and maybe not wanting to close everything.

**Comment by flukeout** [comment]
Alright, let's pile it on the heap then and see if it causes any problems.

**Comment by humphd** [comment]
This close behaviour is determined by:

* [Pane.prototype.destroyViewIfNotNeeded](https://github.com/mozilla/brackets/blob/master/src/view/Pane.js#L1274-L1286)
* [Pane.prototype._isViewNeeded](https://github.com/mozilla/brackets/blob/master/src/view/Pane.js#L1243-L1254)

It originally seems to have come from https://github.com/adobe/brackets/pull/8913, but I'm not clear which problem it's solving exactly.  Since we really only ever show content in the first pane (we use the second for the live preview), we could maybe remove this logic.

**Comment by flukeout** [comment]
Suggestion from @humphd - only open HTML / CSS file on startup / refresh.

**Comment by flukeout** [comment]
I'll refile this as the suggestion above ^

**Comment by flukeout** [comment]
Won't refile since we try to open the ``index.html`` file on editor load, and when it's not there, we create and open one.
