### ISSUE TITLE
Locally deployed project running on microsoft edge but not in chrome

### ISSUE THREAD

**Issue by awdDev786** [mozilla/thimble.mozilla.org#2411]
I have seen strange behavior of local deployment which i couldn't understand so need an expert help here.

**Case 1**
I deployed this repository on <a href="http://c9.io">Cloud 9</a>.I am only running 2 services here.
<a href="https://github.com/mozilla/thimble.mozilla.org">Thimble</a> and <a href="https://github.com/mozilla/brackets">Brackets</a>. At first run it isn't loading in chrome browser but woking well in microsoft edge.Showing following error:

     
![capture](https://user-images.githubusercontent.com/29519534/28770761-c79660ac-75f9-11e7-8b18-27a1a6e79f74.PNG)

**Case 2**

I deployed this repository locally on my machine.it is running good i first some executions and then the same problem.running in edge but not in chrome.

Is this any kind of browser's settings issue like cookies etc?

_Note:_  I have tried empty cache and hard reload options too.but once it is stuck it wont run again.

**Comment by humphd** [comment]
The error in Case 1 looks like it's being hosted over `http` vs. `https`, and we use Service Workers, which require `https` unless you are running locally.

The situation with Case 2 is perhaps that we use different caching in Edge vs. Chrome, since only the latter currently supports Service Workers.

Feel free to hop on https://chat.mozillafoundation.org/mozilla/channels/thimble and chat with us if you want to debug.

**Comment by flukeout** [comment]
Closing for now until a follow up is needed.
