### ISSUE TITLE
Default Project CSS has Multiple Font @include Statements Where Only One is Needed

### ISSUE THREAD

**Issue by emctague** [mozilla/thimble.mozilla.org#2462]
In the Thimble default project's `style.css`, the following two `@include` lines are present, to include both Open Sans and Merriweather:

```css
@import url('https://fonts.googleapis.com/css?family=Open+Sans:400,700');
@import url('https://fonts.googleapis.com/css?family=Merriweather:400,700');
```

This could be cut down to one, much simpler `@include` statement without impacting readability:

```css
@import url('https://fonts.googleapis.com/css?family=Open+Sans|Merriweather:400,700');
```

I'd be more than happy to submit a PR for this issue, because it's kinda bugging me. I've already fixed it in [my fork](https://github.com/emctague/thimble.mozilla.org/commit/9772981674f97500cf344c117f3b243627a5423b).

**Comment by ryanwarsaw** [comment]
From a quick glance, I'm not sure if this is a change we'd want to make. I think it might end up confusing Thimbles further, since the special syntax being used to combine the imports may not
be inherently clear to the user, where as IMO it's more clear now with the two differing import(s).

I'd still submit the PR, and then it can be deliberated further on what we want to do with this.

**Comment by gideonthomas** [comment]
Closing since we think it's clearer to keep the code the way it is.
