### ISSUE TITLE
Brackets failing test on local machine

### ISSUE THREAD

**Issue by ericschv** [mozilla/thimble.mozilla.org#2572]
When testing brackets on local machine in the root directory using `npm test`, it fails when it runs a test for "jasmine". At the current moment Mozilla/brackets does not use jasmine for testing.

This is the error message:

![capture](https://user-images.githubusercontent.com/15128090/33722524-367dad9c-db38-11e7-95ea-e14d55a48cca.JPG)

This issue is related to grunt and can be seen calling "jasmine" here:

https://github.com/mozilla/brackets/blame/master/Gruntfile.js#L541

This error does not get catched by Travis ci since it does not call `npm test` directly.

https://github.com/mozilla/brackets/blob/master/.travis.yml#L7

**Comment by humphd** [comment]
I think the proper fix here is to change the `test` grunt task so it doesn't depend on `jasmine`.  It's not good that our code breaks when a developer does the obvious thing and calls `npm test`.  We should make that change, and then change our `test` script in `package.json` to do what we do in the `.travis.yml` file.  Finally, we should alter `.travis.yml` to do a standard `npm test` instead of defining a custom script.

@ericschv, can you work on this?

**Comment by ericschv** [comment]
@humphd yes I would like to work on it.

**Comment by gideonthomas** [comment]
I'm not sure I follow...we don't run any sort of test on brackets (even on Travis) so what would you expect to happen when you run `npm test`?

**Comment by humphd** [comment]
`npm test` should just do our linting

**Comment by gideonthomas** [comment]
Ah ok, that makes sense. I think we should [update our grunt `test` task](https://github.com/mozilla/brackets/blob/master/Gruntfile.js#L541) to only run lint tasks and then remove `grunt build-browser-compressed` from the `npm test` command in `package.json`. Let's also change the `.travis.yml` file so that the `script` is removed and we add a `before_deploy` task (like [this](https://docs.travis-ci.com/user/deployment/s3/#Running-commands-before-and-after-release)) that runs `npm run preproduction`

**Comment by ericschv** [comment]
@gideonthomas what is the reason for adding `before_deploy` in `.travis.yml` with the value of `npm run preproduction`?

**Comment by gideonthomas** [comment]
@ericschv that tells travis ci (our continuous integration platform) to first build brackets (generate the `dist` folder and the built files inside it) using the `npm run preproduction` command before we deploy it to Amazon S3. That way, it will make sure that it deploys the dist folder (which is what we want) only.

**Comment by ericschv** [comment]
@gideonthomas @humphd Thank you both for clarifying what needs to be done.
