### ISSUE TITLE
TypeError: Cannot set property 'scrollTop' of null

### ISSUE THREAD

**Issue by trishla08** [mozilla/thimble.mozilla.org#2598]
Couldn't find this on searching but experienced this error a few times on my Chrome browser.
![image](https://user-images.githubusercontent.com/27439626/35003371-a7237b9a-fb12-11e7-86c3-cd7499022a53.png)

It seems that every time I add content to my page which spans more than normal page height, this 'Uncaught type error' pops up in the console. There is nothing out of place in my codes which leads me to believe it's an error on developer's end. I am only using the layout already provided with a few additions ( a few paragraph tags - which increases page height making it scrollable, a form) and the basic layout JS file. On some searching, it seems that the problem is in the viewport somewhere. Not very sure, though.

**Comment by humphd** [comment]
This is happening here:

https://github.com/mozilla/brackets/blob/master/src/extensions/default/bramble/lib/MouseManagerRemote.js#L65-L67

We have code that attempts to keep the preview page at the same scroll position after a reload, by setting `scrollTop` on `document.body`.  Probably there is some kind of timing bug here, where `document.body` isn't ready yet in the DOM.  We're waiting on `DOMContentLoaded` here, which *might* mean that the body isn't fully ready?  That seems odd to me, but https://stackoverflow.com/questions/2414750/difference-between-domcontentloaded-and-load-events leads me to belive that switching to a `load` event on `window` *might* solve this.

@trishla08 did you want to try and fix this?

**Comment by trishla08** [comment]
It'd be my first fix, I'd be happy to give it a try! @humphd

**Comment by humphd** [comment]
Great, @trishla08, go for it!  You'll need to fork/clone our Brackets repo, even though this bug is here in Thimble:

* https://github.com/mozilla/brackets
* Then follow the install instructions here https://github.com/mozilla/brackets#how-to-setup-bramble-brackets-in-your-local-machine
* For the purposes of working on this fix, you can then just use http://localhost:8000/src/hosted.html, which will load the editor without the rest of Thimble
* See what happens if you change https://github.com/mozilla/brackets/blob/master/src/extensions/default/bramble/lib/MouseManagerRemote.js#L65 to be a `load` event vs. `DOMContentLoaded`

Let me know if you need more help.

**Comment by trishla08** [comment]
@humphd I have made a pull request with that change, I think it fixed it since I don't see the error anymore. I can't be 100% sure since the error seems a bit random, we'd have to test it a few times to be sure.
