### ISSUE TITLE
Implementation of feature of publishing directly to private or public ftp in thimble

### ISSUE THREAD

**Issue by ankit2670** [mozilla/thimble.mozilla.org#2612]
Thimble is a great IDE and does its job well. But if there will be an option to publish the project files directly to an FTP server owned by the user then the professional web designers would also start using thimble. I personally use thimble for any kind of web designing. But publishing the project files to the FTP server myself takes more time and is a very tedious job. Before publishing the project files thimble should ask the user where to publish the project files. There should be two options, either to publish the files to thimble's web server or to the user's ftp server. So if there will be the option to publish the project files directly to the user's ftp server, then it would be very good and also this will increase thimble's user group.

**Comment by ryanwarsaw** [comment]
Thimble was originally designed as a teaching tool, mainly geared towards educators or people who want to learn basic web development skills, so I think this may deviate from that overall objective. I think it's super cool that some people are using it as a go-to tool for any sort of professional development, and I certainly don't want to discourage those who choose to do so.

From an engineering perspective it's not out of the realm of possibility, but would require a decent amount of work from a developer and given how niche of a feature this would likely be to our general audience, I'm sure it makes sense at this time to pursue a proposal like this.

**Comment by humphd** [comment]
From a technical point of view, this is doable.  Probably the best way would be to begin by getting something working with [Brackets](https://github.com/mozilla/brackets) on its own vs. Thimble.

However, it's not a feature we want to support in Thimble.  We already do AWS S3 based publishing, and adding private server support isn't in our roadmap.  I'm going to close this, not because it's a bad idea (it's a great idea), but because we aren't going to get to it, realistically.
