### ISSUE TITLE
Geolocation issue caused by permissions on cross-origin iframes

### ISSUE THREAD

**Issue by samnixon87** [mozilla/thimble.mozilla.org#2614]
Chrome recently (Jan 2018) updated to deprecate support for geolocation on cross origin iframes. In the editor that means geolocation doesn't work. 

A small code change will fix. I.e.`<iframe src="https://example.com" allow="geolocation; microphone; camera"></iframe>`

https://sites.google.com/a/chromium.org/dev/Home/chromium-security/deprecating-permissions-in-cross-origin-iframes

**Comment by humphd** [comment]
@samnixon87 excellent, thank you for filing this.  We should fix this.

@gideonthomas I wonder if we'll need to do: `allow="geolocation *; microphone *; camera *"` on the bramble iframe in order for third-party scripts to get those permissions, too.  What do you think?

**Comment by gideonthomas** [comment]
I assume a dialog pops up requesting the user to grant access to those resources (geolocation, mic, etc.)? When does that happen? As soon as the iframe is created or when one of those features is actually used in the content of the iframe? If it's the former, it would be a crappy experience to always see that dialog even if you aren't going to request any of those resources in the iframe.

**Comment by mklilley** [comment]
Hi @gideonthomas , 

I just tried creating an iframe with `allow="geolocation *; microphone *; camera *"` and I didn't get any popups. Only when I called e.g. `navigator.geolocation.watchPosition` did a popup appear asking for permission. This suggests the user experience won't be impacted by adding `allow="geolocation *; microphone *; camera *"`  to the iframe in Thimble.

Would be great if these extra parameters could be added as I can't use Thimble for my projects otherwise :-( . I'd be happy to have a go myself but I'm not familiar enough with the code base to know where to start.

**Comment by humphd** [comment]
We have a few `iframe`s in Thimble + Brackets:

* https://github.com/mozilla/brackets/blob/master/src/extensions/default/bramble/lib/iframe-browser.js#L49 is where the preview window gets made (this might be where we need the `allow` attribute)
* https://github.com/mozilla/brackets/blob/master/src/bramble/client/main.js#L480 is where we create the iframe that the editor + preview live (it runs on a separate domain from Thimble so we can safely allow users to execute scripts without fear of hacking the app itself).  We might need it there too?  Not sure.

@mklilley if you are willing to do an experiment here, follow the instructions in https://github.com/mozilla/brackets#how-to-setup-bramble-brackets-in-your-local-machine to get Brackets (without Thimble) running on your machine.

**Comment by mklilley** [comment]
Hi @humphd,

I got brackets running locally but there was no cross origin error because all files are being served locally from the same domain.

This is in contrast to full thimble which serves the editor from `https://thimble.mozilla.org/en-GB/anonymous/.....` but the iframe source is `https://mozillathimblelivepreview.net/bramble/production/dist/vfs/.anonymous/projects/....`

I'm not sure what bit of the thimble/brackets setup specifies the iframe source so my current thinking is that in order to test iframe changes i'll need to get full thimble up and running on something like Heroku - unless there are any other options you can think of?

Matt

**Comment by humphd** [comment]
You should be on two different origins with Thimble vs. Brackets, even locally, since you have to run on different ports.  Each separate port will define a different origin.
