### ISSUE TITLE
Uploading a img 1280 x 720 results in it being down scaled to 50%

### ISSUE THREAD

**Issue by htmlgames** [mozilla/thimble.mozilla.org#2617]
image is < 3Mb , however which ever format I try, after uploading it's smaller in dimensions , like it's been through some resizing process.

Is this normal behavior?

EDIT: looks like you get around this by linking to an image instead. Also from someone's blog they reckon you can only have a background image < 250k

**Comment by gideonthomas** [comment]
@htmlgames yes, we resize the image if you're uploading it into Thimble. To preserve the image size, we recommend using a storage service (like Amazon S3 or Dropbox) and linking to it instead. We intend to work on notifying a user via the interface when this happens so that it isn't unexpected.

**Comment by humphd** [comment]
You can see what we're doing here: https://github.com/mozilla/brackets/blob/master/src/filesystem/impls/filer/lib/ImageResizer.js

If you absolutely needed to hack around this, you could do the following:

* rename your file to `image.bin`
* upload `image.bin`
* rename `image.bin` to `image.png`

That should get around the resize logic.  We had to add this because people were adding massive images without realizing.

**Comment by htmlgames** [comment]
:) Nice hack!
