### ISSUE TITLE
kindly add emmet support

### ISSUE THREAD

**Issue by donstevewrites** [mozilla/thimble.mozilla.org#2625]

**Comment by ryanwarsaw** [comment]
I haven't heard of `emmet` before, so I looked into it and while it seems really awesome, it seems more geared towards I'll call them "power users". I'm not sure if this is something a lot of our audience would use, since Thimble is mainly intended to be a teaching tool and not a full fledged code editor.

I'm going to close this for now, but if you have any other thoughts definitely let me know, these types of ideas even if we don't implement them, are super helpful in that it gives us a better understanding of what our users are interested in, and want to see come to Thimble. 😃
