### ISSUE TITLE
thimble -> Electron.js?

### ISSUE THREAD

**Issue by Scrappy-Dev** [mozilla/thimble.mozilla.org#2628]
I am a beginner programmer with some knowledge on what things can do. It would be very great if thimble was also an application. I would do this myself but like I said, I am new to things like this. So maybe somebody could fork this project and edit scripts to go with ElectronJS. Its just an idea though.

If you don't know ElectronJS is a framework using the Chromium framework that allows you to create applications with HTML, CSS, and JS. I just didn't know if everyone was familiar with it.

**Comment by Pomax** [comment]
Hi, thanks for the suggestion! Unfortunately, Thimble's strength lies in not having to leave the browser at all, so converting it into an electron app would negate that benefit.

If someone wants to try to wrap up Thimble as an electron app (the server component would make that rather hard, though) then they should totally try to see if they can make that happen, but this is not a goal for Thimble itself.

**Comment by humphd** [comment]
@Scrappy-Dev I've thought about putting the editor (Brackets) in Electron before, yes.  It's an interesting idea, and would work.  But I think @Pomax is right about having Thimble in Electron being not so easy, since it relies on server code.

If you want to try it, an easy way to begin would be to use https://github.com/jiahaog/nativefier with https://mozillathimblelivepreview.net/bramble/production/dist/hosted.html and you'd have a desktop version of Brackets you could play with without writing any code.
