### ISSUE TITLE
Canvas element

### ISSUE THREAD

**Issue by branhost** [mozilla/thimble.mozilla.org#2629]
I was using a library called [p5.js](https://p5js.org/) which uses the canvas. There was no errors when using it put the canvas element doesn't show up.

**Comment by Pomax** [comment]
If you open your browser's developer console, are there any errors relating to the canvas that you can see?

**Comment by ryanwarsaw** [comment]
Closing this due to lack of information, and no recent response from the issue filer, however if this continues to happen to you feel free to reach out again, and please remember to provide as much information as possible, so we better assist you 😄 

I tested the `canvas` element out, I wasn't able to identify any problems, it could be something related to `p5.js` library, +1 to @Pomax's point a simple code example would be extremely helpful.
