### ISSUE TITLE
Preview don't work on Raspberry pi

### ISSUE THREAD

**Issue by locness3** [mozilla/thimble.mozilla.org#2634]
I'm using a Raspberry Pi as a "computer", but I can't use Thimble with it.
The preview just shows a URL everytime when I use Chromium.
Here's a screenshot :  
![screenshot](https://user-images.githubusercontent.com/37651007/40573737-df3f82a8-60c5-11e8-8741-83706c2521a0.png)

**Comment by ryanwarsaw** [comment]
I don't know if this is related to some other bugs, but I can confirm this happens quite regularly on the Raspberry Pi's, I ran a session of about 25 people and roughly 66% experienced exactly what is demonstrated in this screenshot, when attempting to load a shared project.

**Comment by humphd** [comment]
We've dealt with this a hundred times, and the issue is always related to security/privacy settings on the client browser that we can't control.  I wrote about it here: https://blog.humphd.org/promise-to-catch/

You can force it to *not* use the service worker cache by adding `?cacheType=blob` to your URL.
