### ISSUE TITLE
Offline install on Windows Server 2012

### ISSUE THREAD

**Issue by strelkovandreyvalerievich** [mozilla/thimble.mozilla.org#2676]
Good day!
Can I install Thimble on virtual machine with Windows Server 2012 without Internet connection?

**Comment by Pomax** [comment]
As long as you download all the repositories on a machine with internet access, and do the npm installs for all the dependencies, you can most certainly run the entire setup offline. Please see https://github.com/mozilla/thimble.mozilla.org#manual-installation on how to get everything set up, and then copy every over into your VM.

For copying purposes I would recommend making sure you put all the relevant projects under one master dir so that you can pack it, transfer it to the VM, then unpack it inside the VM.

**Comment by strelkovandreyvalerievich** [comment]
Please tell me which manual is more correct?

1. https://github.com/mozilla/thimble.mozilla.org/wiki/Setting-Up-Thimble-without-Virtualization#installing-the-parts
2. https://github.com/mozilla/thimble.mozilla.org#manually-installing-the-parts

**Comment by Pomax** [comment]
I don't see any errors? But you're far from done, you still have all the other repos to check out and bootstrap (id, login, publish, and brackets)

**Comment by strelkovandreyvalerievich** [comment]
Yes, I just in case I ask if everything is right, I was confused just WARN, WARN, 11 VULNERABILITIES, etc.
Thanks, then I go on

**Comment by strelkovandreyvalerievich** [comment]
Now I'll try to get the editor running
8. Run `git clone --recursive https://github.com/mozilla/brackets`  in new Cmder window

![image](https://user-images.githubusercontent.com/40031705/46253497-2fbb3c00-c48e-11e8-99b6-ef754e0f7118.png)

9. Run `npm install`

And here it seems that something went wrong :(

![image](https://user-images.githubusercontent.com/40031705/46253550-65acf000-c48f-11e8-9220-1106d82ff7a7.png)

**Comment by Pomax** [comment]
The error literally tells you what's wrong, so just read what it says, and solve what it explains is the problem?
