### ISSUE TITLE
Code validation tools report "errors" in Thimble source

### ISSUE THREAD

**Issue by vzt00** [mozilla/thimble.mozilla.org#2685]
In my web development course, students are using Thimble - huge success! Thanks.

However, we are also learning best practices in coding including using code validation tools. Students are confused when the code they created with the default Thimble project templates contain coding "errors" according to the validation.

For example
https://validator.w3.org/#validate_by_input
Warning: Consider adding a lang attribute to the html start tag to declare the language of this document.
From line 1, column 16; to line 2, column 6

I need either a fix or a good story about why this happens.

Thanks

**Comment by dtepe** [comment]
Seems to me like it's just a warning not an actual error.  So as far as I know, warnings are usually "best practices" things such as making sure you declare a language.  Not absolutely necessary but useful if perhaps you are hoping to reach an international audience so that translation tools work right.  So that error can be fixed with `<body lang="en">`.

**Comment by Pomax** [comment]
Indeed, not having a `lang` attribute is not an error, just a warning. You are certainly encouraged to add one for "serious" web pages, but it's not a requirement for a document to be valid HTML5.
