### ISSUE TITLE
Tune cache-related headers for Bramble and Thimble

### ISSUE THREAD

**Issue by humphd** [mozilla/thimble.mozilla.org#621]
We're missing the cache more often than we should be, and it would be good if we tuned the two parts of our app so that they allow caching as much as possible.  https://devcenter.heroku.com/articles/increasing-application-performance-with-http-cache-headers has some good discussion of what needs to be done here.

Let's audit both our Express app for Thimble, and also how we serve the Bramble stuff on S3/nginx.  For example, here's what we send for the `bramble.js` api lib:

```
curl -I https://mozillathimblelivepreview.net/bramble/dist/bramble.js
HTTP/1.1 200 OK
Content-Encoding: gzip
Content-Length: 36246
Content-Type: application/javascript
Date: Sat, 27 Jun 2015 01:37:08 GMT
ETag: "645af570134b3679aeb7c2ac200857dc"
Last-Modified: Fri, 26 Jun 2015 20:31:55 GMT
Server: nginx/1.1.19
x-amz-id-2: 0BJt5rRj2bsOZrVKpfRyeOUpnFLJQrFaE0SpTo0ZVg+NhugL4PaIDGGCJioAZb+Y
x-amz-request-id: 7DD48252CE1E9B98
Connection: keep-alive
```

And here's Thimble:

```
curl -I https://thimble.webmaker.org/
HTTP/1.1 200 OK
Content-Length: 13801
Content-Security-Policy-Report-Only: connect-src 'self' http://*.log.optimizely.com https://*.log.optimizely.com wss://hub.togetherjs.com; default-src 'self'; frame-src 'self' https://docs.google.com https://mozillathimblelivepreview.net/previewloader.html https://login.persona.org; font-src 'self' https://togetherjs.com; img-src *; media-src *; script-src 'self' 'unsafe-inline' 'unsafe-eval' http://mozorg.cdn.mozilla.net http://*.newrelic.com https://*.newrelic.com https://cdn.optimizely.com https://ajax.googleapis.com https://mozorg.cdn.mozilla.net https://ssl.google-analytics.com https://www.youtube.com https://s.ytimg.com https://login.persona.org https://togetherjs.com; style-src 'self' 'unsafe-inline' http://mozorg.cdn.mozilla.net https://ajax.googleapis.com https://fonts.googleapis.com https://mozorg.cdn.mozilla.net https://togetherjs.com;
Content-Type: text/html; charset=utf-8
Date: Sat, 27 Jun 2015 01:26:10 GMT
Set-Cookie: webmakerlogin=s%3Aj%3A%7B%22_csrfSecret%22%3A%22TJZM0temgo7ZY0CceT3BoBKQ%22%7D.FK43ymyyjEFWOKydmGJ%2BN4nIWkfVsNAxsv6iRakYNNs; Domain=webmaker.org; Path=/; HttpOnly; Secure
Strict-Transport-Security: max-age=15768000
Vary: Accept-Encoding
X-Content-Type-Options: nosniff
X-FRAME-OPTIONS: DENY
X-XSS-Protection: 1; mode=block
Connection: keep-alive
```

No `Cache-Control` or `Expires` in either.  We can do better here.

cc @jbuck

**Comment by humphd** [comment]
See also https://developers.google.com/speed/docs/insights/LeverageBrowserCaching

**Comment by humphd** [comment]
https://developers.google.com/web/fundamentals/performance/optimizing-content-efficiency/http-caching?hl=en#cache-control is also helpful.

**Comment by sedge** [comment]
Here are the results of my preliminary research:

### Brackets
*Analysis*:
* Static files, but likely to change at least once a month whenever a fix comes in
  * This means we shouldn't force caching for too long
  * To be flexible, we could upload files least likely to change (e.g. brackets core) and the most commonly built files (e.g. bramble.js) with different caching rules

*Suggestions*:
* Flexible caching requires writing a separate node script to upload to S3, instead of relying on travis-ci's deployment hooks
* Relying on travis-ci limits our caching options to just the `cache-control` and `expires` headers
  * A perfect solution would use the `last-modified` header to only request a file if it's changed, but this isn't possible with travis
  * We could compromise with a reasonable `expires: max-age XXX` directive, forcing the client to redownload the resource every so often

### Thimble
*Analysis*:
* An enormous number of static files! For most, `expires: max-age` plus an `Etag` is probably fine
* Unlike S3, it's hard to know if the "last-modified" date is accurate because of the heroku deploy process. I can look into this, but an `Etag` basically does the same thing

*Suggestions*:
* This is straightforward.
  * Add the appropriate `cache-control` headers on resource responses in the Thimble server logic

cc: @jbuck - Anything to add?

**Comment by sedge** [comment]
As a followup, I think I'm wrong about S3. Since it already returns `last-modified` just adding the `cache-control` header should be enough to get that working.

**Comment by jbuck** [comment]
We ended up doing several things on donate.m.o:

* All unversioned static content (at this point, only html files) has a `Cache-Control: max-age=300, must-revalidate, public` header applied. Examples:
  * https://donate.mozilla.org/en-US/
* Everything else is versioned with a content hash in the filename and has a `Cache-Control: max-age=604800, must-revalidate, public` header applied. Examples:
  * https://donate.mozilla.org/main.d0a6a06cc98907cb9879.js
  * https://donate.mozilla.org/style.d0a6a06cc98907cb9879.css
  * https://donate.mozilla.org/assets/images/mozilla.5e83dba715a0469b92071758876f0373.svg
* We use a mix of tooling ([assets-webpack-plugin](https://github.com/sporto/assets-webpack-plugin) for CSS/JS) and manual hashing (images) to generate the content hashes for files

I wouldn't use the `Expires` and `Last-Modified` header, stick with `Cache-Control`.

**Comment by sedge** [comment]
@jbuck Huh. I'm confused about why you include a hash in the filename. That sounds identical to the purpose of the `etag` header, which would mean you could have avoided having to change filenames. What am I missing here?

**Comment by jbuck** [comment]
The etag header is only useful for the browser. Versioned objects mean that you don't need to run an invalidation when you update an object: http://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/ReplacingObjects.html

**Comment by sedge** [comment]
@jbuck  :+1: I KNEW I was missing something.
