### ISSUE TITLE
Resizing preview / editor by dragging between them should work on the edge between the top bars too.

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.mozilla.org#686]
You should be able to resize by dragging both of the highlighted edges...

![image](https://cloud.githubusercontent.com/assets/25212/8623414/2d1774c6-26e6-11e5-9fec-7a39bcf8494a.png)

**Comment by humphd** [comment]
Fixing this bug is going to involve changes to both Thimble and Bramble.  We have code right now that does this in reverse, namely, listening in Bramble for resize events then posting those to the hosting window via `postMessage`.  The code in Bramble is here:

* https://github.com/mozilla/brackets/blob/master/src/extensions/default/bramble/lib/RemoteEvents.js#L19-L33
* https://github.com/mozilla/brackets/blob/master/src/extensions/default/bramble/lib/RemoteEvents.js#L47-L50

These in turn get picked up by the client API that lives in the hosted Thimble app.  The Bramble Client API bits live here, which listens for these layout changes, and updates the state of the app (i.e., remembers the widths of each panel) before re-firing the event at Thimble:

* https://github.com/mozilla/brackets/blob/master/src/bramble/client/main.js#L282-L286

The Thimble app then deals with these here:

* https://github.com/mozilla/thimble.mozilla.org/blob/fa3dde088dc016a562520e62a9df1f5558ba8f70/public/editor/scripts/editor/js/fc/bramble-ui-bridge.js#L353
* https://github.com/mozilla/thimble.mozilla.org/blob/fa3dde088dc016a562520e62a9df1f5558ba8f70/public/editor/scripts/editor/js/fc/bramble-ui-bridge.js#L13

Doing this in reverse will require adding a new Bramble Client API call (see https://github.com/mozilla/brackets#bramble-instance-methods for list), maybe `Bramble.setLayout(...)` that passes widths for each of the 3 panels.  You can look at how these are implemented to understand the pattern, for example:

* https://github.com/mozilla/brackets/blob/master/src/bramble/client/main.js#L905-L907
* https://github.com/mozilla/brackets/blob/master/src/extensions/default/bramble/lib/RemoteCommandHandler.js#L125-L127

At this point you can call into some API in Brackets to actually update the widths of the panels, possibly using `WorkspaceManager`.

**Comment by humphd** [comment]
I'm going to close this in favour of https://github.com/mozilla/brackets/issues/627 and moving the toolbar into Bramble.
