### ISSUE TITLE
Renaming an already published project doesn't bring up the Update published project option, but it should.

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.mozilla.org#719]
I just renamed my project from "boings" to "joings" yet the project list shows that the project was edited 33 minutes ago. Let's count a project rename as an edit.

![image](https://cloud.githubusercontent.com/assets/25212/8788706/0ea32798-2ef1-11e5-904d-ae76f8603061.png)

**Comment by flukeout** [comment]
Also let's make the "Edited" lowercase

**Comment by humphd** [comment]
@gideonthomas, where does a fix for this go, in Thimble or Publish?

**Comment by gideonthomas** [comment]
Thimble

**Comment by humphd** [comment]
@gideonthomas, can you give a sentence or so about what the fix is, and I can do it.

**Comment by gideonthomas** [comment]
[This](https://github.com/mozilla/thimble.webmaker.org/blob/bramble/public/scripts/editor/js/fc/project-rename.js#L69) should also include a dateUpdated field which should also be added [here](https://github.com/mozilla/thimble.webmaker.org/blob/bramble/app.js#L196) and another line to update the `date_updated` field should go below [this](https://github.com/mozilla/thimble.webmaker.org/blob/bramble/routes/rename-project.js#L6). I think that should be enough to fix this issue

**Comment by gideonthomas** [comment]
This should automatically be fixed once mozilla/publish.webmaker.org#165 lands

**Comment by flukeout** [comment]
Still not fixed, is this a good first bug?

**Comment by humphd** [comment]
@gideonthomas this could use some info, and I'm not sure what's needed exactly.  Can you add a note, at least to clarify your comment about about that patch fixing things?

**Comment by lkisac** [comment]
I would like to work on this bug.

**Comment by flukeout** [comment]
@gideonthomas can you weigh on this and guide @lkisac in the right direction?

**Comment by lkisac** [comment]
I tried replicating the issue it seems to be working for me.  I created a new project, saved it. then checked the project list and it said 'Last edited a few seconds ago'.  Waited for about 10 minutes then renamed and saved the project and it also said 'Last edited a few seconds ago' with the new project name.

**Comment by flukeout** [comment]
One aspect of this that isn't working quite right is that you don't get the option of Updating your published project after changing the name. 

@lkisac - try renaming an already published project. Now click on the Publish button, you'll see that there is no option for Updating the published project, but there should be, since an aspect of it is different now.

**Comment by lkisac** [comment]
@flukeout  Ok.  The 'Update published version' button does not appear after renaming a project, only after making a code change.  I will work on this aspect.

**Comment by flukeout** [comment]
Thanks @lkisac - I'll update the issue title to reflect that.

**Comment by gideonthomas** [comment]
Sorry for chiming in late. Since the initial issue has been resolved, this is no longer a `publish.webmaker.org` patch (will remove the label).

To go about fixing this, @lkisac, you need to do a couple of things:

1. [This function](https://github.com/mozilla/thimble.mozilla.org/blob/master/public/editor/scripts/editor/js/fc/publisher.js#L66-L83) needs to be on the `Publisher` prototype and probably renamed to something that makes more sense in this case (probably something like `showUnpublishedChangesPrompt`). Also change the name wherever it is used in that file.
2. [This line](https://github.com/mozilla/thimble.mozilla.org/blob/master/public/editor/scripts/main.js#L70) will probably need to be moved [somewhere here](https://github.com/mozilla/thimble.mozilla.org/blob/master/public/editor/scripts/editor/js/fc/bramble-ui-bridge.js#L330-L341). You might have to pass in the csrftoken and appUrl (available in options) into the `init` function [here](https://github.com/mozilla/thimble.mozilla.org/blob/master/public/editor/scripts/editor/js/bramble-editor.js#L36)
3. Pass the `publisher` instance into the rename utility's `init` function as well and store it in `this`
4. Edit the rename utility's `save` function to call the publisher's function you created in step 1

That should basically be all the code changes you need. Let me know if you have any questions.

**Comment by lkisac** [comment]
Thank you for the guidance @gideonthomas.  I've adjusted most of the code to your suggestions, but I'm having trouble testing my changes.  I'm running Thimble from my vagrant VM and I'm not able to sign in to my Thimble account this way so I can't test the publish and rename functionality.  I just get a 404 error each time with this error message, "Oh no, page not found!".  I can sign in to my account from the Thimble [website](https://thimble.mozilla.org/en-US/) ok, just not from vagrant.  
Is this an error or is there a way around signing in so I can test the functionality?  Thanks in advance.

**Comment by humphd** [comment]
@lkisac it sounds like you're hitting a bug we fixed earlier this week.  Can you try pulling the most recent changes from Mozilla's master branch for thimble and try again?

**Comment by lkisac** [comment]
Pulling most recent changes from Mozilla master fixed the sign in issue.  Thanks @humphd
