### ISSUE TITLE
Highlight the right-clicked file in the file tree

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.mozilla.org#841]
So I just right-clicked the file tree...
![image](https://cloud.githubusercontent.com/assets/25212/9256361/ec0fa65a-41a3-11e5-905a-0ee0c200b088.png)

I can't really tell which file I'm about to rename or delete. We need a way to highlight the file your'e about to act on, if we can throw a temporary CSS classname on the file while the right-click menu is open, I can style it to make that more clear.

**Comment by gideonthomas** [comment]
@flukeout I'll be terrible at styling this. But I can help you figure out where the code for this lies. So feel free to ping me when you start on this issue.

**Comment by humphd** [comment]
Fixing this means changing the CSS for the `.filetree-context` class in Bramble, for both the light and dark themes in these files:

https://github.com/mozilla/brackets/tree/master/src/extensions/default/bramble/stylesheets

**Comment by Th30** [comment]
I'm interested in helping with this:)

**Comment by flukeout** [comment]
Sounds good @Th30 - While you're at it, are you able to increase the font size in that menu to match the size of the fonts in the file-tree? Totally optional, but would be nice.

**Comment by Th30** [comment]
sure I'll give it my all:)

**Comment by Pomax** [comment]
oh man I just ran into this again today, super excited to see @Th30 tackling this.

**Comment by Th30** [comment]
@flukeout
@Pomax 
@humphd 

Hello!:)

Just an update on the project, I found sometime to take a look at this problem (learning environment too), and managed a quick fix that isn't final...but for update purposes:

<img width="279" alt="screen shot 2017-02-07 at 11 27 54 am" src="https://cloud.githubusercontent.com/assets/3598286/22700422/ab4f5aca-ed28-11e6-99da-0e033a18accd.png">

I'm going to try shifting it to the left hand side so that it's not obstructed by the dropdown when right clicking.

In terms of the menu that will be my next target. 

:)

**Comment by Th30** [comment]
I made a minor adjustment adjustments, managed to make the font sizes match between menu and filetree.

<img width="253" alt="screen shot 2017-02-07 at 7 29 35 pm" src="https://cloud.githubusercontent.com/assets/3598286/22718407/3d200ffe-ed6e-11e6-8580-4d2f0e650fe5.png">

Hope it worked out well:)

**Comment by flukeout** [comment]
Great stuff @Th30 - if you make a Pull Request based on these changes I can try them out and suggest a slightly different treatment. I can help with the CSS

**Comment by Th30** [comment]
@flukeout that would be great! I'll get on the Pull Request right away!

**Comment by gideonthomas** [comment]
Fixed with mozilla/brackets@57d075f78d44af8b5cecea9afbc922c6825c5d58
